// Module included in the following assemblies:
//
// * applications/pruning-objects.adoc

[id="pruning-images-manual_{context}"]
= 이미지 수동으로 쳐내기

[id="pruning-images-conditions_{context}"]
== 이미지 쳐내기 조건

You can apply conditions to your manually pruned images.

* To remove any image managed by {product-title}, or images with the annotation `openshift.io/image.managed`:
** Created at least `--keep-younger-than` minutes ago and are not currently referenced by any:
*** Pods created less than `--keep-younger-than` minutes ago
*** `--keep-tag-revisions` most recent items in `stream.status.tags[].items`
** That are exceeding the smallest limit defined in the same project and are not currently referenced by any:
*** Running Pods
*** Pending Pods
* There is no support for pruning from external registries.
* When an image is pruned, all references to the image are removed from all
imagestreams that have a reference to the image in `status.tags`.

[id="pruning-images-running-operation_{context}"]
== 이미지 쳐내기 실행시키기

.과정

. To see what a pruning operation would delete:

.. Keeping up to three tag revisions:
+
----
$ oc adm prune images --keep-tag-revisions=3 --keep-younger-than=60m
----

.. Pruning every image that exceeds defined limits:
+
----
$ oc adm prune images --prune-over-size-limit
----

. To perform the prune operation:
+
----
$ oc adm prune images --keep-tag-revisions=3 --keep-younger-than=60m --confirm
----
+
----
$ oc adm prune images --prune-over-size-limit --confirm
----

[id="pruning-images-secure-insecure_{context}"]
== secure냐 insecure냐 그것이 문제로다

The fall-back to cases unless `--certificate-authority` is specified:

. The `prune` command is run with the `--force-insecure` option.
. The provided `registry-url` is prefixed with the `http://` scheme.

[id="pruning-images-problems_{context}"]
== 이미지 쳐내기 문제

[discrete]
[id="pruning-images-not-being-pruned_{context}"]
==== Images not being pruned

When default options are used, the image is never pruned because it occurs at
position `0` in a history of `myapp:v2.1-may-2016` tag:

* Specify `--keep-tag-revisions=0` with the `oc adm prune images` command.
+
[CAUTION]
====
This action removes all the tags.
====

* Delete all the `istags` where the position is below the revision threshold,
which means `myapp:v2.1` and `myapp:v2.1-may-2016`.

Such tags tend to have just one image in their history.

[discrete]
[id="pruning-images-insecure-against-secure_{context}"]
==== Using an insecure connection against a secured registry

If you see one of the following `oc adm prune images`
command:

----
error: error communicating with registry
----

By default, the certificate authority data stored in the user's configuration.

Use the `--certificate-authority` option to provide the right certificate.
