= 하드웨어 구성
:toc:
:toc-title:

== 시스템 사양

HyperCloud를 구성하는 노드들의 사양 정보는 다음과 같다. (QA: 메모리 수정했어요 마스터 16 > 8, 워커 32 > 16)
[width="100%",options="header", cols="1,1,1,1,1"]
|====================
|노드|운영체제|CPU|메모리|스토리지
|마스터|Red Hat 계열 8|4|8GB|100GB
|워커|Red Hat 계열 8|8|16GB|100GB
|====================

== 운영체제 설정
인스톨러를 통한 HyperCloud 설치 과정에서 네트워크 포워딩, 호스트 이름, 스왑 메모리, SELinux 관련 설정이 가능하다.

=== 네트워크 포워딩
IP 포워딩 기능을 활성화하기 위해 `sysctl.conf` 파일을 열어 아래와 같이 파라미터의 값을 설정한다.(TD: sysctl.conf 파일의 풀 경로가 어떻게 되나요?) (QA: /etc/sysctl.d 하위에 99-kubernetes-cri.conf와 같은 파일을 추가로 생성하여 아래와 같이 파라미터의 값을 설정한다.) 
[width="100%",options="header", cols="2,1,2"]
|====================
|파라미터|설정값|설명
|net.ipv4.ip_forward|1|IP 포워딩 활성화
|net.bridge.bridge-nf-call-iptables|1|CNI 동작을 위한 iptables forward 활성화
|net.bridge.bridge-nf-call-ip6tables|1|CNI 동작을 위한 ip6tables forward 활성화
|====================

=== 호스트 이름
장비의 식별을 위해 호스트 이름을 설정한다.

. *호스트 이름 설정* +
RFC 1123에 정의된 규칙에 맞게 호스트 이름을 설정한다.
+
----
$ sudo hostnamectl set-hostname k8s-master
----
+
[NOTE]

====
RFC 1123에 정의된 규칙은 다음과 같다.

* 최대 63자를 포함할 수 있다. +
* 영어 소문자, 숫자, 특수문자(`-`)만 가능하다.
* 알파벳 문자로 시작해야 한다. (TD: RFC 1123의 경우 영어 소문자 또는 숫자로 시작해야 하는 것으로 파악됨. 확인 필요) +
* 영어 소문자, 숫자로 끝나야 한다.
====

. *호스트 이름 및 IP 주소 등록* +
`/etc/hosts` 파일을 열어 설정한 호스트 이름과 호스트의 IP 주소를 등록한다.
+
.예시
----
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

172.22.5.2 k8s-master
----

=== 스왑 메모리
`swapoff` 명령을 사용하여 스왑 메모리를 비활성화한다.(TD: 비활성화 하는 이유는?)
----
$ sudo swapoff -a
----
만약 스왑 메모리를 영구적으로 비활성화하려면 `/etc/fstab` 파일을 열어 아래의 행을 주석 처리한다.
----
# /dev/mapper/centos-swap swap                    swap    defaults        0
----

=== SELinux
`setenforce` 명령을 사용하여 SELinux를 비활성화한다.(TD: 비활성화 이유는?)
----
$ sudo setenforce 0
----
만약 SELinux를 영구적으로 비활성화하려면 아래의 명령을 실행한다.
----
$ sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
----

== 네트워크 구성

=== 포트
HyperCloud에서 사용되는 주요 포트 목록은 다음과 같다.
[width="100%",options="header", cols="1,1,2"]
|====================
|프로토콜|포트 번호|용도
|ICMP|-|Ping 테스트
|TCP|22|SSH
|TCP|80|HTTP
|TCP|179|Calico BIRD
|TCP|443|HTTPS
|TCP|2379-2380|SSH
|TCP|5000|Podman Registry
|TCP|6443|Kube API 서버
|TCP|7472|MetalLB speaker
|TCP|9000-9999|Calico, Node Exporter를 포함한 호스트 레벨 서비스
|TCP|10010|CRI-O
|TCP|10248|Kubelet
|TCP|10250-10259|Kubernetes가 기본적으로 사용하는 포트 (kubelet, kube-schduler, kube-controller-manager, kube-proxy) 
|UDP|53|DNS
|UDP|123|NTP
|UDP|4789|VXLAN
|UDP|6081|VXLAN
|UDP|9000-9999|Calico, Node Exporter를 포함한 호스트 레벨 서비스
|TCP/UDP|30000-32767|Kubernetes 노트 포트 범위
|====================

=== 도메인
HyperCloud에서 사용되는 주요 도메인 목록은 다음과 같다.
[width="100%",options="header", cols="1,1,1,2"]
|====================
|네임스페이스|호스트|기타|설명
|api-gateway-system|console.xx.xx|console.tmaxcloud.com|
|argocd|argocd.xx.xx|argocd.tmaxcloud.com/|
|awx|||
|cicd-system|||GitLab의 이벤트를 받는 웹훅 서비스로, Git으로부터 이벤트를 받아 CI/CD 파이프라인을 동작
|gitlab-system|||
|helm-ns|||
|hyperauth|||HyperCloud 계정 관리 UI
|hyperregistry|||HyperCloud 컨테이너 이미지 레지스트리
|istio-system|||
|kube-logging|||
|monitoring|||
|====================

=== CoreDNS
HyperCloud에서 DNS 서버 역할을 하는 CoreDNS 설정을 통해 사용할 도메인을 등록할 수 있다. +
내부에서 도메인 네임을 설정할 때 nodelocaldns config 설정 (예시 cm 추가) +
Namespace : kube-system, Configmap : coredns, nodelocaldns에서 확인


=== IP Pool
기본 IP Pool 외에 네임스페이스별 IP Pool을 분리할 수 있다.

. IP Pool 생성
+
.예시
----
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: prv-dls-dev-ippool <1>
spec:
  cidr: 10.128.128.0/24
  blockSize: 28
  ipipMode: Never   # AWS의 경우 Always
natOutgoing: true
----
<1> IP Pool의 이름
<2> (TD: 이외 필요한 항목의 내용 작성 필요)
. 네임스페이스 내의 모든 파드들이 IP Pool을 사용하도록 적용
+
.예시
----
apiVersion: v1
kind: Namespace
metadata:
  annotations: 
    cni.projectcalico.org/ipv4pools: '["prv-dls-dev-ippool"]' <1>
** Namespace는 .metadata.annotations 아래에 명시 (TD: 문장의 의미가 이해되지 않음)
----
<1> 네임스페이스에 적용할 IP Pool의 이름
