= 소프트웨어 설정
:toc:
:toc-title:

== CRI-O 설정
 여러 형식의 이미지를 확인하고 받아오는 다양한 방법 및 컨테이너 이미지를 관리하기 위해 설정한다. 
(TD: CRI-O 설정의 목적 및 이유 작성 필요. )(QA: 작성 완료)
(TD: crio.conf 파일과 registries.conf 파일 설정이 순차적으로 진행이 되어야 하는 건가요?)(QA: crio.conf 파일이 registries.conf 파일에서 스토리지 기본값을 읽어와서 registries.conf 먼저 하는게 맞기는 한데 결국 두 파일을 다 바꾼 뒤 crio를 restart 할때 설정값이 적용되기 때문에 상관없습니다.) 



. *crio.conf 파일 설정* +
`/etc/crio/crio.conf` 파일에서 cri-o 컨테이너 런타임에 대한 설정을 변경한다.(TD: 해당 설정을 통해 무엇을 설정하려는 건지 의도 작성 필요)(QA: 작성 완료)
+
.예시 (TD: xxx 말고 샘플 데이터 작성 필요. registries 및 pids_limit 항목에 대한 예시 값도 작성하는 것이 좋을 것 같습니다. QA: 변경 완료)
----
pause_image = "30.0.0.1:5000/k8s.gcr.io/pause:3.2"
insecure_registries = ["30.0.0.1:5000", "30.0.0.2:5000"]
plugin_dirs = [
        "/opt/cni/bin",
        "/usr/libexec/cni",
]
----
+
설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,2"]
|====================
|항목|설명
|pause_image|Pause 이미지가 포함된 이미지 경로를 설정한다.
|insecure_registries|인증서 등록을 하지 않고 Podman Registry에서 이미지를 가져올 경우 해당 주소를 설정한다.
|plugin_dirs|CNI 플러그인 바이너리 디렉터리 경로를 설정한다.
|registries|이미지를 가져올 경우 해당 레지스트리의 경로를 설정한다.
|pids_limit|컨테이너에서 허용되는 최대 프로세스의 수이다. (기본값: 1024) +
PID Cgroup의 최대 허용 프로세스 수 제한이 필요한 경우 설정한다. 단, 시스템의 제한 값인 /proc/sys/kernel/pid_max의 값 이하로 설정해야 한다.
|====================

. *registries.conf 파일 설정* +
`/etc/containers/registries.conf` 파일에서 컨테이너 이미지 레지스트리에 대한 설정을 변경한다.(TD: 해당 설정을 통해 무엇을 설정하려는 건지 의도 작성 필요)(QA: 변경 완료)
+
.예시 (TD: xxx 말고 샘플 데이터 작성 필요.)(QA: 변경 완료)
----
unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "registry.centos.org", "30.0.0.1:5000"]
----
+
설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,2"]
|====================
|항목|설명
|unqualified-search-registries|사용하는 Podman Registry를 설정한다. +
인증서 등록을 하지 않고 Podman Registry에서 이미지를 가져올 경우 해당 주소를 설정한다.
|====================


. *CRI-O 재실행* +
설정 내용을 적용하기 위해 CRI-O를 재실행한다.
+
----
$ systemctl restart crio
----
