= 로그 조회
:toc:
:toc-title:

== 쿠버네티스 로그 조회

컨테이너의 라이프사이클을 정의, 배포, 관리하기 위한 API와 인터페이스들을 노출하는 컨테이너 오케스트레이션 레이어인 kube-apiserver의 로그를 확인한다.
----
$ kubectl logs -f kube-apiserver-[마스터 노드 이름] -n kube-system
----

== 파드 로그 조회

=== CLI 환경

파드의 상태가 "CrashBackOff", "ImagePullBackOff", "ErrImagePull", "Pending"인 경우 명령어를 이용하여 발생 원인을 확인한다.

* 파드 상세 정보를 통한 상태 및 이벤트 정보 분석
+
----
$ kubectl describe -n [네임스페이스 이름] pod [파드 이름]
----

* 파드 배포 시 반복적인 오류가 발생될 경우 로그 분석
+
----
$ kubectl logs -n [네임스페이스 이름] -f [파드 이름] [-c 컨테이너 이름]
----

=== 콘솔 환경

HyperCloud 콘솔을 통해 애플리케이션의 로그를 확인한다.

. HyperCloud 콘솔에 로그인한다.

. *[워크로드] > [파드]* 메뉴를 선택한다.

. 파드 목록에서 로그를 확인할 파드의 이름을 클릭한다.

. 해당 파드의 상세 화면이 열리면 *[로그]* 탭을 선택한다.

== CI/CD 점검

CI/CD가 진행될 때 생성되는 파이프라인 런과 파이프라인 런을 통해 빌드된 파드들의 로그를 확인한다. 해당 파드 안에서 파이프라인을 통해 진행되는 깃 소스를 가져와서 빌드하고 배포하는 과정에 대한 로그를 확인할 수 있다. 생성한 파이프라인에 따라 확인할 수 있는 태스크의 목록이 다르기 때문에 각 과정마다의 로그 확인이 필요하다.

== 조치 사항

본 절에서는 파드의 상태 및 특정 상황에 대한 조치 방법에 대해서 설명한다.

=== 파드가 "CrashBackOff" 상태일 경우

"CrashBackOff" 상태는 컨테이너 배포 시 설정 등의 문제로 반복적인 재기동 후에 비정상 종료된 상태이다. 대부분 describe 정보나 logs 정보를 통해 원인 분석이 가능하다.

. *파드 삭제 후 상태 확인*
+
----
$ kubectl delete -n [네임스페이스 이름] [파드 이름] --grace-period=0 --force
----

. *오류가 반복될 경우 로그 분석*
+
----
$ kubectl logs -n [네임스페이스 이름] -f [파드 이름] [-c 컨테이너 이름]
----

. *파드 상세 정보를 통한 상태 및 이벤트 정보 분석*
+
----
$ kubectl describe -n [네임스페이스 이름] [파드 이름]
----

. *조치 진행*
+
분석된 원인에 대한 조치를 진행한다.

=== 파드가 "ImagePullBackOff" 및 "ErrImagePull" 상태일 경우

"ImagePullBackOff" 및 "ErrImagePull" 상태는 파드가 사용하는 도커 이미지를 레지스트리에서 풀링(pulling)할 수 없는 상태이다. 주로 이미지가 없거나 태그 정보를 잘못 기입할 경우 발생한다.

. *정상적인 풀링(pulling)이 가능한지 확인*
+
----
$ docker pull [이미지 주소]
----

. *사용 레지스트리가 도커의 insecure-registries 정보에 등록 여부 확인*
+
----
$ cat /etc/docker/daemon.json | grep insecure-registries
----

. *레지스트리에 해당 이미지 존재 여부 확인*
+
----
$ curl [레지스터리 주소]:[포트]/v2/_catalog | grep [이미지 이름]
----

. *해당 이미지 버전의 존재 여부 확인*
+
----
$ curl [레지스터리 주소]:[포트]/v2/[이미지 이름]/tags/list | grep [버전 정보]
----

. *조치 진행*
+
태그 이름이 잘못된 경우 태그 이름을 수정하고, 이미지가 없는 경우에는 이미지를 푸시(push)한다.

=== 파드가 "Pending" 상태일 경우

"Pending" 상태는 노드에 파드가 배포될 수 없을 때 발생한다. describe 명령을 통해 원인 분석이 가능하다.

. *파드의 상세 정보(State, Events 정보) 확인*
+
----
$ kubectl describe -n [네임스페이스 이름] [파드 이름]
----

. *조치 진행*
+
자원이 부족한 경우 yaml의 resources.requests 정보를 수정하여 적용하고, 컨테이너 이미지가 오류인 경우 이미지 재배포한다.

=== 네임스페이스가 삭제되지 않을 경우

특정 자원에 의해 참조가 되는 경우 네임스페이스가 삭제되지 않는 경우가 발생한다. 만약 강제로 네임스페이스를 삭제하려면 다음의 절차를 진행한다.
----
$ kubectl proxy &
kubectl get ns [네임스페이스 이름] -o json > delete-ns.json
sed -i 's/"kubernetes"//g' delete-ns.json
curl -k -H "Content-Type: application/json" -X PUT --data-binary @delete-ns.json http://127.0.0.1:8001/api/v1/namespaces/[네임스페이스 이름]/finalize
----
