= Creating Limit Ranges
:toc:
:toc-title:

The following describes how to create limit range resources.

== YAML Editor

Create a new limit range by using the YAML editor.

. Click *[Create Limit Ranges]* in the <<../console_menu_sub/management#img-basic-resource-main,Limit Ranges>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a limit range to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: LimitRange
metadata:
  name: example <1>
  namespace: default <2>
spec:
  limits:
    - default: <3>
        memory: 512Mi
      defaultRequest: <4>
        memory: 256Mi
      type: Container <5>
----
+
<1> Limit range name
<2> Name of a namespace where the limit range is created
<3> Limit of a default resource quota
<4> Request of a default resource quota
<5> Resource type to apply
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new limit range by using the Form editor.

. Click *[Create Limit Ranges]* in the <<../console_menu_sub/management#img-basic-resource-main,Limit Ranges>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Limit Range* screen opened, enter configuration data about a limit range to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description 
|Name*|Limit range name.
|Namespace*|Name of a namespace where the limit range is created.
|Labels|Labels to add to the limit range
|RESOURCELIMITSRANGE|Resource quota by resource type (such as a pod, container, and persistent volume claim) of a pod to create in a namespace. +
Select a checkbox for a resource type to set limit range, and then click **[+ Add More]** to set its limit type and value. Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|====================
. To create the resource with the data you entered, click *[Create]*.