= 클러스터 템플릿 클레임 생성
:toc:
:toc-title:

본 장에서는 클러스터 템플릿 클레임 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 클러스터 템플릿 클레임을 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 카탈로그]* -> *[클러스터 템플릿 클레임]* 메뉴를 선택한다.
. *클러스터 템플릿 클레임* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 클러스터 템플릿 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[클러스터 템플릿 클레임 생성]* 버튼을 클릭한다.
. *Create ClusterTemplateClaim* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 클러스터 템플릿 클레임의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* resourceName *
* template *
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 클러스터 템플릿 클레임을 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 카탈로그]* -> *[클러스터 템플릿 클레임]* 메뉴를 선택한다.
. *클러스터 템플릿 클레임* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 클러스터 템플릿 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[클러스터 템플릿 클레임 생성]* 버튼을 클릭한다.
. *Create CatalogServiceClaim* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 클러스터 템플릿 클레임의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: tmax.io/v1
kind: ClusterTemplateClaim
metadata:
  name: example22 <1>
  namespace: default <2>
spec:
  resourceName: mysql-template-resourcename2 <3>
  template: mysql-template <4>
----
+
<1> 클러스터 템플릿 클레임의 이름
<2> 클러스터 템플릿 클레임이 생성될 네임스페이스의 이름
<3> 클러스터 템플릿 클레임이 허가되면 생성될 클러스터 템플릿의 이름
<4> 생성될 클러스터 템플릿의 정보가 정의된 템플릿의 이름
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.