= 클러스터 업데이트 클레임 생성
:toc:
:toc-title:

본 장에서는 클러스터 업데이트 클레임 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 클러스터 업데이트 클레임을 폼 에디터를 사용해서 생성할 수 있다.

. "멀티 클러스터" 콘솔 메뉴에서 *[클러스터]* 메뉴를 선택한다.
. *클러스터* 메인 화면이 열리면 *[클러스터 업데이트 클레임]* 탭을 선택한다.
. *[클러스터 업데이트 클레임]* 탭 화면이 열리면 네임스페이스 선택 영역에서 새로운 클러스터 업데이트 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[클러스터 업데이트 클레임 생성]* 버튼을 클릭한다.
. *클러스터 업데이트 클레임 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 클러스터 업데이트 클레임의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* clusterName *
* updatemasterNum
* updateworkerNum
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 클러스터 클레임을 YAML 에디터를 사용해서 생성할 수 있다.

. "멀티 클러스터" 콘솔 메뉴에서 *[클러스터]* 메뉴를 선택한다.
. *클러스터* 메인 화면이 열리면 *[클러스터 업데이트 클레임]* 탭을 선택한다.
. *[클러스터 업데이트 클레임]* 탭 화면이 열리면 네임스페이스 선택 영역에서 새로운 클러스터 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[클러스터 업데이트 클레임 생성]* 버튼을 클릭한다.
. *클러스터 업데이트 클레임 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 클러스터 업데이트 클레임의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: claim.tmax.io/v1alpha1
kind: ClusterUpdateClaim
metadata:
  name: exam <1>
  namespace: example <2>
spec:
  clusterName: exam01 <3>
  updatedMasterNum: 3 <4>
  updatedWorkerNum: 3 <5>
----
+  
<1> 클러스터 업데이트 클레임의 이름
<2> 클러스터 업데이트 클레임이 생성될 네임스페이스의 이름
<3> 클러스터 업데이트 클레임을 반영할 클러스터의 이름 (단, Cluster Claim으로 생성된 클러스터의 이름을 입력한다. )
<4> 변경할 마스터 노드의 수
<5> 변경할 작업자 노드의 수

. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
