= 클러스터 클레임 생성 (TD: 전체 검수 필요)
:toc:
:toc-title:

본 장에서는 클러스터 클레임 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 클러스터 클레임을 폼 에디터를 사용해서 생성할 수 있다.

. "멀티 클러스터" 콘솔 메뉴에서 *[클러스터]* 메뉴를 선택한다.
. *클러스터* 메인 화면이 열리면 *[클러스터 클레임]* 탭을 선택한다.
. *[클러스터 클레임]* 탭 화면이 열리면 네임스페이스 선택 영역에서 새로운 클러스터 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[클러스터 클레임 생성]* 버튼을 클릭한다.
. *클러스터 클레임 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 클러스터 클레임의 구성 정보를 작성한다. (TD: 기본 작성 예 및 항목 설명 작성 필요)
+
. 기본 작성 예(QA: provider vsphere/aws 로 나누어 설명 작성하였습니다)
+
.. *provider vsphere*
       
  [source,yaml]
  ----
apiVersion: claim.tmax.io/v1alpha1
kind: ClusterClaim
metadata:
  name: example <1>
  namespace: default <2>
spec:
  clusterName: example <3>
  masterNum: 1 <4>
  provider: vSphere <5>
  providerVsphereSpec: <6>
    podCidr: 10.0.0.0/16 <7>
    vcenterCpuNum: 3 <8>
    vcenterDataCenter: Datacenter1 <9>
    vcenterDataStore: datastore1 <10>
    vcenterDiskSize: 25 <11>
    vcenterFolder: vm <12>
    vcenterId: administrator@vsphere.local <13>
    vcenterIp: 192.168.10.10 <14>
    vcenterKcpIp: 192.168.10.20 <15>
    vcenterMemSize: 8192 <16>
    vcenterNetwork: VM Network <17>
    vcenterPassword: Password! <18>
    vcenterResourcePool: 192.168.10.11/Resources <19>
    vcenterTemplate: ubuntu-1804-kube-v1.19.6 <20>
    vcenterThumbprint: 'A1:B2:C3:DD:E5:G6:FF:AA:AB:35:AF:17:D7:7A:38:88:55:74:A3:C2' <21>
  version: v1.19.6 <22>
  workerNum: 1 <23>
  ----
<1> 클러스터 클레임의 이름
<2> 클러스터 클레임이 생성될 네임스페이스의 이름
<3> 생성할 클러스터의 이름
<4> 마스터 노드 수
<5> VM이 생성된 클라우드 제공 업체의 이름
<6> 공급자 vSphere 사양
<7> 포드용 내부 IP 주소 CIDR 블록
<8> VM의 CPU 수
<9> 데이터 센터 이름
<10> 데이터 저장소의 이름
<11> vm의 디스크 크기. 단위 없이 GB로 작성. 예: 25
<12> 폴더 이름
<13> VCSA의 사용자 ID
<14> vCenter Server 애플리케이션(VCSA)의 IP 주소
<15> 원격 클러스터(vip)용 컨트롤플레인의 IP 주소
<16> vm의 메모리 크기. 단위 없이 MB로 작성. 예: 8192
<17> 네트워크 이름
<18> VCSA의 비밀번호
<19> 리소스 풀의 이름
<20> 클라우드 초기화의 템플릿 이름
<21> 컴퓨터 인증서의 TLS 지문
<22> Kubernetes 버전
<23> 작업자 노드 수
+
.. *provider aws*
       
  [source,yaml]
  ----
apiVersion: claim.tmax.io/v1alpha1
kind: ClusterClaim
metadata:
  name: example <1>
  namespace: default <2>
spec:
  clusterName: example <3>
  masterNum: 1 <4>
  provider: AWS <5>
  providerAwsSpec: <6>
    masterType: m4.xlarge <7>
    region: ap-northeast-2 <8>
    sshKey: sshkey <9>
    workerType: m4.xlarge <10>
  version: v1.21.11 <11>
  workerNum: 1 <12>
  ----
<1> 클러스터 클레임의 이름
<2> 클러스터 클레임이 생성될 네임스페이스의 이름
<3> 생성할 클러스터의 이름
<4> 마스터 노드 수
<5> VM이 생성된 클라우드 제공 업체의 이름
<6> 공급자 AWS 사양
<7> 마스터 노드의 VM 유형. 예: m4.xlarge.
<8> VM이 작동하는 지역
<9> VM에 액세스하기 위한 ssh 키 정보
<10> 워커 노드의 VM 유형. 예: m4.xlarge.
<11> Kubernetes 버전
<12> 작업자 노드 수
+
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
