= 클러스터 서비스 브로커 생성
:toc:
:toc-title:

본 장에서는 클러스터 서비스 브로커 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 클러스터 서비스 브로커를 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/service-catalog#img-cluster-service-broker-main,클러스터 서비스 브로커 메인 화면>>의 네임스페이스 선택 영역에서 새로운 클러스터 서비스 브로커를 생성할 네임스페이스를 선택한 후 *[클러스터 서비스 브로커 생성]* 버튼을 클릭한다.
. *Create Cluster Service Broker* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 클러스터 서비스 브로커의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다. (* : 필수 입력 항목)

* Name *
+
클러스터 서비스 브로커의 이름을 입력한다.
* Labels
+
클러스터 서비스 브로커에 추가할 레이블 정보를 입력한다.
* Auth Info
+
하위 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|Basic|
* Secret Ref : 
** name :
** namespace :
|Bearer|
* Secret Ref : 
** name :
** namespace :
|====================
* caBundle
* Catalog Restrictions
+
하위 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|Service Class|
* Value * :
|Service Plan|
* Value * :
|====================
* insecureSkipTLSVerify
* relistBehavior
* relistDuration
* relistRequests
* url *
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 클러스터 서비스 브로커를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/service-catalog#img-cluster-service-broker-main,클러스터 서비스 브로커 메인 화면>>의 네임스페이스 선택 영역에서 새로운 클러스터 서비스 브로커를 생성할 네임스페이스를 선택한 후 *[클러스터 서비스 브로커 생성]* 버튼을 클릭한다.
. *Create Cluster Service Broker* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 클러스터 서비스 브로커의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: hyperbroker5 <1>
spec:
  url: http://192.168.6.159:2867 <2>
----
+
<1> 클러스터 서비스 브로커의 이름
<2> 서비스 브로커 서버의 서비스 URL

. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
