= Creating Config Maps
:toc:
:toc-title:

The following describes how to create config map resources.

== YAML Editor

Create a new config map by using the YAML editor.

. Click *[Create Config Maps]* in the <<../console_menu_sub/work-load#img-config-map-main,Config Maps>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a config map to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap <1>
  namespace: default <2>
data: <3>
  (key): (value)
  id: tmax-admin
  password: admin-pw
----
+
<1> Config map name
<2> Name of a namespace where the config map is created
<3> Data to define in the config map (Key-value format)

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new config map by using the Form editor.

. Click *[Create Config Maps]* in the <<../console_menu_sub/work-load#img-config-map-main,Config Maps>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Config Maps* screen opened, enter configuration data about a config map to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name*|Config map name.
|Namespace*|Name of a namespace where the config map is created.
|Config Map Value|Data to define in the config map (Key-value format) +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Key: Data item
* Value: Item value
|====================

. To create the resource with the data you entered, click *[Create]*.