= 크론 잡 생성
:toc:
:toc-title:

본 장에서는 크론 잡 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 크론 잡을 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[크론 잡]* 메뉴를 선택한다.
. *크론 잡* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 크론 잡을 생성할 특정 네임스페이스를 선택한다.
. *[크론 잡 생성]* 버튼을 클릭한다.
. *크론 잡 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 크론 잡의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* concurrencyPolicy
* failedJobsHistoryLimit
* Job Template * +
하위 세부 항목은 xref:../form-set-item.adoc#JobTemplate["폼 에디터 설정 항목 참조"의 "Job Template"]을 참고한다.
* schedule *
* startingDeadlineSeconds
* successfulJobsHistoryLimit
* suspend
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 크론 잡을 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[크론 잡]* 메뉴를 선택한다.
. *크론 잡* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 크론 잡을 생성할 특정 네임스페이스를 선택한다.
. *[크론 잡 생성]* 버튼을 클릭한다.
. *크론 잡 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 크론 잡의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello <1>
  namespace: default <2>
spec:
  schedule: "*/1 * * * *" <3>
  jobTemplate: <4>
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            resources: <5>
              limits: <6>
                memory: 200Mi
                cpu: 1
              requests: <7>
                memory: 100Mi
                cpu: 0.5                      
            command: ["/bin/sh", "-c", "date"]
          restartPolicy: OnFailure
----
+
<1> 크론 잡의 이름
<2> 크론 잡이 생성될 네임스페이스의 이름
<3> 잡이 실행될 주기(크론 문법으로 작성) *(필수 설정)*
<4> 주기적으로 실행될 잡의 상세 내역
<5> 컨테이너에 할당할 리소스의 종류 및 양 +
다음과 같은 조건에서 크론 잡을 생성할 경우 반드시 설정 필요 +
* 네임스페이스 클레임을 통해 생성된 네임스페이스
* 리소스 쿼타가 설정된 네임스페이스 +
<6> 컨테이너가 최대로 사용할 수 있는 리소스의 양
<7> 컨테이너가 생성될 때 요청할 리소스의 양
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.