= Creating Data Volumes
:toc:
:toc-title:

The following describes how to create data volume resources.

== YAML Editor

Create a new data volume by using the YAML editor.

. Click *[Create Data Volumes]* in the <<../console_menu_sub/storage#img-data-volume-main,Data Volumes>> main screen.
. Enter configuration data about a data volume to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: my-data-volume <1>
  # namespace: default <2>
spec:
  source:
    http: <3>
      url: "https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.img" <4>
      # secretRef: "" <5>
      # certConfigMap: "" <6>
    # contentType: "archive" <7>
    
  pvc:
    accessModes: <8>
      - ReadWriteOnce 
    resources:
      requests:
        storage: 5Gi <9>
    # storageClassName: local <10>
    # volumeMode: Block <11>
----
+
<1> Data volume name
<2> Name of a namespace where the data volume is created (Default value: default)
<3> Type of an external path to get a virtual machine image to
* http
* s3
* registry
<4> Actual path to get a virtual machine image to
<5> K8s Secret resource used when authentication is required to access the url
<6> K8s ConfigMap resource used when TLS certificate is required to access the url
<7> Type of virtual machine image source (Default value: kubevirt)
* kubevirt: When the image source is virtual disk image.
* archive: When an external path type is http and virtual machine image source is a tar file.
<8> Access mode of a persistent volume claim to use when creating a virtual machine +
If a block storage class is sued, ReadWriteMany can be set only when the volume usage mode is set to Block.
* ReadWriteOnce: One node mounts a volume in read-write mode.
* ReadOnlyMany: Multiple nodes mount a volume in read-only mode.
* ReadWriteMany: Multiple nodes mount a volume in read-write mode.
<9> Size of a persistent volume claim to use when creating a virtual machine
<10> Storage class name of a persistent volume claim to use when creating a virtual machine
<11> Volume usage mode (Default value: Filesystem)
* Filesystem
* Block

. To create the resource with the data you entered, click *[Create]*.