= 디플로이먼트 생성
:toc:
:toc-title:

본 장에서는 디플로이먼트 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 디플로이먼트를 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[디플로이먼트]* 메뉴를 선택한다.
. *디플로이먼트* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 디플로이먼트를 생성할 특정 네임스페이스를 선택한다.
. *[디플로이먼트 생성]* 버튼을 클릭한다.
. *Create Deployment* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 디플로이먼트의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* minReadySeconds
* paused
* progressDeadlineSeconds
* replicas
* revisionHistoryLimit
* Selector * +
하위 세부 항목은 xref:../form-set-item.adoc#Selector["폼 에디터 설정 항목 참조"의 "Selector"]를 참고한다.
* Strategy +
하위 세부 항목은 xref:../form-set-item.adoc#Strategy["폼 에디터 설정 항목 참조"의 "Strategy"]를 참고한다.
* Template * +
하위 세부 항목은 xref:../form-set-item.adoc#Template["폼 에디터 설정 항목 참조"의 "Template"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 디플로이먼트를 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[디플로이먼트]* 메뉴를 선택한다.
. *디플로이먼트* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 디플로이먼트를 생성할 특정 네임스페이스를 선택한다.
. *[디플로이먼트 생성]* 버튼을 클릭한다.
. *Create Deployment* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 디플로이먼트의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example <1>
  namespace: default <2>
spec:
  selector: 
    matchLabels: <3>
      app: hello-hypercloud
    replicas: 3 <4>
    template: <5>
      metadata: 
        labels: <6>
          app: hello-hypercloud
      spec: 
      containers: <7>
        - name: hello-hypercloud <8>
          image: hypercloud/hello-hypercloud <9>
          ports: <10>
            - containerPort: 8080 <11>
----
+
<1> 디플로이먼트의 이름
<2> 디플로이먼트가 생성될 네임스페이스의 이름
<3> 디플로이먼트가 관리할 파드의 레이블 정보
<4> 파드 복제본의 개수
<5> 생성할 파드에 대한 상세 명세
<6> 파드를 분류할 때 사용할 레이블 정보 (키-값 형식)
<7> 파드를 구성할 컨테이너의 상세 내역
<8> 컨테이너의 이름
<9> 컨테이너의 이미지
<10> 컨테이너에서 노출할 포트 목록
<11> 파드의 IP 주소에서 노출할 포트 번호
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.