= Creating Deployments
:toc:
:toc-title:

The following describes how to create deployment resources.

== YAML Editor

Create a new deployment by using the YAML editor.

. Click *[Create Deployments]* in the <<../console_menu_sub/work-load#img-deployment-main,Deployments>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a deployment to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example <1>
  namespace: default <2>
spec:
  selector: 
    matchLabels: <3>
      app: hello-hypercloud
    replicas: 3 <4>
    template: <5>
      metadata: 
        labels: <6>
          app: hello-hypercloud
      spec: 
      containers: <7>
        - name: hello-hypercloud <8>
          image: hypercloud/hello-hypercloud <9>
          ports: <10>
            - containerPort: 8080 <11>
----
+
<1> Deployment name
<2> Name of a namespace where the deployment is created
<3> Label of a pod to be managed by the deployment
<4> Number of pod replicas
<5> Information about a pod to create
<6> Information about labels to use when classifying pods (Key-value format)
<7> Information about containers included in a pod
<8> Container name
<9> Container image
<10> Ports to expose to the container
<11> Port number to expose on the pod's IP address

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new deployment by using the Form editor.

. Click *[Create Deployments]* in the <<../console_menu_sub/work-load#img-deployment-main,Deployments>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Deployments* screen opened, enter configuration data about a deployment to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description   
|Name|Deployment name.
|Container Image|Container image name for running an application.
|Image pull policy|Image pull policy to use for containers.

* If Not Present: Pull images only when the image does not exist in local.
* Always: Pull images whenever the container starts.
* Never: Do not pull images.
|Replicas|Number of pod replicas.
|Labels|Information about labels to add to the deployment.
|Run command|Command to run when a container runs in a pod (Command field). +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|Run command arguments|Command arguments (Args field). +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|Environment variables|Environment variables for the deployment. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Key: Environment variable name.
* Value: Default value of the environment variable.
|Port|Ports to expose to the container. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Port Name: Port name.
* Port: Port number.
* Protocol: One of the following network protocols: TCP, UDP, and SCDP.
|Volumes|Volumes to add to a pod. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Volume Name: Volume name.
* Mount Path: Path of the volume to mount.
* Persistent Volume Claim: Persistent volume claim name.
* Read Only: Read/write mode.
|Resource(Request)|Minimum resources required to schedule a pod. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Resource: Resource type.
* Quantity: Minimum quantity.
|Resource(Limits)|Maximum resources allowed when creating and running pod's container. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Resource: Resource type.
* Quantity: Maximum quantity.
|Restart Policy|Restart policy for a terminated container.

* Always: Always restart it.
* OnFailure: Restarts it only when it is terminated abnormally.
* Never: Do not restart it.
|====================

. To create the resource with the data you entered, click *[Create]*.

NOTE: The following are rules for commands (Command field) and command arguments (Args field). +
- If both command (Command field) and command arguments (Args field) are defined, the Entrypoint field value defined in an image is overwritten by the command (Command field) value and the Cmd field value is overwritten by the command argument (Args field) value. +
- If only command (Command field) is defined, the Entrypoint field value defined in an image is overwritten by the command (Command field) value and the Cmd field value is overwritten as undefined. + 
- If only command argument (Args field) is defined, only image's Cmd field value is overwritten.