= 목적지 규칙 생성
:toc:
:toc-title:

본 장에서는 목적지 규칙 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 목적지 규칙을 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[목적지 규칙]* 메뉴를 선택한다.
. *목적지 규칙* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 목적지 규칙을 생성할 특정 네임스페이스를 선택한다.
. *[목적지 규칙 생성]* 버튼을 클릭한다.
. *목적지 규칙 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 목적지 규칙의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Export To
+
----
Value *
----
* host
* Subsets
* Traffic Policy
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 목적지 규칙을 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[목적지 규칙]* 메뉴를 선택한다.
. *목적지 규칙* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 목적지 규칙을 생성할 특정 네임스페이스를 선택한다.
. *[목적지 규칙 생성]* 버튼을 클릭한다.
. *목적지 규칙 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 목적지 규칙의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details <1>
  namespace: bookinfo
spec:
  host: details <2>
  subsets:
    - labels: <3>
        version: v1
      name: v1 <4>
    - labels:
        version: v2
      name: v2
----
+
<1> 목적지 규칙의 이름
<2> 트래픽 정책이 적용되는 대상
<3> metadata에서 다른 버전을 식별하기 위해 사용할 레이블 정보 (키-값 형식)
<4> 트래픽 정책이 적용되는 대상의 하위 정책 이름
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
