= 엔보이 필터 생성
:toc:
:toc-title:

본 장에서는 엔보이 필터 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 엔보이 필터를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[엔보이 필터]* 메뉴를 선택한다.
. *엔보이 필터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 엔보이 필터를 생성할 특정 네임스페이스를 선택한다.
. *[엔보이 필터 생성]* 버튼을 클릭한다.
. *엔보이 필터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 엔보이 필터의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Config Patches
* Filters
* workloadLabels
* Workload Selector
+
----
labels
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 엔보이 필터를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[엔보이 필터]* 메뉴를 선택한다.
. *엔보이 필터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 엔보이 필터를 생성할 특정 네임스페이스를 선택한다.
. *[엔보이 필터 생성]* 버튼을 클릭한다.
. *엔보이 필터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 엔보이 필터의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metadata-exchange-1.4 <1>
  namespace: istio-system <2>
spec:
  configPatches:
    - applyTo: HTTP_FILTER <3>
      match:
        context: ANY
        listener:
          filterChain: <4>
            filter:
              name: envoy.http_connection_manager
        proxy:
          proxyVersion: ^1\.4.*
      patch: <5>
        operation: INSERT_BEFORE
        value:
          config:
            config:
              configuration: envoy.wasm.metadata_exchange
              vm_config:
                code:
                  inline_string: envoy.wasm.metadata_exchange
                runtime: envoy.wasm.runtime.null
          name: envoy.filters.http.wasm
----
+
<1> 엔보이 필터의 이름
<2> 엔보이 필터가 생성될 네임스페이스의 이름
<3> patch를 적용할 위치
<4> patch를 적용할 조건
<5> 적용할 patch의 상세 내용
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
