= 게이트웨이 생성
:toc:
:toc-title:

본 장에서는 게이트웨이 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 게이트웨이를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[게이트웨이]* 메뉴를 선택한다.
. *게이트웨이* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 게이트웨이를 생성할 특정 네임스페이스를 선택한다.
. *[게이트웨이 생성]* 버튼을 클릭한다.
. *게이트웨이 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 게이트웨이의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* selector
* Servers +
하위 세부 항목은 xref:../form-set-item.adoc#Servers["폼 에디터 설정 항목 참조"의 "Servers"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 게이트웨이를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[게이트웨이]* 메뉴를 선택한다.
. *게이트웨이* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 게이트웨이를 생성할 특정 네임스페이스를 선택한다.
. *[게이트웨이 생성]* 버튼을 클릭한다.
. *게이트웨이 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 게이트웨이의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway <1>
  namespace: bookinfo
spec:
  selector: <2>
    istio: ingressgateway 
  servers:
    - hosts: <3>
        - '*' 
      port: <4>
        name: http
        number: 80
        protocol: HTTP
----
+
<1> 게이트웨이의 이름
<2> 게이트웨이를 구성하는 특정 파드 또는 VM 집합의 레이블 정보
<3> 게이트웨이에 의해 노출되는 대상
<4> 프록시에서 들어오는 연결을 수신할 포트 정보
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.