= HPA 생성
:toc:
:toc-title:

본 장에서는 HPA 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 HPA를 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[HPA]* 메뉴를 선택한다.
. *HPAs* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 HPA를 생성할 특정 네임스페이스를 선택한다.
. *[HPA 생성]* 버튼을 클릭한다.
. *HPA 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 HPA의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Behavior
* maxReplicas *
* Metrics
* minReplicas
* Scale Target Ref *
+
----
apiVersion
kind *
name *
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 HPA를 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[HPA]* 메뉴를 선택한다.
. *HPAs* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 HPA를 생성할 특정 네임스페이스를 선택한다.
. *[HPA 생성]* 버튼을 클릭한다.
. *HPA 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 HPA의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: example <1>
  namespace: default <2>
spec: 
  scaleTargetRef: <3>
    apiVersion: apps/v1 <4>
    kind: Deployment <5>
    name: example <6>
  minReplicas: 1 <7>
  maxReplicas: 3 <8>
  metrics: <9>
    - type: Resource <10>
      resource:
        name: cpu <11>
        targetAverageUtilization: 50 <12>
----
+
<1> HPA의 이름
<2> HPA가 생성될 네임스페이스의 이름
<3> 오토스케일링할 대상의 상세 내역
<4> 오토스케일링할 대상의 API 버전
<5> 오토스케일링할 대상의 종류
<6> 오토스케일링할 대상의 이름
<7> 최소로 줄어들 파드 복제본의 개수
<8> 최대로 늘어날 파드 복제본의 개수
<9> 오토스케일링에 활용할 메트릭의 상세 내역
<10> 메트릭의 유형
<11> 리소스의 이름
<12> 대상 파드의 리소스 메트릭 평균의 목표값
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
