= 인그레스 생성
:toc:
:toc-title:

본 장에서는 인그레스 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 인그레스를 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[네트워크]* -> *[인그레스]* 메뉴를 선택한다.
. *인그레스* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 인그레스를 생성할 특정 네임스페이스를 선택한다.
. *[인그레스 생성]* 버튼을 클릭한다.
. *인그레스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 인그레스의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Backend
* ingressClassName
* Rules
+
----
host
▼ Http
│  ▼ Paths *
│  │  ▼ Backend *
│  │  │  ▼ Resource
│  │  │  │  apiGroup
│  │  │  │  kind *
│  │  │  │  name *
│  │  │  serviceName
│  │  │  servicePort
│  │  path
│  │  pathType
----
* Tls
+
----
▼ Hosts
│  Value
secretName
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 인그레스를 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[네트워크]* -> *[인그레스]* 메뉴를 선택한다.
. *인그레스* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 인그레스를 생성할 특정 네임스페이스를 선택한다.
. *[인그레스 생성]* 버튼을 클릭한다.
. *인그레스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 인그레스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress <1>
  namespace: default <2>
spec: 
  backend: <3>
    serviceName: service1 <4>
    servicePort: 80 <5>
  tls: <6>
  - hosts: <7>
    - sslexample.foo.com
    - sslexample.woo.com
    secretName: testsecret-tls <8>
  rules: <9>
  - host: sslexample.foo.com <10>
    http: <11>
      paths: <12>
      - path: /test <13>
        backend: <14>
          serviceName: service1 <15>
          servicePort: 80 <16>
----
+
<1> 인그레스의 이름
<2> 인그레스가 생성될 네임스페이스의 이름
<3> 모든 트래픽을 전송할 단일 기본 백엔드 관련 설정
<4> 트래픽을 처리할 서비스 이름
<5> 트래픽을 처리할 서비스 포트
<6> TLS 관련 설정
<7> TLS 인증서에 포함된 호스트 목록
<8> TLS에 사용할 시크릿 이름 +
이때 시크릿에는 TLS에 사용할 인증서와 개인 키가 있어야 함
<9> 호스트 규칙 목록
<10> 사용할 전체 주소 도메인 이름 (FQDN)
<11> 백엔드를 가리키는 http 선택기 목록
<12> 요청을 백엔드에 매핑하는 경로 모음
<13> 설정할 경로 +
이때 해당 경로와 일치하는 경우 요청이 백엔드로 전달됨
<14> 트래픽을 전송할 백엔드 관련 설정
<15> 트래픽을 처리할 서비스 이름
<16> 트래픽을 처리할 서비스 포트
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
