= Creating Ingresses
:toc:
:toc-title:

The following describes how to create ingress resources.

== YAML Editor

Create a new ingress by using the YAML editor.

. Click *[Create Ingresses]* in the <<../console_menu_sub/network#img-ingress-main,Ingresses>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about an ingress to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress <1>
  namespace: default <2>
spec: 
  backend: <3>
    serviceName: service1 <4>
    servicePort: 80 <5>
  tls: <6>
  - hosts: <7>
    - sslexample.foo.com
    - sslexample.woo.com
    secretName: testsecret-tls <8>
  rules: <9>
  - host: sslexample.foo.com <10>
    http: <11>
      paths: <12>
      - path: /test <13>
        backend: <14>
          serviceName: service1 <15>
          servicePort: 80 <16>
----
+
<1> Ingress name
<2> Name of a namespace where the ingress is created
<3> Information about a single default backend to send all traffic to
<4> Name of a service that handles traffic
<5> Port of a service that handles traffic
<6> TLS information
<7> Hosts included in TLS certificates
<8> Name of a secret used for TLS +
The secret must have a certificate and private key used for TLS
<9> Host rules
<10> Fully qualified domain name (FQDN) to use
<11> http selectors that point to the backend
<12> Paths that map requests to the backend
<13> Path to set +
If this path matches, requests are sent to the backend.
<14> Information about the backend to send traffic to
<15> Name of a service that handles traffic
<16> Port of a service that handles traffic

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new ingress by using the Form editor.

. Click *[Create Ingresses]* in the <<../console_menu_sub/network#img-ingress-main,Ingresses>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Ingresses* screen opened, enter configuration data about an ingress to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name|Ingress name.
|Host|Ingress host information. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Hostname: Fully qualified domain name (FQDN).
* Path: Path to map to a backend
* Service Name: Name of a service that handles traffic
* Service Port: Port of a service that handles traffic
|====================

. To create the resource with the data you entered, click *[Create]*.