= 인그레스 생성
:toc:
:toc-title:

본 장에서는 인그레스 리소스의 생성 방법에 대해서 설명한다.

== YAML 에디터

새로운 인그레스를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/network#img-ingress-main,인그레스 메인 화면>>에서 *[인그레스 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[Yaml 에디터]**를 클릭한다.
. YAML 에디터 화면이 열리면 생성할 인그레스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress <1>
  namespace: default <2>
spec: 
  backend: <3>
    serviceName: service1 <4>
    servicePort: 80 <5>
  tls: <6>
  - hosts: <7>
    - sslexample.foo.com
    - sslexample.woo.com
    secretName: testsecret-tls <8>
  rules: <9>
  - host: sslexample.foo.com <10>
    http: <11>
      paths: <12>
      - path: /test <13>
        backend: <14>
          serviceName: service1 <15>
          servicePort: 80 <16>
----
+
<1> 인그레스의 이름
<2> 인그레스가 생성될 네임스페이스의 이름
<3> 모든 트래픽을 전송할 단일 기본 백엔드 관련 설정
<4> 트래픽을 처리할 서비스 이름
<5> 트래픽을 처리할 서비스 포트
<6> TLS 관련 설정
<7> TLS 인증서에 포함된 호스트 목록
<8> TLS에 사용할 시크릿 이름 +
이때 시크릿에는 TLS에 사용할 인증서와 개인 키가 있어야 함
<9> 호스트 규칙 목록
<10> 사용할 전체 주소 도메인 이름 (FQDN)
<11> 백엔드를 가리키는 http 선택기 목록칙 목록
<10> 사용할 전체 주소 도메인 이름 (FQDN)
<11> 백엔드를 가리키는 http 선택기 목록
<12> 요청을 백엔드에 매핑하는 경로 모음
<12> 요청을 백엔드에 매핑하는 경로 모음
<13> 설정할 경로 +
이때 해당 경로와 일치하는 경우 요청이 백엔드로 전달됨
<14> 트래픽을 전송할 백엔드 관련 설정
<15> 트래픽을 처리할 서비스 이름
<16> 트래픽을 처리할 서비스 포트
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

== 폼 에디터

새로운 인그레스를 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/network#img-ingress-main,인그레스 메인 화면>>에서 *[인그레스 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[폼 에디터]**를 클릭한다.
. *인그레스 생성* 화면이 열리면 생성할 인그레스의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명  
|이름|인그레스의 이름을 입력한다.
|호스트|인그레스의 호스트 정보를 입력한다. 이때 *[+ 추가]* 버튼을 클릭하면 입력 항목이 하나씩 추가되고, *[-]* 버튼을 클릭하면 입력 항목을 삭제할 수 있다.

* 호스트 이름 : 사용할 전체 주소 도메인 이름 (FQDN)
* 경로 : 백엔드에 매핑할 경로
* 서비스 이름 : 트래픽을 처리할 서비스 이름
* 서비스 포트 : 트래픽을 처리할 서비스 포트
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.