= 인테그레이션 컨피그 생성
:toc:
:toc-title:

본 장에서는 인테그레이션 컨피그 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 인테그레이션 컨피그를 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/ci-cd#img-integration-config-main,인테그레이션 컨피그 메인 화면>>의 네임스페이스 선택 영역에서 새로운 인테그레이션 컨피그를 생성할 네임스페이스를 선택한 후 *[인테그레이션 컨피그 생성]* 버튼을 클릭한다.
. *Create Integration Config* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 인테그레이션 컨피그의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Git * +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Git>["폼 에디터 설정 항목 참조"의 "Git"]을 참고한다.
* Jobs * +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Jobs>["폼 에디터 설정 항목 참조"의 "Jobs"]를 참고한다.
* Pod Template +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Pod Template>["폼 에디터 설정 항목 참조"의 "Pod Template"]을 참고한다.
* Secrets
+
----
name
----
* Workspaces +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Workspaces>["폼 에디터 설정 항목 참조"의 "Workspaces"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 인테그레이션 컨피그를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/ci-cd#img-integration-config-main,인테그레이션 컨피그 메인 화면>>의 네임스페이스 선택 영역에서 새로운 인테그레이션 컨피그를 생성할 네임스페이스를 선택한 후 *[인테그레이션 컨피그 생성]* 버튼을 클릭한다.
. *Create Integration Config* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 인테그레이션 컨피그의 구성 정보를 작성한다.
+
.기본 작성 예 (TD: 인테그레이션 컨피그에 맞는 샘플 예제 작성 필요) (QA: https://github.com/tmax-cloud/cicd-operator/blob/master/docs/integration_config.md#sample-yaml )
[source,yaml]
----
apiVersion: v1
kind: LimitRange
metadata:
  name: example <1>
  namespace: default <2>
spec:
  limits:
    - default: <3>
        memory: 512Mi
      defaultRequest: <4>
        memory: 256Mi
      type: Container <5>
----
+
<1> 제한 범위의 이름
<2> 제한 범위가 생성될 네임스페이스의 이름
<3> 기본 리소스 쿼타 제한 정보
<4> 기본 리소스 쿼타 요청 정보
<5> 적용될 리소스 종류
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

