= 잡 생성
:toc:
:toc-title:

본 장에서는 잡 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 잡을 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[잡]* 메뉴를 선택한다.
. *잡* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 잡을 생성할 특정 네임스페이스를 선택한다.
. *[잡 생성]* 버튼을 클릭한다.
. *잡 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 잡의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* activeDeadlineSeconds
* backoffLimit
* completionMode
* completions
* manualSelector
* parallelism
* Pod Failure Policy
* Selector +
하위 세부 항목은 xref:../form-set-item.adoc#Selector["폼 에디터 설정 항목 참조"의 "Selector"]를 참고한다.
* suspend
* Template * +
하위 세부 항목은 xref:../form-set-item.adoc#Template["폼 에디터 설정 항목 참조"의 "Template"]를 참고한다.
=======
* Selector
* Template *
* ttlSecondsAfterFinished
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 잡을 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[잡]* 메뉴를 선택한다.
. *잡* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 잡을 생성할 특정 네임스페이스를 선택한다.
. *[잡 생성]* 버튼을 클릭한다.
. *잡 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 잡의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: batch/v1
kind: Job
metadata:
  name: pi <1>
  namespace: default <2>
spec:
  
  s: 10 <3>
  parallelism: 2 <4>
  backoffLimit: 4 <5>
  activeDeadlineSeconds: 100 <6>
  template: <7>
    spec:
      containers:
      - name: pi
        image: perl
        resources: <8>
          limits: <9>
            memory: 200Mi
            cpu: 1
          requests: <10>
            memory: 100Mi
            cpu: 0.5           
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
----
+
<1> 잡의 이름
<2> 잡이 생성될 네임스페이스의 이름
<3> 최종적으로 완료되어야 할 파드의 개수
<4> 한 번에 생성될 파드의 개수
<5> 잡을 실패로 간주하기 이전에 재시도할 횟수
<6> 잡 전체의 데드라인 (단위: 초)
<7> 생성될 파드 템플릿의 상세 내역
<8> 컨테이너에 할당할 리소스의 종류 및 양 +
다음과 같은 조건에서 잡을 생성할 경우 반드시 설정 필요 +
* 네임스페이스 클레임을 통해 생성된 네임스페이스
* 리소스 쿼타가 설정된 네임스페이스 +
<9> 컨테이너가 최대로 사용할 수 있는 리소스의 양
<10> 컨테이너가 생성될 때 요청할 리소스의 양
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
