= 카프카 커넥트 생성
:toc:
:toc-title:

본 장에서는 카프카 커넥트 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 카프카 커넥트를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 커넥트]* 메뉴를 선택한다.
. *카프카 커넥트* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 커넥트를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 커넥트 생성]* 버튼을 클릭한다.
. *카프카 커넥트 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 카프카 커넥트의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Authentication
* bootstrapServers *
* Build
* clientRackInitImage
* External Configuration
* image
* Jmx Options
* Jvm Options 
* Liveness Probe
+
----
failureThreshold
initialDelaySeconds
periodSeconds
successThreshold
timeoutSeconds
----
* Logging 
* Metrics Config 
* Rack
+
----
topologyKey *
----
* Readiness Probe
+
----
failureThreshold
initialDelaySeconds
periodSeconds
successThreshold
timeoutSeconds
----
* replicas
* Template 
* Tls
+
----
▼ Trusted Certificates
│  certificate *
│  secretName *
----
* Tracing
+
----
type *
----
* version


. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 카프카 커넥트를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 커넥트]* 메뉴를 선택한다.
. *카프카 커넥트* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 커넥트를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 커넥트 생성]* 버튼을 클릭한다.
. *카프카 커넥트 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 카프카 커넥트의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster <1>
  namespace: default <2>
spec:
  image: tmaxcloudck/kafka-connect:v1.0.3
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092 <3>
  jvmOptions: <4>
    "-Xmx": "1500m"
    "-Xms": "256m"
  config: <5>
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081
    config.providers: secrets,configmaps
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
  metricsConfig: <6>
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: connect-metrics
        key: metrics-config.yml
----
+
<1> 카프카 커넥트의 이름
<2> 카프카 커넥트가 생성될 네이스페이스의 이름
<3> 카프카 커넥트 클러스터에 연결하기 위한 부트스트랩 
<4> 카프카 커넥트의 JVM 옵션 설정
<5> 카프카 커넥트의 구성 설정
<6> 카프카 커넥트의 메트릭 수집 방법 설정
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
