= 카프카 커넥터 생성
:toc:
:toc-title:

본 장에서는 카프카 커넥터 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 카프카 커넥터를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 커넥터]* 메뉴를 선택한다.
. *카프카 커넥터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 커넥터를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 커넥터 생성]* 버튼을 클릭한다.
. *카프카 커넥터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 카프카 커넥터의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* class 
* pause
* tasksMax

. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 카프카 커넥터를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 커넥터]* 메뉴를 선택한다.
. *카프카 커넥터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 커넥터를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 커넥터 생성]* 버튼을 클릭한다.
. *카프카 커넥터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 카프카 커넥터의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-source-connector <1>
  namespace: default <2>
  labels:
    strimzi.io/cluster: my-connect-cluster <3>
spec:
  class: org.apache.kafka.connect.file.FileStreamSourceConnector <4>
  tasksMax: 2 <5>
  config: <6>
    file: "/opt/kafka/LICENSE" <7>
    topic: my-topic <8>
----
+
<1> 카프카 커넥터의 이름
<2> 카프카 커넥터가 생성될 네이스페이스의 이름
<3> 동일 네임스페이스에 존재하는 카프카 커넥트 인스턴스의 이름 
<4> 카프카 커넥터 클래스의 이름
<5> 카프카 커넥터가 생성할 수 있는 최대 작업의 수
<6> 카프카 커넥터의 설정
<7> 카프카 커넥터가 사용할 파일의 경로 지정
<8> 카프카 커넥터가 생성한 데이터를 전송할 카프카 topic의 이름 지정
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
