= 카프카 커넥트 생성 (TD: 전체 검수 필요)
:toc:
:toc-title:

본 장에서는 카프카 커넥트 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 카프카 커넥트를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 커넥트]* 메뉴를 선택한다.
. *카프카 커넥트* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 커넥트를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 커넥트 생성]* 버튼을 클릭한다.
. *카프카 커넥트 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 카프카 커넥트의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Authentication +
하위 세부 항목은 xref:../form-set-item.adoc#Authentication["폼 에디터 설정 항목 참조"의 "Authentication"]을 참고한다.
* bootstrapServers *
* Build +
하위 세부 항목은 xref:../form-set-item.adoc#Build["폼 에디터 설정 항목 참조"의 "Build"]를 참고한다.
* clientRackInitImage
* External Configuration +
하위 세부 항목은 xref:../form-set-item.adoc#ExternalConfiguration["폼 에디터 설정 항목 참조"의 "External Configuration"]을 참고한다.
* image
* Jmx Options +
하위 세부 항목은 xref:../form-set-item.adoc#JmxOptions["폼 에디터 설정 항목 참조"의 "Jmx Options"]를 참고한다.
* Jvm Options +
하위 세부 항목은 xref:../form-set-item.adoc#JvmOptions["폼 에디터 설정 항목 참조"의 "Jvm Options"]를 참고한다.
* Liveness Probe
+
----
failureThreshold
initialDelaySeconds
periodSeconds
successThreshold
timeoutSeconds
----
* Logging +
하위 세부 항목은 xref:../form-set-item.adoc#Logging["폼 에디터 설정 항목 참조"의 "Logging"]을 참고한다.
* Metrics Config +
하위 세부 항목은 xref:../form-set-item.adoc#MetricsConfig["폼 에디터 설정 항목 참조"의 "Metrics Config"]를 참고한다.
* Rack
+
----
topologyKey *
----
* Readiness Probe
+
----
failureThreshold
initialDelaySeconds
periodSeconds
successThreshold
timeoutSeconds
----
* replicas
* Template +
하위 세부 항목은 xref:../form-set-item.adoc#Templatekafka["폼 에디터 설정 항목 참조"의 "Template(Kafka)"]를 참고한다.
* Tls
+
----
▼ Trusted Certificates
│  certificate *
│  secretName *
----
* Tracing
+
----
type *
----
* version


. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 카프카 커넥트를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 커넥트]* 메뉴를 선택한다.
. *카프카 커넥트* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 커넥트를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 커넥트 생성]* 버튼을 클릭한다.
. *카프카 커넥트 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 카프카 커넥트의 구성 정보를 작성한다. (TD: 기본 예제 작성 및 필수 항목에 대한 설명 작성 필요)
+
.기본 작성 예
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: example <1>
  namespace: default <2>
----
+
<1> 카프카 커넥트의 이름
<2> 카프카 커넥트가 생성될 네이스페이스의 이름
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.