= 카프카 브릿지 생성
:toc:
:toc-title:

본 장에서는 카프카 브릿지 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 카프카 브릿지를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 브릿지]* 메뉴를 선택한다.
. *카프카 브릿지* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 브릿지를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 브릿지 생성]* 버튼을 클릭한다.
. *카프카 브릿지 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 카프카 브릿지의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Authentication
* bootstrapServers *
* clientRackInitImage
* enableMetrics
* Http
* image
* Jvm Options 
* Liveness Probe
+
----
failureThreshold
initialDelaySeconds
periodSeconds
successThreshold
timeoutSeconds
----
* Logging 
* Rack
* Readiness Probe
+
----
failureThreshold
initialDelaySeconds
periodSeconds
successThreshold
timeoutSeconds
----
* replicas
* Template
* Tls
+
----
▼ Trusted Certificates
│  certificate *
│  secretName *
----
* Tracing
+
----
type *
----

. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 카프카 브릿지를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 브릿지]* 메뉴를 선택한다.
. *카프카 브릿지* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 브릿지를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 브릿지 생성]* 버튼을 클릭한다.
. *카프카 브릿지 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 카프카 브릿지의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: example <1>
  namespace: default <2>
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092 <3>
  http:
    port: 8080
----
+
<1> 카프카 브릿지의 이름
<2> 카프카 브릿지가 생성될 네이스페이스의 이름
<3> 카프카 클러스터에 연결하기 위한 부트스트랩 서버
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
