= 카프카 클러스터 생성 (TD: 전체 검수 필요)
:toc:
:toc-title:

본 장에서는 카프카 클러스터 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 카프카 클러스터를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 클러스터]* 메뉴를 선택한다.
. *카프카 클러스터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 클러스터를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 클러스터 생성]* 버튼을 클릭한다.
. *카프카 클러스터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 카프카 클러스터의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Clients Ca
+
----
certificateExpirationPolicy
generateCertificateAuthority
generateSecretOwnerReference
renewalDays
validityDays
----
* Cluster Ca
+
----
certificateExpirationPolicy
generateCertificateAuthority
generateSecretOwnerReference
renewalDays
validityDays
----
* Cruise Control +
하위 세부 항목은 xref:../form-set-item.adoc#CruiseControl["폼 에디터 설정 항목 참조"의 "Cruise Control"]를 참고한다.
* Entity Operator +
하위 세부 항목은 xref:../form-set-item.adoc#EntityOperator["폼 에디터 설정 항목 참조"의 "Entity Operator"]를 참고한다.
* Jmx Trans +
하위 세부 항목은 xref:../form-set-item.adoc#JmxTrans["폼 에디터 설정 항목 참조"의 "Jmx Trans"]를 참고한다.
* Kafka * +
하위 세부 항목은 xref:../form-set-item.adoc#Kafka["폼 에디터 설정 항목 참조"의 "Kafka"]를 참고한다.
* Kafka Exporter +
하위 세부 항목은 xref:../form-set-item.adoc#KafkaExporter["폼 에디터 설정 항목 참조"의 "Kafka Exporter"]를 참고한다.
* Maintenance Time Windows
+
----
Value *
----
* Zookeeper * +
하위 세부 항목은 xref:../form-set-item.adoc#Zookeeper["폼 에디터 설정 항목 참조"의 "Zookeeper"]를 참고한다.

. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 카프카 클러스터를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[카프카]* -> *[카프카 클러스터]* 메뉴를 선택한다.
. *카프카 클러스터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 카프카 클러스터를 생성할 특정 네임스페이스를 선택한다.
. *[카프카 클러스터 생성]* 버튼을 클릭한다.
. *카프카 클러스터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 카프카 클러스터의 구성 정보를 작성한다. (TD: 기본 예제 작성 및 필수 항목에 대한 설명 작성 필요)
+
.기본 작성 예
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: simple (1)
  namespace: default (2)
spec:
  kafka: (3)
    version: 2.8.0
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    jvmOptions:
      "-Xmx": "1500m"
      "-Xms": "256m"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper: (4)
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    jvmOptions:
      "-Xmx": "1500m"
      "-Xms": "256m"
    storage:
      type: ephemeral
----
+
<1> 카프카 클러스터의 이름
<2> 카프카 클러스터가 생성될 네이스페이스의 이름
<3> 카프카 클러스터의 상세 명세
<4> 브로커 상태 점검 및 분산 코디네이션 서비스를 제공하는 주키퍼의 상세 명세
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
