= Creating Katib
:toc:
:toc-title:

The following describes how to create Katib resources.

== YAML Editor

Create a new Katib by using the YAML editor.

. Click *[Create Katib]* in the <<../console_menu_sub/ai-dev#img-katib-main,Katib>> main screen.
. Enter configuration data about a Katib to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata: <1>
  namespace: demo <2>
  labels: <3>
    controller-tools.k8s.io: "1.0"
  name: demo-experiment <4>
spec: <5>
  objective: <6>
    type: maximize <7>
    goal: 0.99 <8>
    objectiveMetricName: Validation-accuracy <9>
    additionalMetricNames: <10>
      - accuracy
      - loss
      - Validation-loss
  metricsCollectorSpec: <11>
    source: <12>
      fileSystemPath: <13>
        path: "/result/mnist.log" <14>
        kind: File <15>
    collector: <16>
      kind: File <17>
  algorithm: <18>
    algorithmName: random <19>
  parallelTrialCount: 3 <20>
  maxTrialCount: 5 <21>
  maxFailedTrialCount: 3 <22>
  parameters: <23>
    - name: --learning_rate <24>
      parameterType: double <25>
      feasibleSpace: <26>
        min: "0.01" <27>
        max: "0.03" <28>
    - name: --dropout_rate
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.9"
  trialTemplate: <29>
    goTemplate: <30>
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: docker.io/rhojw/sample-job:3C8CE2EE
                  command:
                  - "python"
                  - "/app/fmnist-save-model-renew.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}" <31>
                  {{- end}}
                  {{- end}}
                  resources:
                    limits:
                      nvidia.com/gpu: 1
                restartPolicy: Never
----
+
<1> Experiment metadata
<2> Name of a namespace where an experiment is created
<3> Information about labels to use when classifying experiments (Key-value format)
<4> Experiment name
<5> Experiment specification
<6> Experiment's objective
<7> Objective type
<8> Objective goal
<9> Objective metric name
<10> Metrics to check besides objectives
<11> Specification of a collector that collects metrics
<12> Source to collect metrics from
<13> Information about the source in a file system
<14> Path to collect metrics to
<15> Either a file or directory in the path
<16> Collector information
<17> Collector kind
<18> Algorithm to find an optimal parameter combination
<19> Algorithm name
<20> Maximum number of trials that run in parallel
<21> Maximum trial count
<22> Maximum number of allowed failures
<23> Parameters to optimize with an experiment
<24> Parameter name
<25> Parameter type
<26> Parameter value range
<27> Minimum value of a parameter
<28> Maximum value of a parameter
<29> Trial template
<30> Go language's template
<31> Parameter format

. To create the resource with the data you entered, click *[Create]*.