= 추론 서비스 생성
:toc:
:toc-title:

본 장에서는 추론 서비스 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 추론 서비스를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[AI DevOps]* -> *[추론 서비스]* 메뉴를 선택한다.
. *추론 서비스* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 추론 서비스를 생성할 특정 네임스페이스를 선택한다.
. *[추론 서비스 생성]* 버튼을 클릭한다.
. *추론 서비스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 추론 서비스의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Explainer +
하위 세부 항목은 xref:../form-set-item.adoc#Explainer["폼 에디터 설정 항목 참조"의 "Explainer"]을 참고한다.
* Predictor * +
하위 세부 항목은 xref:../form-set-item.adoc#Predictor["폼 에디터 설정 항목 참조"의 "Predictor"]을 참고한다.
* Transformer +
하위 세부 항목은 xref:../form-set-item.adoc#Transformer["폼 에디터 설정 항목 참조"의 "Transformer"]을 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 추론 서비스를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[AI DevOps]* -> *[추론 서비스]* 메뉴를 선택한다.
. *추론 서비스* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 추론 서비스를 생성할 특정 네임스페이스를 선택한다.
. *[추론 서비스 생성]* 버튼을 클릭한다.
. *추론 서비스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 추론 서비스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata: <1>
  name: "triton-mms" <2>
  namespace: demo <3>
spec: <4>
  predictor: <5>
    serviceAccountName: minio-serviceaccount <6>
    triton: <7>
      args:
      - --log-verbose=1
      - --strict-model-config=false
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 8Gi
----
+
<1> 추론 서비스의 메타데이터
<2> 추론 서비스의 이름
<3> 추론 서비스가 생성될 네임스페이스의 이름
<4> 추론 서비스의 사양
<5> 머신러닝의 예측(predictor) 모델에 대한 사양
<6> 추론 서비스에서 생성한 파드를 실행할 때 사용할 서비스 어카운트의 이름
<7> Trition 추론 서버의 사양

. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
