= Creating Namespace Claims
:toc:
:toc-title:

The following describes how to create namespace claim resources.

== YAML Editor

Create a new namespace claim by using the YAML editor.

. Click *[Create Namespace Claims]* in the <<../console_menu_sub/management#img-namespace-claim-main,Namespace Claims>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a namespace claim to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tmax.io/v1
kind: NamespaceClaim
metadata:
  name: example <1>
  labels:
    handled: f <2>
resourceName: example-namespaceclaim <3>
spec: <4>
  hard:
    limits.cpu: "1" 
    limits.memory: "1Gi"
----
+
<1> Namespace claim name
<2> Label used to detect creation, modification, and deletion of the claim in HyperCloud Operator *(Required)*
<3> Name of a namespace to be created when the namespace claim is approved
<4> Type and volume of resources to allocate
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new namespace claim by using the Form editor.

. Click *[Create Namespace Claims]* in the <<../console_menu_sub/management#img-namespace-claim-main,Namespace Claims>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Namespace Claim* screen opened, enter configuration data about a namespace claim to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name*|Namespace claim name.
|Labels|Labels to add to the namespace claim.
|Resource Name*|Name of the namespace to be created when the namespace claim is approved.
|Namespace Resource Quota*|Type and volume of resources used in the namespace. When the namespace claim is approved, a resource quota is created with the resource name.

* CPU Limits: Limit of CPU resource to use
* Memory Limits: Limit of memory resource to use

To add other types of resources besides CPU Limits and Memory Limits, click **[+ Add More]**. Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|====================
. To create the resource with the data you entered, click *[Create]*.