= Creating Namespaces
:toc:
:toc-title:

The following describes how to create namespace resources.

== YAML Editor

Create a new namespace by using the YAML editor.

. Click *[Create Namespaces]* in the <<../console_menu_sub/management#img-namespace-main,Namespaces>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a namespace to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: example <1>
----
+
<1> Namespace name
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new namespace by using the Form editor.

. Click *[Create Namespaces]* in the <<../console_menu_sub/management#img-namespace-main,Namespaces>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Namespace* screen opened, enter configuration data about a namespace to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name*|Namespace name.
|Labels|Labels to add to the namespace.
|====================
. To create the resource with the data you entered, click *[Create]*.