= Creating Network Policies
:toc:
:toc-title:

The following describes how to create network policy resources.

== YAML Editor

Create a new network policy by using the YAML editor.

. Click *[Create Network Policies]* in the <<../console_menu_sub/security#img-network-main,Network Policies>> main screen.
. Enter configuration data about a network policy to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example-network-policy <1>
  namespace: default <2>
spec:
  podSelector: <3>
    matchLabels:
     role: db
  policyTypes: <4>
  - Ingress
  - Egress
  ingress: <5>
  - from:
    - ipBlock: <6>
        cidr: 172.17.0.0/16
        except:
        - 172.17.1.0/24
    - namespaceSelector: <7>
        matchLabels:
          project: myproject
    - podSelector: <8>
        matchLabels:
          role: frontend
  - ports: <9>
    - port: 5000
      protocol: TCP
  egress: <10>
  - to:
    - ipBlock:
        cidr: 172.17.0.0/16
        except:
        - 172.17.1.0/24
    - namespaceSelector:
        matchLabels:
          project: myproject
  - ports:
    - port: 5000
      protocol: TCP
----
+
<1> Network policy name
<2> Name of a namespace where the network policy is created
<3> Pod selector to apply the network policy to
<4> Policy type (Default value: Ingress)
<5> Information about the policy type (Example: ingress)
<6> IP band that allows traffic
<7> Namespace selector that allows traffic
<8> Pod selector that allows traffic
<9> Port and protocol that allow traffic
<10> Information about the policy type (Example: egress)

. To create the resource with the data you entered, click *[Create]*.