= 노트북 서버 생성
:toc:
:toc-title:

본 장에서는 노트북 서버 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 노트북 서버를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[AI DevOps]* -> *[노트북 서버]* 메뉴를 선택한다.
. *노트북 서버* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 노트북 서버를 생성할 특정 네임스페이스를 선택한다.
. *[노트북 서버 생성]* 버튼을 클릭한다.
. *노트북 서버 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 노트북 서버의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Template +
하위 세부 항목은 xref:../form-set-item.adoc#TemplateNotebook["폼 에디터 설정 항목 참조"의 "Template(Notebook Server)"]을 참고한다.
* Volume Claim
+
----
name *
size *
storageClass
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 노트북 서버를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[AI DevOps]* -> *[노트북 서버]* 메뉴를 선택한다.
. *노트북 서버* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 노트북 서버를 생성할 특정 네임스페이스를 선택한다.
. *[노트북 서버 생성]* 버튼을 클릭한다.
. *노트북 서버 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 노트북 서버의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: kubeflow.tmax.io/v1
kind: Notebook
metadata: <1>
  labels: <2>
    app: demo-notebook
  name: demo-notebook <3>
  namespace: demo <4>
spec: <5>
  template: <6>
    spec: <7>
      containers: <8>
      - env: [] <9>
        image: 'brightfly/kubeflow-jupyter-lab:tf2.0-gpu' <10>
        name: demo <11>
        resources: <12>
          requests: <13>
            cpu: "0.5" <14>
            memory: 1.0Gi <15>
        volumeMounts: <16>
        - mountPath: /home/jovyan <17>
          name: demo-pvc <18>
        - mountPath: /dev/shm
          name: dshm
      serviceAccountName: default-editor <19>
      ttlSecondsAfterFinished: 300 <20>
      volumes: <21>
      - name: demo-pvc <22>
        persistentVolumeClaim: <23>
          claimName: demo-pvc <24>
      - emptyDir: <25>
          medium: Memory <26>
        name: dshm <27>
  volumeClaim: <28>
  - name: demo-pvc <29>
    size: 10Gi <30>
----
+
<1> 노트북의 메타데이터
<2> 노트북을 분류할 때 사용할 레이블 정보 (키-값 형식)
<3> 노트북의 이름
<4> 노트북이 생성될 네임스페이스의 이름
<5> 노트북의 스펙
<6> 노트북 파드에 대한 상세 내역
<7> 노트북 파드의 스펙
<8> 노트북 파드를 구성할 컨테이너의 목록
<9> 컨테이너에 추가할 환경 변수
<10> 컨테이너의 이미지
<11> 컨테이너의 이름
<12> 컨테이너에 필요한 리소스 양
<13> 리소스 요청
<14> 요청할 CPU 개수
<15> 요청할 메모리 크기
<16> 컨테이너에 마운트할 볼륨 정보
<17> 볼륨을 마운트할 경로
<18> 마운트할 볼륨의 이름
<19> 노트북 파드에 할당할 서비스 어카운트의 이름
<20> 잡 완료 후 자동 삭제까지의 소요 시간 (단위: 초)
<21> 노트북 파드에서 사용할 볼륨을 지정
<22> 볼륨의 이름
<23> 볼륨의 타입 (PVC 타입)
<24> PVC의 이름
<25> 볼륨의 타입 (emptyDir 타입)
<26> 볼륨의 저장 매체
<27> 볼륨의 이름
<28> 노트북에 마운트할 PVC 생성
<29> 생성할 PVC의 이름
<30> 생성할 PVC의 크기
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
