= Creating Notebook Server
:toc:
:toc-title:

The following describes how to create notebook server resources.

== YAML Editor

Create a new notebook server by using the YAML editor.

. Click *[Create Notebook Server]* in the <<../console_menu_sub/ai-dev#img-notebook-server-main,Notebook Server>> main screen.
. Enter configuration data about a notebook server to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: hyperflow.tmax.io/v1
kind: Notebook
metadata: <1>
  labels: <2>
    app: demo-notebook
  name: demo-notebook <3>
  namespace: demo <4>
spec: <5>
  template: <6>
    spec: <7>
      containers: <8>
      - env: [] <9>
        image: 'brightfly/kubeflow-jupyter-lab:tf2.0-gpu' <10>
        name: demo <11>
        resources: <12>
          requests: <13>
            cpu: "0.5" <14>
            memory: 1.0Gi <15>
        volumeMounts: <16>
        - mountPath: /home/jovyan <17>
          name: demo-pvc <18>
        - mountPath: /dev/shm
          name: dshm
      serviceAccountName: default-editor <19>
      ttlSecondsAfterFinished: 300 <20>
      volumes: <21>
      - name: demo-pvc <22>
        persistentVolumeClaim: <23>
          claimName: demo-pvc <24>
      - emptyDir: <25>
          medium: Memory <26>
        name: dshm <27>
  volumeClaim: <28>
  - name: demo-pvc <29>
    size: 10Gi <30>
----
+
<1> Notebook metadata
<2> Information about labels to use when classifying notebooks (Key-value format)
<3> Notebook name
<4> Name of a namespace where the notebook is created
<5> Notebook specification
<6> Information about the notebook pod
<7> Notebook pod specification
<8> Containers included in the notebook pod
<9> Environment variable to add to a container
<10> Container image
<11> Container name
<12> Resource amount required for a container
<13> Resource requests
<14> Number of CPUs to request
<15> Memory size to request
<16> Information about a volume to mount to a container
<17> Path to mount a volume to
<18> Name of a volume to mount
<19> Name of a service account allocated to the notebook pod
<20> Time period from job completion to automatic deletion (Unit: seconds)
<21> Volume used by the notebook pod
<22> Volume name
<23> Volume type (PVC type)
<24> PVC name
<25> Volume type (emptyDir type)
<26> Volume's storage device
<27> Volume name
<28> Information about PVC to mount to the notebook
<29> Name of PVC to create
<30> Size of PVC to create

. To create the resource with the data you entered, click *[Create]*.