= Creating Persistent Volumes
:toc:
:toc-title:

The following describes how to create persistent volume resources.

== YAML Editor

Create a new persistent volume by using the YAML editor.

. Click *[Create Persistent Volumes]* in the <<../console_menu_sub/storage#img-pv-main,Persistent Volumes>> main screen.
. Enter configuration data about a persistent volume to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example <1>
spec:
  capacity:
    storage: 5Gi <2>
  accessModes: <3>
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle <4>
  storageClassName: slow <5>
  # mountOptions: <6>
  #   - hard
  #   - nfsvers=4.1
  nfs: <7>
    path: /tmp
    server: 172.17.0.2
----
+
<1> Persistent volume name
<2> Persistent volume size
<3> Access mode of a persistent volume +
If a block storage class is sued, ReadWriteMany can be set only when the volume usage mode is set to Block.
* ReadWriteOnce: One node mounts a volume in read-write mode.
* ReadOnlyMany: Multiple nodes mount a volume in read-only mode.
* ReadWriteMany: Multiple nodes mount a volume in read-write mode.
<4> Policy of handling persistent volumes used (Default value: Delete)
* Retain: Retain the volume and its data.
* Recycle: Delete the volume data and reuse the data in a new persistent volume claim (Available only when the plugin type is nfs or hostpath)
* Delete: Delete the volume.
<5> Storage class name of the persistent volume
<6> Mount option depending on plugin
<7> Information about the plugin type to use when provisioning a storage

. To create the resource with the data you entered, click *[Create]*.