= Creating Persistent Volume Claims
:toc:
:toc-title:

The following describes how to create persistent volume claim resources.

== YAML Editor

Create a new persistent volume claim by using the YAML editor.

. Click *[Create Persistent Volume Claims]* in the <<../console_menu_sub/storage#img-pvc-main,Persistent Volume Claims>> main screen.
. Enter configuration data about a persistent volume claim to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example <1>
  # namespace: default <2>
spec:
  accessModes: <3>
    - ReadWriteOnce
  # volumeMode: Filesystem <4>
  resources:
    requests:
      storage: 8Gi <5>
  storageClassName: slow <6>
  selector: <7>
    matchLabels: 
      release: stable
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
----
+
<1> Persistent volume claim name
<2> Name of a namespace where the persistent volume claim is created (Default value: default)
<3> Access mode of a persistent volume claim +
If a block storage class is sued, ReadWriteMany can be set only when the volume usage mode is set to Block.
* ReadWriteOnce: One node mounts a volume in read-write mode.
* ReadOnlyMany: Multiple nodes mount a volume in read-only mode.
* ReadWriteMany: Multiple nodes mount a volume in read-write mode.
<4> Volume usage mode (Default value: Filesystem)
* Filesystem
* Block
<5> Persistent volume claim size
<6> Storage class name of the persistent volume claim
<7> Information about the persistent volume claim and a volume to bind +
Only volumes that meet both 'matchLabels' and 'matchExpressions' can be bound.

. To create the resource with the data you entered, click *[Create]*.