= 영구 볼륨 생성
:toc:
:toc-title:

본 장에서는 영구 볼륨 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 영구 볼륨을 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[스토리지]* -> *[영구 볼륨]* 메뉴를 선택한다.
. *영구 볼륨* 메인 화면이 열리면 *[영구 볼륨 생성]* 버튼을 클릭한다.
. *영구 볼륨 생성* 화면이 열리면 **다음을 통해 설정**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 영구 볼륨의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Access Modes *
+
----
Value
----
* Aws Elastic Block Store
+
----
fsType
partition
readOnly
volumeID *
----
* Azure Disk
+
----
cachingMode
diskName *
diskURI *
fsType
kind
readOnly
----
* Azure File
+
----
readOnly
secretName *
secretNamespace
shareName *
----
* Capacity *
+
----
KEY
VALUE
----
* Cephfs +
하위 세부 항목은 xref:../form-set-item.adoc#Cephfs["폼 에디터 설정 항목 참조"의 "Cephfs"]를 참고한다.
* Cinder +
하위 세부 항목은 xref:../form-set-item.adoc#Cinder["폼 에디터 설정 항목 참조"의 "Cinder"]를 참고한다.
* Claim Ref
+
----
apiVersion
fieldPath
kind
name
namespace
resourceVersion
uid
----
* Csi +
하위 세부 항목은 xref:../form-set-item.adoc#Csi["폼 에디터 설정 항목 참조"의 "Csi"]를 참고한다.
* Fc +
하위 세부 항목은 xref:../form-set-item.adoc#Fc["폼 에디터 설정 항목 참조"의 "Fc"]를 참고한다.
* Flex Volume +
하위 세부 항목은 xref:../form-set-item.adoc#FlexVolume["폼 에디터 설정 항목 참조"의 "Flex Volume"]을 참고한다.
* Flocker
+
----
datasetName
datasetUUID
----
* Gce Persistent Disk
+
----
fsType
partition
pdName *
readOnly
----
* Glusterfs
+
----
endpoints *
path *
readOnly
----
* Host Path
+
----
path *
type
----
* Iscsi +
하위 세부 항목은 xref:../form-set-item.adoc#Iscsi["폼 에디터 설정 항목 참조"의 "Iscsi"]를 참고한다.
* Local
+
----
path *
----
* Mount Options
+
----
Value
----
* Nfs
+
----
path *
readOnly
server *
----
* Node Affinity +
하위 세부 항목은 xref:../form-set-item.adoc#NodeAffinity["폼 에디터 설정 항목 참조"의 "Node Affinity"]를 참고한다.
* persistentVolumeReclaimPolicy
* Photon Persistent Disk
+
----
fsType
pdID *
----
* Portworx Volume
+
----
fsType
readOnly
volumeID *
----
* Quobyte
+
----
group
readOnly
registry *
user
volume *
----
* Rbd +
하위 세부 항목은 xref:../form-set-item.adoc#Rbd["폼 에디터 설정 항목 참조"의 "Rbd"]를 참고한다.
* Scale IO +
하위 세부 항목은 xref:../form-set-item.adoc#ScaleIO["폼 에디터 설정 항목 참조"의 "Scale IO"]를 참고한다.
* storageClassName
* Storageos +
하위 세부 항목은 xref:../form-set-item.adoc#Storageos["폼 에디터 설정 항목 참조"의 "Storageos"]를 참고한다.
* volumeMode
* Vsphere Volume
+
----
fsType
storagePolicyID
storagePolicyName
volumePath *
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 영구 볼륨을 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[스토리지]* -> *[영구 볼륨]* 메뉴를 선택한다.
. *영구 볼륨* 메인 화면이 열리면 *[영구 볼륨 생성]* 버튼을 클릭한다.
. *영구 볼륨 생성* 화면이 열리면 **다음을 통해 설정**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 영구 볼륨의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example <1>
spec:
  capacity:
    storage: 5Gi <2>
  accessModes: <3>
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete <4>
  storageClassName: hostpath <5>
  hostPath: 
    path: /mnt/dir1 <6>
    type: DirectoryOrCreate <7>

----
+
<1> 영구 볼륨의 이름
<2> 영구 볼륨의 크기
<3> 영구 볼륨의 접근 모드 +
만약 블록 스토리지 클래스를 사용하는 경우 volumeMode가 Block인 경우에만 ReadWriteMany 적용이 가능
* ReadWriteOnce : 하나의 노드에서 볼륨을 읽기, 쓰기로 마운트
* ReadOnlyMany : 여러 노드에서 볼륨을 읽기 전용으로 마운트
* ReadWriteMany : 여러 노드에서 볼륨을 읽기, 쓰기로 마운트
<4> 사용이 끝난 영구 볼륨의 처리 방식 (기본값: Delete) 
* Retain : 볼륨을 삭제하지 않고, 데이터를 보존
* Delete : 볼륨을 삭제
<5> 영구 볼륨의 스토리지 클래스 이름
<6> hostPath 볼륨의 디렉터리 경로
<7> hostPath 볼륨의 타입
* DirectoryOrCreate : ``path``에 설정한 경로에 디렉터리가 없으면 Kubelet이 가지고 있는 동일한 그룹과 소유권, 권한을 0755로 설정한 빈 디렉터리를 생성함
* Directory : ``path``에 설정한 경로에 해당 디렉터리가 존재해야 함
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.