= 영구 볼륨 생성
:toc:
:toc-title:

본 장에서는 영구 볼륨 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 영구 볼륨을 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[스토리지]* -> *[영구 볼륨]* 메뉴를 선택한다.
. *영구 볼륨* 메인 화면이 열리면 *[영구 볼륨 생성]* 버튼을 클릭한다.
. *Create Persistent Volume* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 영구 볼륨의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Access Modes
+
----
Value
----
* Aws Elastic Block Store
+
----
fsType
partition
readOnly
volumeID *
----
* Azure Disk
+
----
cachingMode
diskName *
diskURI *
fsType
kind
readOnly
----
* Azure File
+
----
readOnly
secretName *
secretNamespace
shareName *
----
* Capacity
+
----
KEY
VALUE
----
* Cephfs +
하위 세부 항목은 xref:../form-set-item.adoc#<Cephfs>["폼 에디터 설정 항목 참조"의 "Cephfs"]를 참고한다.
* Cinder +
하위 세부 항목은 xref:../form-set-item.adoc#<Cinder>["폼 에디터 설정 항목 참조"의 "Cinder"]를 참고한다.
* Claim Ref
+
----
apiVersion
fieldPath
kind
name
namespace
resourceVersion
uid
----
* Csi +
하위 세부 항목은 xref:../form-set-item.adoc#<Csi>["폼 에디터 설정 항목 참조"의 "Csi"]를 참고한다.
* Fc +
하위 세부 항목은 xref:../form-set-item.adoc#<Fc>["폼 에디터 설정 항목 참조"의 "Fc"]를 참고한다.
* Flex Volume +
하위 세부 항목은 xref:../form-set-item.adoc#<Flex Volume>["폼 에디터 설정 항목 참조"의 "Flex Volume"]을 참고한다.
* Flocker
+
----
datasetName
datasetUUID
----
* Gce Persistent Disk
+
----
fsType
partition
pdName *
readOnly
----
* Glusterfs
+
----
endpoints *
path *
readOnly
----
* Host Path
+
----
path
type
----
* Iscsi +
하위 세부 항목은 xref:../form-set-item.adoc#<Iscsi>["폼 에디터 설정 항목 참조"의 "Iscsi"]를 참고한다.
* Local
+
----
path *
----
* Mount Options
+
----
Value
----
* Nfs
+
----
path *
readOnly
server *
----
* Node Affinity +
하위 세부 항목은 xref:../form-set-item.adoc#<Node Affinity>["폼 에디터 설정 항목 참조"의 "Node Affinity"]를 참고한다.
* persistentVolumeReclaimPolicy
* Photon Persistent Disk
+
----
fsType
pdID *
----
* Portworx Volume
+
----
fsType
readOnly
volumeID *
----
* Quobyte
+
----
group
readOnly
registry *
user
volume *
----
* Rbd +
하위 세부 항목은 xref:../form-set-item.adoc#<Rbd>["폼 에디터 설정 항목 참조"의 "Rbd"]를 참고한다.
* Scale IO +
하위 세부 항목은 xref:../form-set-item.adoc#<Scale IO>["폼 에디터 설정 항목 참조"의 "Scale IO"]를 참고한다.
* storageClassName
* Storageos +
하위 세부 항목은 xref:../form-set-item.adoc#<Storageos>["폼 에디터 설정 항목 참조"의 "Storageos"]를 참고한다.
* volumeMode
* Vsphere Volume
+
----
fsType
storagePolicyID
storagePolicyName
volumePath *
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 영구 볼륨을 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[스토리지]* -> *[영구 볼륨]* 메뉴를 선택한다.
. *영구 볼륨* 메인 화면이 열리면 *[영구 볼륨 생성]* 버튼을 클릭한다.
. *Create Persistent Volume* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 영구 볼륨의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example <1>
spec:
  capacity:
    storage: 5Gi <2>
  accessModes: <3>
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete <4>
  storageClassName: nfs <5>
  # mountOptions: <6>
  #   - hard
  #   - nfsvers=4.1
  nfs: <7>
    path: /tmp
    server: 172.17.0.2
----
+
<1> 영구 볼륨의 이름
<2> 영구 볼륨의 크기
<3> 영구 볼륨의 접근 모드 +
만약 블록 스토리지 클래스를 사용하는 경우 volumeMode가 Block인 경우에만 ReadWriteMany 적용이 가능
* ReadWriteOnce : 하나의 노드에서 볼륨을 읽기, 쓰기로 마운트
* ReadOnlyMany : 여러 노드에서 볼륨을 읽기 전용으로 마운트
* ReadWriteMany : 여러 노드에서 볼륨을 읽기, 쓰기로 마운트
<4> 사용이 끝난 영구 볼륨의 처리 방식 (기본값: Delete) 
* Retain : 볼륨을 삭제하지 않고, 데이터를 보존
* Delete : 볼륨을 삭제
<5> 영구 볼륨의 스토리지 클래스 이름
<6> 플러그인의 특성에 따른 마운트 옵션
<7> 스토리지를 프로비저닝할 때 사용할 플러그인 유형의 상세 명세
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.