= Creating Pipelines
:toc:
:toc-title:

The following describes how to create pipeline resources.

== YAML Editor

Create a new pipeline by using the YAML editor.

. Click *[Create Pipelines]* in the <<../console_menu_sub/ci-cd#img-pipeline-main,Pipelines>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a pipeline to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-pipeline
  namespace: default
spec:
  resources: <1>
    - name: source-repo
      type: git
    - name: sample-image
      type: image
  tasks:
    - name: task1
      taskRef: <2>
        name: example-task1
      params: <3>
        - name: example-string
          value: sample-string1
      resources:
        inputs: <4>
          - name: example-pipeline-resource-git
            resource: source-repo
        outputs: <5>
          - name: example-pipeline-resource-image
            resource: sample-image
    - name: task2
      taskRef:
        name: example-task2
      resources:
        inputs:
          - name: example-input-image
            resource: sample-image
            from:
              - task1
----
+
<1> Information about the pipeline referred by a task
<2> Name of a task to run in the pipeline
<3> Information about parameters referred by a container image that runs in a task
<4> Information about a pipeline resource referred by a container image that runs in a task
<5> Information about results generated after running a task

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new pipeline by using the Form editor.

. Click *[Create Pipelines]* in the <<../console_menu_sub/ci-cd#img-pipeline-main,Pipelines>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Pipelines* screen opened, enter configuration data about a pipeline to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description
|Name*|Pipeline name.
|Parameter Configuration|Parameters referred by the pipeline. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Name: Parameter name.
* Description: Brief parameter description.
* Default Value: Default value of the parameter.
|Resource Configuration*|Pipeline resources used by the pipeline. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Name: Pipeline resource name.
* Resource Type: Pipeline resource type.
|Pipeline Build|Task included in the pipeline. After adding a task, you can see *[+]* on the left and right of and below the task. By clicking the button on the left, you can add a sequential task before the task. By clicking the button on the right, you can add a sequential task after the task. By clicking the button on the below, you can add a parallel task. +
In addition, clicking the added task displays the page where you can set the task's parameter, input resource, and output resource data. To delete the added task, click *[Actions]* > **[Delete Task]**.
|====================

. To create the resource with the data you entered, click *[Create]*.