= Creating Pipeline Resources
:toc:
:toc-title:

The following describes how to create pipeline resources.

== YAML Editor

Create a new pipeline resource by using the YAML editor.

. Click *[Create Pipeline Resources]* in the <<../console_menu_sub/ci-cd#img-pipeline-resource-main,Pipeline Resources>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a pipeline resource to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: example-pipeline-resource-git <1>
  namespace: default
spec:
  type: git <2>
  params: <3>
    - name: revision
      value: master
    - name: url
      value: 'https://github.com/sample/git/url'
----
+
<1> Pipeline resource name
<2> Pipeline resource type
<3> Information about configuration storage and the registry

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new pipeline resource by using the Form editor.

. Click *[Create Pipeline Resources]* in the <<../console_menu_sub/ci-cd#img-pipeline-resource-main,Pipeline Resources>> main screen.
. Select **[From Editor]** from the drop down menu.
. In the *Create Pipeline Resources* screen opened, enter configuration data about a pipeline resource to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description
|Name|Pipeline resource name.
|Type|Pipeline resource type.

* git: Source code in Git storage.
* Image: Image located in remote storage.
|Parameters|Information about configuration storage and the registry.

* Revision: branch name of the configuration storage. (Only available when the type is **"git"**)
* Url: configuration storage and the registry URL
|Labels|Labels to add to the pipeline resource.
|====================

. To create the resource with the data you entered, click *[Create]*.