= Creating Pipeline Runs
:toc:
:toc-title:

The following describes how to create pipeline run resources.

== YAML Editor

Create a new pipeline run by using the YAML editor.

. Click *[Create Pipeline Runs]* in the <<../console_menu_sub/ci-cd#img-pipeline-run-main,Pipeline Runs>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a pipeline run to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: example-pipeline-run
  namespace: default
spec:
  serviceAccountName: example-san <1>
  pipelineRef: <2>
    name: example-pipeline
  resources:
    - name: source-repo
      resourceRef: <3>
        name: example-pipeline-resource-git
    - name: sample-image
      resourceRef:
        name: example-pipeline-resource-image
----
+
<1> Name of a service account that has privilege to create a resource in a namespace
<2> Name of a pipeline that runs in the pipeline run
<3> Information about a pipeline resource referred by a container image that runs in a task

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new pipeline run by using the Form editor.

. Click *[Create Pipeline Runs]* in the <<../console_menu_sub/ci-cd#img-pipeline-run-main,Pipeline Runs>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Pipeline Runs* screen opened, enter configuration data about a pipeline run to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description  
|Name|Pipeline run name.
|Pipeline|Name of a pipeline to run.
|Parameters|Values of parameters to which a container image that runs in a task included in a pipeline refers.
|Service Account Name|Name of a service account that has privilege to create a resource in a namespace.
|Labels|Labels to add to the pipeline run.
|====================

. To create the resource with the data you entered, click *[Create]*.