= 파드 생성
:toc:
:toc-title:

본 장에서는 파드 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 파드를 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[파드]* 메뉴를 선택한다.
. *파드* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 파드를 생성할 특정 네임스페이스를 선택한다.
. *[파드 생성]* 버튼을 클릭한다.
. *파드 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 파드의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* activeDeadlineSeconds
* Affinity +
하위 세부 항목은 xref:../form-set-item.adoc#Affinity["폼 에디터 설정 항목 참조"의 "Affinity"]를 참고한다.
* automountServiceAccountToken
* Containers * +
하위 세부 항목은 xref:../form-set-item.adoc#Containers["폼 에디터 설정 항목 참조"의 "Containers"]를 참고한다.
* Dns Config +
하위 세부 항목은 xref:../form-set-item.adoc#DnsConfig["폼 에디터 설정 항목 참조"의 "Dns Config"]를 참고한다.
* dnsPolicy
* enableServiceLinks
* Ephemeral Containers +
하위 세부 항목은 xref:../form-set-item.adoc#EphemeralContainers["폼 에디터 설정 항목 참조"의 "Ephemeral Containers"]를 참고한다.
* Host Aliases +
하위 세부 항목은 xref:../form-set-item.adoc#HostAliases["폼 에디터 설정 항목 참조"의 "Host Aliases"]를 참고한다.
* hostIPC
* hostNetwork
* hostPID
* hostname
* Image Pull Secrets
+
----
name
----
* Init Containers +
하위 세부 항목은 xref:../form-set-item.adoc#Containers["폼 에디터 설정 항목 참조"의 "Containers"]를 참고한다.
* nodeName
* nodeSelector
* Overhead
+
----
KEY
VALUE
----
* preemptionPolicy
* priority
* priorityClassName
* Readiness Gates
+
----
conditionType *
----
* restartPolicy
* runtimeClassName
* schedulerName
* Security Context +
하위 세부 항목은 xref:../form-set-item.adoc#SecurityContext["폼 에디터 설정 항목 참조"의 "Security Context"]를 참고한다.
* serviceAccountName
* setHostnameAsFQDN
* shareProcessNamespace
* subdomain
* terminationGracePeriodSeconds
* Tolerations
+
----
effect
key
operator
tolerationSeconds
value
----
* Topology Spread Constraints +
하위 세부 항목은 xref:../form-set-item.adoc#TopologySpreadConstraints["폼 에디터 설정 항목 참조"의 "Topology Spread Constraints"]를 참고한다.
* Volumes +
하위 세부 항목은 xref:../form-set-item.adoc#Volumes["폼 에디터 설정 항목 참조"의 "Volumes"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 파드를 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[파드]* 메뉴를 선택한다.
. *파드* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 파드를 생성할 특정 네임스페이스를 선택한다.
. *[파드 생성]* 버튼을 클릭한다.
. *파드 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 파드의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: example <1>
  labels: <2>
    app: hello-hypercloud
  namespace: default <3>
spec:
  containers: <4>
    - name: hello-hypercloud <5>
      image: hypercloud/hello-hypercloud <6>
      resources: <7>
        limits: <8>
          memory: 200Mi
          cpu: 1
        requests: <9>
          memory: 100Mi
          cpu: 0.5
      ports: <10>
        - containerPort: 8080 <11>
----
+
<1> 파드의 이름
<2> 파드를 분류할 때 사용할 레이블 정보 (키-값 형식)
<3> 파드가 생성될 네임스페이스의 이름
<4> 파드를 구성할 컨테이너의 상세 내역
<5> 컨테이너의 이름
<6> 컨테이너의 이미지
<7> 컨테이너에 할당할 리소스의 종류 및 양 +
다음과 같은 조건에서 파드를 생성할 경우 반드시 설정 필요 +
* 네임스페이스 클레임을 통해 생성된 네임스페이스
* 리소스 쿼타가 설정된 네임스페이스 +
<8> 컨테이너가 최대로 사용할 수 있는 리소스의 양
<9> 컨테이너가 생성될 때 요청할 리소스의 양
<10> 컨테이너에서 노출할 포트 목록
<11> 파드의 IP 주소에서 노출할 포트 번호
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.