= Creating Pod Security Policies
:toc:
:toc-title:

The following describes how to create pod security policy resources.

== YAML Editor

=== Privileged Permission

Create a new pod security policy for privileged permission by using the YAML editor.

. Click *[Create Pod Security Policies]* in the <<../console_menu_sub/security#img-pod-security-main,Pod Security Policies>> main screen.
. Enter configuration data about a pod security policy (privileged permission) to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged <1>
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*' <2>
spec:
  privileged: true <3>
  allowPrivilegeEscalation: true <4>
  readOnlyRootFilesystem: false <5>
  allowedCapabilities: <6>
  - '*'
  volumes: <7>
  - '*'
  hostNetwork: true <8>
  hostPorts: <9>
  - min: 0
    max: 65535
  hostIPC: true <10>
  hostPID: true <11>
  runAsUser: <12>
    rule: 'RunAsAny'
  seLinux: <13>
    rule: 'RunAsAny'
  supplementalGroups: <14>
    rule: 'RunAsAny'
  fsGroup: <15>
    rule: 'RunAsAny'
----
+
<1> Pod security policy name
<2> Allowed value for seccomp (``*`` allows all profiles.) +
If not set, a default value cannot be changed.
* unconfined
* runtime/default
* docker/default
* localhost/<path>
* *
<3> Option to use privileged mode of a container included in a pod
* true: Use the mode.
* false: A container's sub-process cannot have more permissions than a parent process.
<4> Option to allow an escalation for a root permission
* true: Allows an escalation.
* false: A container's sub-process cannot have more permissions than a parent process.
<5> Permission for a root file system (Default value: true)
* true: Read-only permission.
* false: Read/write permission.
<6> Functions available for a container (``*`` allows all functions.)
<7> Allowed volume types +
Allowed values are volume source defined when creating the volume (``*`` allows all volume types)
<8> Option to use a network namespace of a node
<9> Port range allowed for a network namespace of a host
<10> Option to share an IPC namespace of a host
<11> Option to share a process ID namespace of a host
<12> Control range of an ID of a user who runs a container
* MustRunAs
* MustRunAsNonRoot
* RunAsAny
<13> Control range of SELinux
* MustRunAs
* RunAsAny
<14> Control range of a group ID to be added by a container
* MustRunAs
* MayRunAs
* RunAsAny
<15> Control range of a supplement group to apply to some volumes
* MustRunAs
* MayRunAs
* RunAsAny

. To create the resource with the data you entered, click *[Create]*.

=== Restricted Permission

Create a new pod security policy for restricted permission by using the YAML editor.

. Click *[Create Pod Security Policies]* in the <<../console_menu_sub/security#img-pod-security-main,Pod Security Policies>> main screen.
. Enter configuration data about a pod security policy (restricted permission) to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted <1>
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default' <2>
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default' <3>
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default' <4>
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default' <5>
spec:
  privileged: false <6>
  allowPrivilegeEscalation: false <7>
  requiredDropCapabilities: <8>
    - ALL
  volumes: <9>
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false <10>
  hostIPC: false <11>
  hostPID: false <12>
  runAsUser: <13>
    rule: 'MustRunAsNonRoot'
  seLinux: <14>
    rule: 'RunAsAny'
  supplementalGroups: <15>
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup: <16>
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true <17>
----
+
<1> Pod security policy name
<2> Allowed value for seccomp (``*`` allows all profiles.) +
If not set, a default value cannot be changed.
* unconfined
* runtime/default
* docker/default
* localhost/<path>
* *
<3> Default value used by seccomp
* unconfined
* runtime/default
* docker/default
* localhost/<path>
<4> Default value allowed for apparmor
* unconfined
* runtime/default
* localhost/<profile_name>
<5> Default value used by apparmor
* unconfined
* runtime/default
* localhost/<profile_name>
<6> Option to use privileged mode of a container included in a pod
<7> Option to allow an escalation for a root permission
* true: Allows an escalation.
* false: A container's sub-process cannot have more permissions than a parent process.
<8> Functions to remove from a container +
The functions must not be included in ``allowedCapabilities`` or ``defaultAddCapabilities``.
<9> Allowed volume types +
Allowed values are volume source defined when creating the volume (``*`` allows all volume types)
<10> Option to use a network namespace of a node
<11> Option to share an IPC namespace of a host
<12> Option to share a process ID namespace of a host
<13> Control range of an ID of a user who runs a container
* MustRunAs
* MustRunAsNonRoot
* RunAsAny
<14> Control range of SELinux
* MustRunAs
* RunAsAny
<15> Control range of a group ID to be added by a container
* MustRunAs
* MayRunAs
* RunAsAny
<16> Control range of a supplement group to apply to some volumes
* MustRunAs
* MayRunAs
* RunAsAny
<17> Permission for a root file system (Default value: true)
* true: Read-only permission.
* false: Read/write permission.

. To create the resource with the data you entered, click *[Create]*.