= 레디스 클러스터 생성
:toc:
:toc-title:

본 장에서는 레디스 클러스터 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 레디스 클러스터를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[레디스]* -> *[레디스 클러스터]* 메뉴를 선택한다.
. *레디스 클러스터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 레디스 클러스터를 생성할 특정 네임스페이스를 선택한다.
. *[레디스 클러스터 생성]* 버튼을 클릭한다.
. *레디스 클러스터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 레디스 클러스터의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* TLS 
* clusterSize *
* Kubernetes Config * 
* nodeSelector
* priorityClassName
* Redis Exporter 
* Redis Follower 
* Redis Leader 
* Resources
+
----
▼ Limits
│  KEY
│  VALUE
▼ Requests
│  KEY
│  VALUE
----
* Security Context 
* Sidecars 
* Storage 
* Tolerations
+
----
effect
key
operator
tolerationSeconds
value
----

. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 레디스 클러스터를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[레디스]* -> *[레디스 클러스터]* 메뉴를 선택한다.
. *레디스 클러스터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 레디스 클러스터를 생성할 특정 네임스페이스를 선택한다.
. *[레디스 클러스터 생성]* 버튼을 클릭한다.
. *레디스 클러스터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 레디스 클러스터의 구성 정보를 작성한다. (* : 필수 설정 항목)
+
.기본 작성 예
[source,yaml]
----
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster-test <1>
  namespace: default <2>
spec:
  TLS: <3>
    ca: ca.pem
    cert: ca.crt
    key: ca.key
    secret:
      defaultMode: 1
      secretName: redis-tls-secret
  clusterSize: 3 <4>
  kubernetesConfig: <5>
    image: 'quay.io/opstree/redis:v6.2.5'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter: <6>
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisFollower: <7>
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    redisConfig: <8>
      additionalRedisConfig: redis-cluster-follower
  redisLeader: <9>
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    redisConfig: <10>
      additionalRedisConfig: redis-cluster-leader
  storage: <11>
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
----
+
<1> 레디스 클러스터의 이름 *
<2> 레디스 클러스터가 생성될 네이스페이스의 이름 *
<3> TLS 컨피그 사용 시 필요한 정보
<4> 클러스터 크기 *
<5> 레디스 버전 및 리소스 정보 *
<6> 프로메테우스(Prometheus) Exporter 생성 시 필요한 정보
<7> 레디스 팔로워의 상세 정보 *
<8> 레디스 팔로워 컨피그 맵 사용 시 필요한 정보
<9> 레디스 리더의 상세 정보 *
<10> 레디스 리더 컨피그 맵 사용 시 필요한 정보
<11> 스토리지 설정 시 필요한 정보 *
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
