= 레디스 클러스터 생성 (TD: 전체 검수 필요)
:toc:
:toc-title:

본 장에서는 레디스 클러스터 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 레디스 클러스터를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[레디스]* -> *[레디스 클러스터]* 메뉴를 선택한다.
. *레디스 클러스터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 레디스 클러스터를 생성할 특정 네임스페이스를 선택한다.
. *[레디스 클러스터 생성]* 버튼을 클릭한다.
. *레디스 클러스터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 레디스 클러스터의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* TLS +
하위 세부 항목은 xref:../form-set-item.adoc#TlsRedis["폼 에디터 설정 항목 참조"의 "Tls(Redis)"]를 참고한다.
* clusterSize *
* Kubernetes Config * +
하위 세부 항목은 xref:../form-set-item.adoc#KubernetesConfig["폼 에디터 설정 항목 참조"의 "Kubernetes Config"]를 참고한다.
* nodeSelector
* priorityClassName
* Redis Exporter +
하위 세부 항목은 xref:../form-set-item.adoc#RedisExporter["폼 에디터 설정 항목 참조"의 "Redis Exporter"]를 참고한다.
* Redis Follower +
하위 세부 항목은 xref:../form-set-item.adoc#RedisFollower/RedisLeader["폼 에디터 설정 항목 참조"의 "Redis Follower"]를 참고한다.
* Redis Leader +
하위 세부 항목은 xref:../form-set-item.adoc#RedisFollower/RedisLeader["폼 에디터 설정 항목 참조"의 "Redis Leader"]를 참고한다.
* Resources
+
----
▼ Limits
│  KEY
│  VALUE
▼ Requests
│  KEY
│  VALUE
----
* Security Context +
하위 세부 항목은 xref:../form-set-item.adoc#SecurityContextRedis["폼 에디터 설정 항목 참조"의 "Security Context(Redis)"]를 참고한다.
* Sidecars +
하위 세부 항목은 xref:../form-set-item.adoc#Sidecars["폼 에디터 설정 항목 참조"의 "Sidecars"]를 참고한다.
* Storage +
하위 세부 항목은 xref:../form-set-item.adoc#Storage["폼 에디터 설정 항목 참조"의 "Storage"]를 참고한다.
* Tolerations
+
----
effect
key
operator
tolerationSeconds
value
----

. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 레디스 클러스터를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[레디스]* -> *[레디스 클러스터]* 메뉴를 선택한다.
. *레디스 클러스터* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 레디스 클러스터를 생성할 특정 네임스페이스를 선택한다.
. *[레디스 클러스터 생성]* 버튼을 클릭한다.
. *레디스 클러스터 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 레디스 클러스터의 구성 정보를 작성한다. (TD: 기본 예제 작성 및 필수 항목에 대한 설명 작성 필요)
+
.기본 작성 예
[source,yaml]
----
(QA: 레디스 클러스터 생성 시 설정할 수 있는 옵셔널 값들 다 포함한 yaml입니다.)
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster-test <1>
  namespace: test <2>
spec:
  TLS: <3>
    ca: ca.pem
    cert: ca.crt
    key: ca.key
    secret:
      defaultMode: 1
      secretName: redis-tls-secret
  clusterSize: 3 <4>
  kubernetesConfig: <5>
    image: 'quay.io/opstree/redis:v6.2.5'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter: <6>
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisFollower: <7>
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    redisConfig: <8>
      additionalRedisConfig: redis-cluster-follower
  redisLeader: <9>
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    redisConfig: <10>
      additionalRedisConfig: redis-cluster-leader
  storage: <11>
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
----
+
(QA: 필수, 선택 옵션들을 구분해서 큰 단락에서의 설명입니다. 각 옵션별로 하나씩 설명을 쓰기에는 너무 많아질 것 같아서 어떤 옵션 사용할때 필요한 부분인지에 대해서만 썼습니다.) +
<1> 레디스 클러스터의 이름 (필수) +
<2> 레디스 클러스터가 생성될 네이스페이스의 이름 (필수) +
<3> TLS 컨피그 사용 시 필요한 정보 (선택) +
<4> 클러스터 크기 (필수) +
<5> 레디스 버전 및 리소스 정보 (필수) + 
<6> prometheus exporter 생성 시 필요한 정보 (선택) +
<7> 레디스 follower 정보 (필수) +
<8> 레디스 follwer 컨피그 맵 사용 시 필요한 정보 (선택) +
<9> 레디스 leader 정보 (필수) +
<10> 레디스 leader 컨피그 맵 사용 시 필요한 정보 (선택) +
<11> 스토리지 설정 시 필요한 정보 (필수) +
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
