= Creating Registries
:toc:
:toc-title:

The following describes how to create registry resources.

== YAML Editor

Create a new registry by using the YAML editor.

. Click *[Create Registries]* in the <<../console_menu_sub/image#img-registry-main,Registries>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a registry to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tmax.io/v1
kind: Registry
metadata:
  name: example <1>
  namespace: default <2>
spec:
  image: 'registry:2.6.2' <3>
  loginId: tmax <4>
  loginPassword: xamtsecret <5>
  service:
    serviceType: LoadBalancer <6>
    loadBalancer:
      port: 443
  persistentVolumeClaim: <7>
    create:
      accessModes:
        - ReadWriteOnce
      storageSize: 10Gi
      storageClassName: example
      volumeMode: Filesystem
      deleteWithPvc: false
----
+
<1> Registry name
<2> Name of a namespace where the registry is created
<3> Image to use to create a registry pod *(Currently, only 'registry:2.6.2' is available.)*
<4> Registry login ID
<5> Registry login password
<6> Registry's service type. Select either Ingress or LoadBalancer, and then define configuration data for each type. +
Selecting LoadBalancer must set a port number used to access a service.
<7> Registry's persistent volume claim. Select either exist or create, and then define configuration data for each type.
* pvcName: Persistent volume claim name (only for exist)
* accessMode: Persistent volume claim's access mode (only for create)
* storageSize: Persistent volume claim's storage volume (only for create)
* storageClassName: Persistent volume claim's storage class name (only for create)
* volumeMode: Volume usage mode (only for create)
* deleteWithPvc: Option to automatically delete a persistent volume claim when deleting the registry (only for create)
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new registry by using the Form editor.

. Click *[Create Registries]* in the <<../console_menu_sub/image#img-registry-main,Registries>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Registry* screen opened, enter configuration data about a registry to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name*|Registry name.
|Namespace*|Name of a namespace where the registry is created.
|Registry Creation Image*|Image to use to create a registry pod. *(Currently, only 'registry:2.6.2' is available.)*
|Login Info*|Registry login ID and password.
|Service*|Registry's service type.

* Ingress
* Load Balancer: Set a port number used to access a service.
|Persistent Volume Claim*|Registry's persistent volume claim. You can select an existing one or create one.
|Labels|Labels to add to the registry.
|====================
. To create the resource with the data you entered, click *[Create]*.
