= 컨테이너 레지스트리 생성
:toc:
:toc-title:

본 장에서는 컨테이너 레지스트리 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 컨테이너 레지스트리를 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/image#img-registry-main,컨테이너 레지스트리 메인 화면>>의 네임스페이스 선택 영역에서 새로운 컨테이너 레지스트리를 생성할 네임스페이스를 선택한 후 *[컨테이너 레지스트리 생성]* 버튼을 클릭한다.
. *Create Registry* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 컨테이너 레지스트리의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* customConfigYml
* description
* image
* loginId *
* loginPassword *
* Notary +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Notary>["폼 에디터 설정 항목 참조"의 "Notary"]를 참고한다.
* Persistent Volume Claim * +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Persistent Volume Claim>["폼 에디터 설정 항목 참조"의 "Persistent Volume Claim"]을 참고한다.
* readOnly
* Registry Deployment +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Registry Deployment>["폼 에디터 설정 항목 참조"의 "Registry Deployment"]를 참고한다.
* Service *
+
----
serviceType *
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 컨테이너 레지스트리를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/image#img-registry-main,컨테이너 레지스트리 메인 화면>>의 네임스페이스 선택 영역에서 새로운 컨테이너 레지스트리를 생성할 네임스페이스를 선택한 후 *[컨테이너 레지스트리 생성]* 버튼을 클릭한다.
. *Create Registry* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 컨테이너 레지스트리의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: tmax.io/v1
kind: Registry
metadata:
  name: example <1>
  namespace: default <2>
spec:
  image: 'registry:2.6.2' <3> //(QA: 2.6.2 -> 2.7.1 이미지 tag 변경 요청드립니다.)
  loginId: tmax <4>
  loginPassword: xamtsecret <5>
  service:
    serviceType: LoadBalancer <6>
    loadBalancer: //(QA: port 정보 없이도 사용 가능합니다.)
      port: 443
  persistentVolumeClaim: <7>
    create:
      accessModes:
        - ReadWriteOnce
      storageSize: 10Gi
      storageClassName: example
      volumeMode: Filesystem
      deleteWithPvc: false
----
+
<1> 컨테이너 레지스트리의 이름
<2> 컨테이너 레지스트리가 생성될 네임스페이스의 이름
<3> 컨테이너 레지스트리 파드 생성에 사용될 이미지 *(현재 'registry:2.6.2' 만 가능)* //(QA: hypercloud5.0 에서는 2.7.1 버전을 사용합니다.)
<4> 컨테이너 레지스트리에 로그인할 ID
<5> 컨테이너 레지스트리에 로그인할 ID의 비밀번호
<6> 컨테이너 레지스트리의 서비스 유형을 정의한다. 우선 서비스의 유형으로 Ingress, LoadBalancer 중 하나를 선택한 후 각 유형에 따른 설정 항목을 정의한다. +
이때 LoadBalancer를 선택한 경우에는 서비스에 접속하기 위한 포트 번호를 설정해야 한다. //(QA: loadbalancer 선택한 경우에도 포트번호 설정이 따로 필요 없습니다.)
<7> 컨테이너 레지스트리의 영구 볼륨 클레임을 정의한다. 우선 영구 볼륨 클레임의 유형으로 exist, create 중 하나를 선택한 후 각 유형에 따른 설정 항목을 정의한다.
* pvcName : 영구 볼륨 클레임의 이름 (exist 유형만 해당)
* accessMode : 영구 볼륨 클레임의 접근 모드 (create 유형만 해당)
* storageSize : 영구 볼륨 클레임의 스토리지 용량 (create 유형만 해당)
* storageClassName : 영구 볼륨 클레임의 스토리지 클레스 이름 (create 유형만 해당)
* volumeMode : 볼륨의 사용 모드 (create 유형만 해당)
* deleteWithPvc : 컨테이너 레지스트리 삭제 시 영구 볼륨 클레임의 자동 삭제 여부 (create 유형만 해당)
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
