= Creating Replica Sets
:toc:
:toc-title:

The following describes how to create replica set resources.

== YAML Editor

Create a new replica set by using the YAML editor.

. Click *[Create Replica Sets]* in the <<../console_menu_sub/work-load#img-replicaset-main,Replica Sets>> main screen.
. Enter configuration data about a replica set to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example <1>
  namespace: default <2>
spec: 
  replicas: 2 <3>
  selector:
    matchLabels: <4>
      app: hello-hypercloud
  template: <5>
    metadata:
      name: hello-hypercloud
      labels: <6>
        app: hello-hypercloud
    spec:
      containers: <7>
        - name: hello-hypercloud <8>
          image: hypercloud/hello-hypercloud <9>
          ports: <10>
            - containerPort: 8080 <11>
----
+
<1> Replica set name
<2> Name of a namespace where the replica set is created
<3> Number of pod replicas
<4> Label of a pod to be managed by the replica set
<5> Information about a pod to create
<6> Information about labels to use when classifying pods (Key-value format)
<7> Information about containers included in a pod
<8> Container name
<9> Container image
<10> Ports to expose to the container
<11> Port number to expose on the pod's IP address

. To create the resource with the data you entered, click *[Create]*.