= Creating Request Authentications
:toc:
:toc-title:

The following describes how to create request authentication resources.

== YAML Editor

Create a new request authentication by using the YAML editor.

. Click *[Create Request Authentications]* in the <<../console_menu_sub/service-mesh#img-request-auth-main,Request Authentications>> main screen.
. Enter configuration data about a request authentication to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: httpbin <1>
  namespace: foo
spec:
  selector: <2>
    matchLabels:
      app: httpbin
  jwtRules: <3>
  - issuer: "issuer-foo"
    jwksUri: https://example.com/.well-known/jwks.json
----
+
<1> Request authentication name
<2> Information about a workload label to apply the request authentication to
<3> JWT claims that can be validated at the specified workload. +
This is enabled only when there is a token in the location reconfigured by the rule. The token is validated based on JWT rule. If the validation fails, the request is rejected.

. To create the resource with the data you entered, click *[Create]*.