= 요청 인증 생성
:toc:
:toc-title:

본 장에서는 요청 인증 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 요청 인증을 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[요청 인증]* 메뉴를 선택한다.
. *요청 인증* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 요청 인증을 생성할 특정 네임스페이스를 선택한다.
. *[요청 인증 생성]* 버튼을 클릭한다.
. *요청 인증 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 요청 인증의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Jwt Rules 
* Selector
+
----
matchLabels
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 요청 인증을 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[요청 인증]* 메뉴를 선택한다.
. *요청 인증* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 요청 인증을 생성할 특정 네임스페이스를 선택한다.
. *[요청 인증 생성]* 버튼을 클릭한다.
. *요청 인증 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 요청 인증의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: httpbin <1>
  namespace: foo
spec:
  selector: <2>
    matchLabels:
      app: httpbin
  jwtRules: <3>
  - issuer: "issuer-foo"
    jwksUri: https://example.com/.well-known/jwks.json
----
+
<1> 요청 인증의 이름
<2> 요청 인증 방식이 적용될 워크로드의 레이블 정보
<3> 지정된 워크로드에 유효성을 검사할 수 있는 JWT 클레임 목록 
+
NOTE: 해당 규칙에 의해 재구성된 위치에 토큰이 있는 경우에만 활성화된다. 이때 토큰은 JWT 규칙을 기반으로 검증되고, 유효성 검사가 실패하면 요청이 거부된다.
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
