= Creating Resource Quotas
:toc:
:toc-title:

The following describes how to create resource quota resources.

== YAML Editor

Create a new resource quota by using the YAML editor.

. Click *[Create Resource Quotas]* in the <<../console_menu_sub/management#img-resource-quota-main,Resource Quotas>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a resource quota to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example <1>
  namespace: default <2>
spec: <3>
  hard:
    pods: '4'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
----
+
<1> Resource quota name
<2> Name of a namespace where the resource quota is created
<3> Type and volume of resources to allocate
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new resource quota by using the Form editor.

. Click *[Create Resource Quotas]* in the <<../console_menu_sub/management#img-resource-quota-main,Resource Quotas>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Resource Quota* screen opened, enter configuration data about a resource quota to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name*|Resource quota name.
|Namespace*|Name of a namespace where the resource quota is created.
|Labels|Labels to add to the resource quota.
|Namespace Resource Quota|Resource quota by resource type (such as a pod, container, and persistent volume claim) of a pod to create in a namespace. +
Click **[+ Add More]** to set a resource type and its value. Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|====================
. To create the resource with the data you entered, click *[Create]*.