= Creating Resource Quota Claims
:toc:
:toc-title:

The following describes how to create resource quota claim resources.

== YAML Editor

Create a new resource quota claim by using the YAML editor.

. Click *[Create Resource Quota Claims]* in the <<../console_menu_sub/management#img-resource-quota-claim-main,Resource Quota Claims>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a resource quota claim to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tmax.io/v1
kind: ResourceQuotaClaim
metadata:
  name: example <1>
  namespace: default <2>
  labels:
    handled: f <3>
resourceName: example-resourcequotaclaim <4>
spec:
  hard:
    limits.cpu: '1' <5>
    limits.memory: 1Gi <6>
----
+
<1> Resource quota claim name
<2> Name of a namespace where the resource quota claim is created
<3> Label used to detect creation, modification, and deletion of the claim in HyperCloud Operator *(Required)*
<4> Name of a resource quota to be created when the resource quota claim is approved
<5> Type and volume of resources to allocate
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new resource quota claim by using the Form editor.

. Click *[Create Resource Quota Claims]* in the <<../console_menu_sub/management#img-resource-quota-claim-main,Resource Quota Claims>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Resource Quota Claim* screen opened, enter configuration data about a resource quota claim to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description 
|Name*|Resource quota claim name.
|Namespace*|Name of a namespace where the resource quota claim is created.
|Labels|Labels to add to the resource quota claim.
|Resource Name*|Name of the namespace to be created when the resource quota claim is approved.
|Namespace Resource Quota*|Type and volume of resources used in the namespace. When the resource quota claim is approved, a resource quota is created with the resource name.

* CPU Limits: Limit of CPU resource to use
* Memory Limits: Limit of memory resource to use

To add other types of resources besides CPU Limits and Memory Limits, click **[+ Add More]**. Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|====================
. To create the resource with the data you entered, click *[Create]*.