= 리소스 쿼타 클레임 생성
:toc:
:toc-title:

본 장에서는 리소스 쿼타 클레임 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 리소스 쿼타 클레임을 폼 에디터를 사용해서 생성할 수 있다.

. 리소스 쿼타 메인 화면에서 *[리소스 쿼타 클레임]* 탭을 선택한다.
. <<../console_menu_sub/management#img-resource-quota-claim-main,[리소스 쿼타 클레임] 탭 화면>>이 열리면 *[리소스 쿼타 클레임 생성]* 버튼을 클릭한다.
. *Create ResourceQuotaClaim* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 리소스 쿼타 클레임의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Hard *
+
----
KEY
VALUE
----
* resourceName *
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 리소스 쿼타 클레임을 YAML 에디터를 사용해서 생성할 수 있다.

. 리소스 쿼타 메인 화면에서 *[리소스 쿼타 클레임]* 탭을 선택한다.
. <<../console_menu_sub/management#img-resource-quota-claim-main,[리소스 쿼타 클레임] 탭 화면>>이 열리면 *[리소스 쿼타 클레임 생성]* 버튼을 클릭한다.
. *Create ResourceQuotaClaim* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 리소스 쿼타 클레임의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: tmax.io/v1
kind: ResourceQuotaClaim
metadata:
  name: example <1>
  namespace: default <2>
  labels:
    handled: f <3>
resourceName: example-resourcequotaclaim <4>
spec:
  hard:
    limits.cpu: '1' <5>
    limits.memory: 1Gi <6>
----
+
<1> 리소스 쿼타 클레임의 이름
<2> 리소스 쿼타 클레임이 생성될 네임스페이스의 이름
<3> HyperCloud Operator에서 클레임의 생성, 변경, 삭제를 감지하기 위한 레이블 정보 *(반드시 포함해야 함)*
<4> 리소스 쿼타 클레임이 허가되면 생성될 리소스 쿼타의 이름
<5> 할당할 리소스의 종류 및 양
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
