= 리소스 쿼타 클레임 생성
:toc:
:toc-title:

본 장에서는 리소스 쿼타 클레임 리소스의 생성 방법에 대해서 설명한다.

== YAML 에디터

새로운 리소스 쿼타 클레임을 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/management#img-resource-quota-claim-main,리소스 쿼타 클레임 메인 화면>>에서 *[리소스 쿼타 클레임 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[Yaml 에디터]**를 클릭한다. 
. YAML 에디터 화면이 열리면 생성할 리소스 쿼타 클레임의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: tmax.io/v1
kind: ResourceQuotaClaim
metadata:
  name: example <1>
  namespace: default <2>
  labels:
    handled: f <3>
resourceName: example-resourcequotaclaim <4>
spec:
  hard:
    limits.cpu: '1' <5>
    limits.memory: 1Gi <6>
----
+
<1> 리소스 쿼타 클레임의 이름
<2> 리소스 쿼타 클레임이 생성될 네임스페이스의 이름
<3> HyperCloud Operator에서 클레임의 생성, 변경, 삭제를 감지하기 위한 레이블 정보 *(반드시 포함해야 함)*
<4> 리소스 쿼타 클레임이 허가되면 생성될 리소스 쿼타의 이름
<5> 할당할 리소스의 종류 및 양
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

== 폼 에디터

새로운 리소스 쿼타 클레임을 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/management#img-resource-quota-claim-main,리소스 쿼타 클레임 메인 화면>>에서 *[리소스 쿼타 클레임 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[폼 에디터]**를 클릭한다.
. *리소스 쿼타 클레임 생성* 화면이 열리면 생성할 리소스 쿼타 클레임의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다. (* : 필수 입력 항목)
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명  
|이름 *|리소스 쿼타 클레임의 이름을 입력한다.
|네임스페이스 *|리소스 쿼타 클레임이 생성될 네임스페이스의 이름을 선택한다.
|레이블|리소스 쿼타 클레임에 추가할 레이블 정보를 입력한다.
|리소스 이름 *|리소스 쿼타 클레임이 허가되면 생성될 리소스 쿼타의 이름을 입력한다.
|네임스페이스 리소스 쿼타 *|네임스페이스에서 사용할 자원의 양을 설정한다. 리소스 쿼타 클레임이 승인되면 설정한 리소스 이름으로 리소스 쿼타가 생성된다.

* CPU Limits : 사용할 CPU 자원의 제한값
* Memory Limits : 사용할 메모리 자원의 제한값

만약 CPU Limits, Memory Limits 타입 외 자원의 할당량을 추가하려면 **[+ 추가]**를 클릭한다. 이때 **[+ 추가]**를 클릭하면 입력 항목이 하나씩 추가되고, *[-]* 버튼을 클릭하면 입력 항목을 삭제할 수 있다.
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.