= Creating Role Binding Claims
:toc:
:toc-title:

The following describes how to create role binding claim resources.

== YAML Editor

Create a new role binding claim by using the YAML editor.

. Click *[Create Role Binding Claims]* in the <<../console_menu_sub/permission#img-role-binding-claim-main,Role Binding Claims>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a role binding claim to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tmax.io/v1
kind: RoleBindingClaim
metadata:
  name: example-role-biniding <1>
  namespace: default <2>
resourceName: example-claim <3>
subjects:
  - kind: User <4>
    name: example@tmax.co.kr <5>
roleRef:
  kind: ClusterRole <6>
  name: namespace-user <7>
  apiGroup: rbac.authorization.k8s.io <8>
----
+
<1> Role binding claim name
<2> Name of a namespace where the role binding claim is created (Don not set for a cluster role)
<3> Name of a role binding to be created when the role binding claim is approved
<4> Type of a user to bind to a role (User, Group, or Service Account)
<5> Name of a user to bind to a role
<6> Type of a role to allocate to a user
<7> Name of a role to allocate to a user
<8> API permission required to approve the role binding claim
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new role binding claim by using the Form editor.

. Click *[Create Role Binding Claims]* in the <<../console_menu_sub/permission#img-role-binding-claim-main,Role Binding Claims>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Role Binding Claims* screen opened, enter configuration data about a role binding claim to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name|Role binding claim name.
|Resource Name|Name of a role binding to be created when the role binding claim is approved.
|Role|Name of a role to allocate to a user.
|Subject|Type of a user to bind to a role.

* User
* Group
* Service Account
|Subject Name|User name.
|====================
. To create the resource with the data you entered, click *[Create]*.