= Creating Role Bindings
:toc:
:toc-title:

The following describes how to create role binding resources.

== Form Editor

Create a new role binding by using the Form editor.

. Click *[Role Bindings]* in the <<../console_menu_sub/permission#img-role-binding-main,Role Bindings>> main screen.
. In the *Create Role Bindings* screen opened, enter configuration data about a role binding to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Type|Role binding type.

* Namespace Role Binding (RoleBinding): Binds a namespace role and user
* Cluster-wide Role Binding (ClusterRoleBinding): Binds a cluster role and user
|Role Binding|Basic information about the role binding.

* Name: Role binding name.
* Namespace: Namespace where the role binding is created. Enabled only when **"Namespace Role Binding (RoleBinding)"** is set.
|Role|Name of a role to allocate to a user.
|Subject|Basic information about a user to bind to a role.

* Type: One of the following user types: User, Group, and Service Account.
* Subject Name: User name.
|====================
. To create the resource with the data you entered, click *[Create]*.