= Creating Roles
:toc:
:toc-title:

The following describes how to create role resources.

== YAML Editor

Create a new role by using the YAML editor.

. Click *[Create Roles]* in the <<../console_menu_sub/permission#img-role-main,Roles>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a role to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example <1>
  namespace: default <2>
rules:
  - apiGroups: <3>
      - ''
    resources: <4>
      - pods
    verbs: <5>
      - get
      - watch
      - list
----
+
<1> Role name
<2> Name of a namespace where the role is created (Do not set for a cluster role.)
<3> Type of an API group including a resource to control
<4> Name of a resource to control
<5> Actions available for a resource to control
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new role by using the Form editor.

. Click *[Create Roles]* in the <<../console_menu_sub/permission#img-role-main,Roles>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Roles* screen opened, enter configuration data about a role to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Role Type|Range to apply the role.

* Namespace Role: Apply the role to the namespace.
* Cluster Role: Apply the role to all namespaces.
|Name*|Role name.
|Namespace*|Name of a namespace where the role is created.
|Grant Resources*|Name of a resource to control and actions available for the resource. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.
|====================
. To create the resource with the data you entered, click *[Create]*.