= Creating Secrets
:toc:
:toc-title:

The following describes how to create secret resources.

== YAML Editor

Create a new secret by using the YAML editor.

. Click *[Create Secrets]* in the <<../console_menu_sub/work-load#img-secret-main,Secrets>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a secret to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: example-secret <1>
  namespace: default <2>
type: Opaque
stringData: <3>
  (key): (value)
  id: tmax-admin
  password: admin-pw
----
+
<1> Secret name
<2> Name of a namespace where the secret is created
<3> Authentication data (Key-value format)

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

=== Source Secret

Create a source secret that uses basic authentication (user name and password) and SSH key data that are encoded with Base64 for authentication.

. Click *[Create Secrets]* in the <<../console_menu_sub/work-load#img-secret-main,Secrets>> main screen.
. Select **[Form Editor(Source)]** from the drop down menu.
. In the *Create Secrets* screen opened, enter configuration data about a source secret to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description
|Name|Source secret name.
|Authentication Type|Data type used for authentication.

* Basic Authentication: Encode user names and passwords with Base64.
* SSH Key: Encode SSH keys with Base64.
|Username|User name to use for authentication. (Enabled only when Authentication Type is set to **"Basic Authentication"**)
|Password or Token|Password to use for authentication. (Enabled only when Authentication Type is set to **"Basic Authentication"**)
|SSH Private Key|Private SSH key file. (Enabled only when Authentication Type is set to **"SSH Key"**) +
Clicking *[Browse...]* opens the *Open* dialog box where you can select a SSH key file.
|====================

. To create the resource with the data you entered, click *[Create]*.

=== Webhook Secret

Create a webhook secret to call a webhook that requests that an application has been run in POST method.

. Click *[Create Secrets]* in the <<../console_menu_sub/work-load#img-secret-main,Secrets>> main screen.
. Select **[Form Editor(Webhook)]** from the drop down menu.
. In the *Create Secrets* screen opened, enter configuration data about a webhook secret to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description  
|Name|Webhook secret name.
|Webhook Secret Key|Secret key used to call webhook. Clicking *[Generate]* generates a random secret key.
|====================

. To create the resource with the data you entered, click *[Create]*.