= 시크릿 생성
:toc:
:toc-title:

본 장에서는 시크릿 리소스의 생성 방법에 대해서 설명한다.

== YAML 에디터

새로운 시크릿을 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/work-load#img-secret-main,시크릿 메인 화면>>에서 *[시크릿 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[Yaml 에디터]**를 클릭한다.
. YAML 에디터 화면이 열리면 생성할 시크릿의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: example-secret <1>
  namespace: default <2>
type: Opaque
stringData: <3>
  (key): (value)
  id: tmax-admin
  password: admin-pw
----
+
<1> 시크릿의 이름
<2> 시크릿이 생성될 네임스페이스의 이름
<3> 인증 정보 (Key-Value 형식)
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

== 폼 에디터

=== 소스 시크릿

Base64로 인코딩한 기본 인증(사용자 이름, 패스워드) 및 SSH 키 데이터를 인증에 사용하는 소스 시크릿을 생성할 수 있다.

. <<../console_menu_sub/work-load#img-secret-main,시크릿 메인 화면>>에서 *[시크릿 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[폼 에디터 (원본)]**를 클릭한다.
. *시크릿 생성* 화면이 열리면 생성할 소스 시크릿의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명  
|이름|소스 시크릿의 이름을 입력한다.
|인증 유형|인증에 사용할 데이터 유형을 선택한다.

* 기본 인증 : 사용자 이름, 패스워드를 Base64로 인코딩
* SSH 키 : SSH 키를 Base64로 인코딩
|사용자 이름|인증에 사용할 사용자의 이름을 입력한다. (단, 인증 유형을 **"기본 인증"**으로 선택한 경우에만 활성화)
|비밀번호 혹은 토큰|인증에 사용할 사용자의 비밀번호를 입력한다. (단, 인증 유형을 **"기본 인증"**으로 선택한 경우에만 활성화)
|SSH 개인키|개인 SSH 키 파일을 업로드한다. (단, 인증 유형을 **"SSH 키"**로 선택한 경우에만 활성화) +
이때 *[검색]* 버튼을 클릭해서 *열기* 팝업이 열리면 사용할 SSH 키 파일을 선택한다.
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

=== 웹후크 시크릿

애플리케이션 작업이 수행되었음을 POST 방식으로 요청하는 웹후크를 호출하기 위한 웹후크 시크릿을 생성할 수 있다.

. <<../console_menu_sub/work-load#img-secret-main,시크릿 메인 화면>>에서 *[시크릿 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[폼 에디터 (웹후크)]**를 클릭한다.
. *시크릿 생성* 화면이 열리면 생성할 웹후크 시크릿의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명  
|이름|웹후크 시크릿의 이름을 입력한다.
|웹훅 시크릿 키|웹후크를 호출하기 위한 비밀키를 생성한다. 이때 *[생성]* 버튼을 클릭해서 랜덤 비밀키를 생성한다.
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.