= Creating Services
:toc:
:toc-title:

The following describes how to create service resources.

== YAML Editor

Create a new service by using the YAML editor.

. Click *[Create Services]* in the <<../console_menu_sub/network#img-service-main,Services>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a service to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: example <1>
  namespace: default <2>
spec:
  selector: <3>
      app: MyApp
    ports: 
    - protocol: TCP <4>
    port: 80 <5>
    targetPort: 9376 <6>
----
+
<1> Service name
<2> Name of a namespace where the service is created
<3> Label of a pod to be managed by the service (Key-value format)
<4> Protocol to be used by the service
* TCP
* UDP
<5> Port to be used by the service
<6> Port of a pod to be forwarded by the service

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new service by using the Form editor.

. Click *[Create Services]* in the <<../console_menu_sub/network#img-service-main,Services>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Services* screen opened, enter configuration data about a service to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description    
|Name|Service name.
|Port|Service port information. +
Clicking **[+ Add More]** adds a new input field, and clicking *[-]* deletes the input field.

* Name: Port name.
* Port: Port number used to connect to the service.
* Protocol: Protocol type for communication (TCP, UDP, or SCDP)
* Target Port: Port number used to connect to a container
|Type|Service type.

* Cluster IP: Only accessible from inside a cluster.
* LoadBalancer: Accessible through an external load balancer.
* Node Port: Accessible from inside and outside a cluster.
|Selector|Information about a pod label to be managed by the service.

* Key: Label property key.
* Value: Label property value.
|Labels|Information about labels to add to the service.
|====================

. To create the resource with the data you entered, click *[Create]*.