= 서비스 바인딩 생성
:toc:
:toc-title:

본 장에서는 서비스 바인딩 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 서비스 바인딩을 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/service-catalog#img-service-binding-main,서비스 바인딩 메인 화면>>의 네임스페이스 선택 영역에서 새로운 서비스 바인딩을 생성할 네임스페이스를 선택한 후 *[서비스 바인딩 생성]* 버튼을 클릭한다.
. *Create Service Binding* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 서비스 바인딩의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다. (* : 필수 입력 항목)

* Name *
+
서비스 바인딩의 이름을 입력한다.
* Labels 
+
서비스 바인딩에 추가할 레이블 정보를 입력한다.
* Instance Ref *
+
하위 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|name|
|====================
* Parameters
+
하위 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|Key|
|Value|
|====================
* Parameters From
+
하위 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|Secret Key Ref|
* key * :
* name * :
|====================
* secretName
* Secret Transforms
+
하위 설정 항목에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|Add Key|
* jsonPathExpression :
* key * :
* stringValue * :
* value :
|Add Keys From|
* Secret Ref :
** name :
** namespace : 
|Remove Key|
* key * :
|Rename Key|
* from * :
* to * :
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 서비스 바인딩을 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/service-catalog#img-service-binding-main,서비스 바인딩 메인 화면>>의 네임스페이스 선택 영역에서 새로운 서비스 바인딩을 생성할 네임스페이스를 선택한 후 *[서비스 바인딩 생성]* 버튼을 클릭한다.
. *Create Service Binding* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 서비스 바인딩의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: nginx-binding <1>
  namespace: hypercloud-system <2>
spec:
  instanceRef: <3>
    name: nginx-instance
----
+
<1> 서비스 바인딩의 이름
<2> 서비스 바인딩이 생성될 네임스페이스의 이름
<3> 서비스 바인딩이 참조하는 서비스 인스턴스의 이름

. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.