= 서비스 생성
:toc:
:toc-title:

본 장에서는 서비스 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 서비스를 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/network#img-service-main,서비스 메인 화면>>의 네임스페이스 선택 영역에서 새로운 서비스를 생성할 네임스페이스를 선택한 후 *[서비스 생성]* 버튼을 클릭한다.
. *Create Service* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 서비스의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* clusterIP
* External I Ps
+
----
Value
----
* externalName
* externalTrafficPolicy
* healthCheckNodePort
* loadBalancerIP
* Load Balancer Source Ranges
+
----
Value
----
* Ports *
+
----
name
nodePort
port *
protocol
targetPort
----
* publishNotReadyAddresses
* selector
* sessionAffinity
* Session Affinity Config +
하위 세부 항목은 xref:../form_set_item/form-set-item.adoc#<Session Affinity Config>["폼 에디터 설정 항목 참조"의 "Session Affinity Config"]를 참고한다.
* type
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.


== YAML 에디터

새로운 서비스를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/network#img-service-main,서비스 메인 화면>>의 네임스페이스 선택 영역에서 새로운 서비스를 생성할 네임스페이스를 선택한 후 *[서비스 생성]* 버튼을 클릭한다.
. *Create Service* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 서비스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: example <1>
  namespace: default <2>
spec:
  selector: <3>
      app: MyApp
    ports: 
    - protocol: TCP <4>
    port: 80 <5>
    targetPort: 9376 <6>
----
+
<1> 서비스의 이름
<2> 서비스가 생성될 네임스페이스의 이름
<3> 서비스가 관리할 파드의 레이블 정보 (키:값)
<4> 서비스가 사용할 프로토콜
* TCP
* UDP
<5> 서비스가 사용할 포트
<6> 서비스가 포워드할 파드의 포트
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.