= 서비스 브로커 생성
:toc:
:toc-title:

본 장에서는 서비스 브로커 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 서비스 브로커를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 카탈로그]* -> *[서비스 브로커]* 메뉴를 선택한다.
. *서비스 브로커* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 서비스 브로커를 생성할 특정 네임스페이스를 선택한다.
. *[서비스 브로커 생성]* 버튼을 클릭한다.
. *Create Service Broker* 화면이 열리면 **Configure via**를 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 서비스 브로커의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Auth Info +
하위 세부 항목은 xref:../form-set-item.adoc#<Auth Info(Service Broker)>["폼 에디터 설정 항목 참조"의 "Auth Info(Service Broker)"]를 참고한다.
* caBundle
* Catalog Restrictions +
하위 세부 항목은 xref:../form-set-item.adoc#<Catalog Restrictions>["폼 에디터 설정 항목 참조"의 "Catalog Restrictions"]를 참고한다.
* insecureSkipTLSVerify
* relistBehavior
* relistDuration
* relistRequests
* url *
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 서비스 브로커를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 카탈로그]* -> *[서비스 브로커]* 메뉴를 선택한다.
. *서비스 브로커* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 서비스 브로커를 생성할 특정 네임스페이스를 선택한다.
. *[서비스 브로커 생성]* 버튼을 클릭한다.
. *Create Service Broker* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다. +
. YAML 에디터가 열리면 생성할 서비스 브로커의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBroker
metadata:
  name: hyperbroker5 <1>
  namespace: default <2>
spec:
  url: http://192.168.6.159:2867 <3>
----
+
<1> 서비스 브로커의 이름
<2> 서비스 브로커가 생성될 네임스페이스의 이름
<3> 서비스 브로커 서버의 서비스 URL
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.