= 서비스 바인딩 생성
:toc:
:toc-title:

본 장에서는 서비스 바인딩 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 서비스 바인딩을 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 카탈로그]* -> *[서비스 바인딩]* 메뉴를 선택한다.
. *서비스 바인딩* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 서비스 바인딩을 생성할 특정 네임스페이스를 선택한다.
. *[서비스 바인딩 생성]* 버튼을 클릭한다.
. *서비스 바인딩 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 서비스 바인딩의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Instance Ref *
+
----
name
----
* Parameters
+
----
KEY
VALUE
----
* Parameters From +
하위 세부 항목은 xref:../form-set-item.adoc#ParametersFrom["폼 에디터 설정 항목 참조"의 "Parameters From"]을 참고한다.
* secretName
* Secret Transforms +
하위 세부 항목은 xref:../form-set-item.adoc#SecretTransforms["폼 에디터 설정 항목 참조"의 "Secret Transforms"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 서비스 바인딩을 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 카탈로그]* -> *[서비스 바인딩]* 메뉴를 선택한다.
. *서비스 바인딩* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 서비스 바인딩을 생성할 특정 네임스페이스를 선택한다.
. *[서비스 바인딩 생성]* 버튼을 클릭한다.
. *서비스 바인딩 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 서비스 바인딩의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: nginx-binding <1>
  namespace: hypercloud-system <2>
spec:
  instanceRef: <3>
    name: nginx-instance
----
+
<1> 서비스 바인딩의 이름
<2> 서비스 바인딩이 생성될 네임스페이스의 이름
<3> 서비스 바인딩이 참조하는 서비스 인스턴스의 이름
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.