= Creating Service Accounts
:toc:
:toc-title:

The following describes how to create service account resources.

== YAML Editor

Create a new service account by using the YAML editor.

. Click *[Create Service Accounts]* in the <<../console_menu_sub/permission#img-service-account-main,Service Accounts>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a service account to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example <1>
  namespace: default <2>
----
+
<1> Service account name
<2> Name of a namespace where the service account is created
. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new service account by using the Form editor.

. Click *[Create Service Accounts]* in the <<../console_menu_sub/permission#img-service-account-main,Service Accounts>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Service Accounts* screen opened, enter configuration data about a service account to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description
|Name*|Service account name.
|Namespace*|Name of a namespace where the service account is created.
|====================
. To create the resource with the data you entered, click *[Create]*.