= 사이드카 생성
:toc:
:toc-title:

본 장에서는 사이드카 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 사이드카를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[사이드카]* 메뉴를 선택한다.
. *사이드카* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 사이드카를 생성할 특정 네임스페이스를 선택한다.
. *[사이드카 생성]* 버튼을 클릭한다.
. *사이드카 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 사이드카의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Egress
+
----
bind
captureMode
▼ Hosts
│  Value *
▼ Port
│  name
│  number
│  protocol
----
* Ingress
+
----
bind
captureMode
defaultEndpoint
▼ Port
│  name
│  number
│  protocol
----
* Outbound Traffic Policy
+
----
mode
----
* Workload Selector
+
----
labels
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 사이드카를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[사이드카]* 메뉴를 선택한다.
. *사이드카* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 사이드카를 생성할 특정 네임스페이스를 선택한다.
. *[사이드카 생성]* 버튼을 클릭한다.
. *사이드카 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 사이드카의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: no-ip-tables <1>
  namespace: bookinfo
spec:
  workloadSelector: <2>
    labels:
      app: productpage
  ingress: <3>
  - port:
      number: 9080
      protocol: HTTP
      name: somename
    defaultEndpoint: 127.0.0.1:8080
    captureMode: NONE
  egress: <4>
  - port:
      number: 3306
      protocol: MYSQL
      name: egressmysql
    captureMode: NONE
    bind: 127.0.0.1
    hosts:
    - "*/mysql.foo.com"
----
+
<1> 사이드카의 이름
<2> 사이드카 구성을 적용할 특정 파드 집합의 선택 기준 (만약 생략할 경우 동일 네임스페이스의 모든 워크로드 인스턴스에 구성이 적용)
<3> 연결된 워크로드 인스턴스에 대해 인바운드 트래픽을 처리하기 위한 사이드카의 구성 정보
<4> 연결된 워크로드 인스턴스에서 메시 내 다른 서비스로의 아웃바운드 트래픽을 처리하기 위한 사이드카의 구성 정보
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.