= Creating Stateful Sets
:toc:
:toc-title:

The following describes how to create stateful set resources.

== YAML Editor

Create a new stateful set by using the YAML editor.

. Click *[Create Stateful Sets]* in the <<../console_menu_sub/work-load#img-statefulset-main,Stateful Sets>> main screen.
. Enter configuration data about a stateful set to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: example <1>
  namespace: default <2>
spec: 
  serviceName: nginx <3> 
  replicas: 3 <4>  
  selector:
    matchLabels: <5>
      app: nginx
  template: <6>
    metadata:
      labels: <7>
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10 <8>
      containers: <9>
        - name: nginx <10>
          image: 'gcr.io/google_containers/nginx-slim:0.8' <11>
          ports: <12>
            - containerPort: 80 <13>
              name: web <14>
          volumeMounts: <15>
            - name: www <16>
              mountPath: /usr/share/nginx/html <17>
  volumeClaimTemplates: <18>
    - metadata:
        name: www <19>
      spec:
        accessModes: <20>
          - ReadWriteOnce
        storageClassName: my-storage-class <21>
        resources:
          requests: <22>
            storage: 1Gi <23>
----
+
<1> Stateful set name
<2> Name of a namespace where the stateful set is created
<3> Name of a service managing the stateful set
<4> Number of pod replicas
<5> Label of a pod to be managed by the stateful set
<6> Information about a pod to create
<7> Information about labels to use when classifying pods (Key-value format)
<8> Grace period to terminate a pod (Unit: seconds)
<9> Information about containers included in a pod
<10> Container name
<11> Container image
<12> Ports to expose to the container
<13> Port number to expose on the pod's IP address
<14> Port name
<15> Volumes to mount to a container's file system
<16> Volume name
<17> Path of a container where a volume is mounted
<18> Information about a persistent volume claim to create
<19> Persistent volume claim name
<20> Volume's access mode
<21> Storage class name
<22> Minimum resources required for volumes
<23> Storage resources required for volumes

. To create the resource with the data you entered, click *[Create]*.