= 스테이트풀 셋 생성
:toc:
:toc-title:

본 장에서는 스테이트풀 셋 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 스테이트풀 셋을 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[스테이트풀 셋]* 메뉴를 선택한다.
. *스테이트풀 셋* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 스테이트풀 셋을 생성할 특정 네임스페이스를 선택한다.
. *[스테이트풀 셋 생성]* 버튼을 클릭한다.
. *스테이트풀 셋 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 스테이트풀 셋의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* podManagementPolicy
* replicas
* revisionHistoryLimit
* Selector * +
하위 세부 항목은 xref:../form-set-item.adoc#Selector["폼 에디터 설정 항목 참조"의 "Selector"]를 참고한다.
* serviceName *
* Template * +
하위 세부 항목은 xref:../form-set-item.adoc#Template["폼 에디터 설정 항목 참조"의 "Template"]을 참고한다.
* Update Strategy +
하위 세부 항목은 xref:../form-set-item.adoc#UpdateStrategy(StatefulSet)["폼 에디터 설정 항목 참조"의 "Update Strategy(StatefulSet)"]을 참고한다.
* Volume Claim Templates +
하위 세부 항목은 xref:../form-set-item.adoc#VolumeClaimTemplates["폼 에디터 설정 항목 참조"의 "Volume Claim Templates"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 스테이트풀 셋을 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[워크로드]* -> *[스테이트풀 셋]* 메뉴를 선택한다.
. *스테이트풀 셋* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 스테이트풀 셋을 생성할 특정 네임스페이스를 선택한다.
. *[스테이트풀 셋 생성]* 버튼을 클릭한다.
. *스테이트풀 셋 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 스테이트풀 셋의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: example <1>
  namespace: default <2>
spec: 
  serviceName: nginx <3> 
  replicas: 3 <4>  
  selector:
    matchLabels: <5>
      app: nginx
  template: <6>
    metadata:
      labels: <7>
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10 <8>
      containers: <9>
        - name: nginx <10>
          image: 'gcr.io/google_containers/nginx-slim:0.8' <11>
          resources: <12>
            limits: <13>
              memory: 200Mi
              cpu: 1
            requests: <14>
              memory: 100Mi
              cpu: 0.5           
          ports: <15>
            - containerPort: 80 <16>
              name: web <17>
          volumeMounts: <18>
            - name: www <19>
              mountPath: /usr/share/nginx/html <20>
  volumeClaimTemplates: <21>
    - metadata:
        name: www <22>
      spec:
        accessModes: <23>
          - ReadWriteOnce
        storageClassName: my-storage-class <24>
        resources:
          requests: <25>
            storage: 1Gi <26>
----
+
<1> 스테이트풀 셋의 이름
<2> 스테이트풀 셋이 생성될 네임스페이스의 이름
<3> 스테이트풀 셋을 관리하는 서비스의 이름
<4> 파드 복제본의 개수
<5> 스테이트풀 셋이 관리할 파드의 레이블 정보
<6> 생성할 파드에 대한 상세 명세
<7> 파드를 분류할 때 사용할 레이블 정보 (키-값 형식)
<8> 파드가 Gracefully 종료되기 위해 필요한 시간 (단위: 초)
<9> 파드를 구성할 컨테이너의 상세 내역
<10> 컨테이너의 이름
<11> 컨테이너의 이미지
<12> 컨테이너에 할당할 리소스의 종류 및 양 +
다음과 같은 조건에서 스테이트풀 셋을 생성할 경우 반드시 설정 필요 +
* 네임스페이스 클레임을 통해 생성된 네임스페이스
* 리소스 쿼타가 설정된 네임스페이스 +
<13> 컨테이너가 최대로 사용할 수 있는 리소스의 양
<14> 컨테이너가 생성될 때 요청할 리소스의 양
<15> 컨테이너에서 노출할 포트 목록
<16> 파드의 IP 주소에서 노출할 포트 번호
<17> 포트의 이름
<18> 컨테이너의 파일 시스템에 마운트할 볼륨 목록
<19> 볼륨의 이름
<20> 볼륨이 마운트될 컨테이너 내부 경로
<21> 생성할 영구 볼륨 클레임의 상세 내역
<22> 영구 볼륨 클레임의 이름
<23> 볼륨의 접근 모드
<24> 스토리지 클래스의 이름
<25> 볼륨에 필요한 최소 자원에 대한 상세 내역
<26> 볼륨에 필요한 스토리지 자원의 양
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.