= 스토리지 클래스 생성
:toc:
:toc-title:

본 장에서는 스토리지 클래스 리소스의 생성 방법에 대해서 설명한다.

== YAML 에디터

=== 블록 스토리지 클래스

새로운 블록 스토리지 클래스를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/storage#img-storage-class-main,스토리지 클래스 메인 화면>>에서 *[스토리지 클래스 생성]* 버튼을 클릭한다.
. YAML 에디터 화면이 열리면 생성할 블록 스토리지 클래스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block <1>
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph <2>
  pool: replicapool <3>
  imageFormat: "2" <4>
  imageFeatures: layering <5>
    
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner <6>
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph <2>
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner <6>
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph <2>
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node <6>
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph <2>
  csi.storage.k8s.io/fstype: ext4 <7>
    
#mounter: rbd-nbd <8>
allowVolumeExpansion: true <9>    
reclaimPolicy: Delete <10> 
----
+
<1> 스토리지 클래스의 이름
<2> Rook Ceph 클러스터가 설치된 네임스페이스의 이름 (기본값: rook-ceph) +
만약 기본값을 변경할 경우 secret의 네임스페이스도 변경 필요
<3> Ceph pool의 이름 (기본값: replicapool)
<4> RBD 이미지의 포맷 (기본값: 2) +
이미지 포맷을 1로 설정할 경우 deprecated되어 볼륨 cloning 등의 기능들은 사용할 수 없음
<5> RBD 이미지의 특성 (기본값: layering) +
현재 striping, exclusive-lock, object-map, fast-diff, deep-flatten, journaling 등은 미지원
<6> 오퍼레이터에 의해 생성된 Ceph 관리자의 secret (고정값)
<7> 스토리지의 파일 시스템 타입 (기본값: ext4)
<8> 볼륨을 마운트할 때 rbd-nbd 모듈의 사용 여부 (기본값: 미사용)
<9> 볼륨 크기 확장 기능의 지원 여부 (기본값: true)
<10> 사용이 끝난 영구 볼륨의 처리 방식 (기본값: Delete)
* Retain : 볼륨을 삭제하지 않고, 데이터를 보존
* Delete : 볼륨을 삭제
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

=== 파일 스토리지 클래스

새로운 파일 스토리지 클래스를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/storage#img-storage-class-main,스토리지 클래스 메인 화면>>에서 *[스토리지 클래스 생성]* 버튼을 클릭한다.
. YAML 에디터 화면이 열리면 생성할 파일 스토리지 클래스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephfs-sc <1>
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph <2>
  fsName: myfs <3>
  pool: myfs-data0 <4>
    
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner <5>
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph <2>
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner <5>
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph <2>
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node <5>
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph <2>
    # mounter: kernel <6>
    
reclaimPolicy: Delete <7>
allowVolumeExpansion: true <8>    
mountOptions:
  #- debug <9>
----
+
<1> 스토리지 클래스의 이름
<2> Rook Ceph 클러스터가 설치된 네임스페이스의 이름 (기본값: rook-ceph) +
만약 기본값을 변경할 경우 secret의 네임스페이스도 변경 필요
<3> CephFS의 파일 시스템 이름 (기본값: myfs)
<4> Ceph pool의 이름 (기본값: myfs-data0)
<5> 오퍼레이터에 의해 생성된 Ceph 관리자의 secret (고정값)
<6> 볼륨을 마운트할 때 사용할 모듈 (기본값: 미사용) +
만약 해당 필드값을 작성하지 않으면 기본 volume mounter를 드라이버가 판단함
* fuse : ceph-fuse
* kernel : ceph kernelclient
<7> 사용이 끝난 영구 볼륨의 처리 방식 (기본값: Delete)
* Retain : 볼륨을 삭제하지 않고, 데이터를 보존
* Delete : 볼륨을 삭제
<8> 볼륨 크기 확장 기능의 지원 여부 (기본값: true)
<9> 마운트할 때 디버깅의 가능 여부 (기본값: 미사용)
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
새로운 서비스를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/network#img-service-main,서비스 메인 화면>>에서 *[서비스 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[Yaml 에디터]**를 클릭한다.
. YAML 에디터 화면이 열리면 생성할 서비스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example <1>
  namespace: default <2>
spec:
  selector:
      app: MyApp <3>
    ports: 
    - protocol: TCP <4>
    port: 80 <5>
    targetPort: 9376 <6>
----
+
<1> 서비스의 이름
<2> 서비스가 생성될 네임스페이스의 이름
<3> 서비스가 관리할 파드의 레이블 정보
<4> 서비스가 사용할 프로토콜
* TCP
* UDP
<5> 서비스가 사용할 포트
<6> 서비스가 포워드할 파드의 포트
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.