= 스토리지 클래스 생성
:toc:
:toc-title:

본 장에서는 스토리지 클래스 리소스의 생성 방법에 대해서 설명한다. 

CAUTION: Ceph 스토리지 클래스를 생성하기 전 반드시 쿠버네티스 환경에서 Ceph 스토리지가 연동된 상태여야 한다.

== 폼 에디터

새로운 스토리지 클래스를 폼 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[스토리지]* -> *[스토리지 클래스]* 메뉴를 선택한다.
. *스토리지 클래스* 메인 화면이 열리면 *[스토리지 클래스 생성]* 버튼을 클릭한다.
. *스토리지 클래스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 스토리지 클래스의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* allowVolumeExpansion
* Allowed Topologies +
하위 세부 항목은 xref:../form-set-item.adoc#AllowedTopologies["폼 에디터 설정 항목 참조"의 "Allowed Topologies"]를 참고한다.
* Mount Options
+
----
Value
----
* Parameters
+
----
KEY
VALUE
----
* provisioner *
* reclaimPolicy
* volumeBindingMode
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

=== NFS 스토리지 클래스 

새로운 NFS 스토리지 클래스를 YAML 에디터를 사용해서 생성할 수 있다.

. "마스터 클러스터" 콘솔 메뉴에서 *[스토리지]* -> *[스토리지 클래스]* 메뉴를 선택한다.
. *스토리지 클래스* 메인 화면이 열리면 *[스토리지 클래스 생성]* 버튼을 클릭한다.
. *Create Storage Class* 화면이 열리면 **Configure via**를 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 스토리지 클래스의 구성 정보를 설정한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs <1>
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  onDelete: delete <2>
  pathPattern: "${.PVC.namespace}/${.PVC.name}" <3>
----
+
<1> 스토리지 클래스의 이름
<2> 사용이 끝난 영구 볼륨의 처리 방식
* retain : 볼륨을 삭제하지 않고, 데이터를 보존
* delete : 볼륨을 삭제
<3> NFS 서버에 생성되는 DIR 경로 형식
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.