= Creating Storage Classes
:toc:
:toc-title:

The following describes how to create storage class resources.

== YAML Editor

=== Block Storage Class

Create a new block storage class by using the YAML editor.

. Click *[Create Storage Classes]* in the <<../console_menu_sub/storage#img-storage-class-main,Storage Classes>> main screen.
. Enter configuration data about a block storage class to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block <1>
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph <2>
  pool: replicapool <3>
  imageFormat: "2" <4>
  imageFeatures: layering <5>
    
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner <6>
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph <2>
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner <6>
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph <2>
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node <6>
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph <2>
  csi.storage.k8s.io/fstype: ext4 <7>
    
#mounter: rbd-nbd <8>
allowVolumeExpansion: true <9>    
reclaimPolicy: Delete <10> 
----
+
<1> Storage class name
<2> Name of a namespace where a Rook Ceph cluster is installed (Default value: rook-ceph) +
If the default value is not used, secret's namespace must be changed.
<3> Ceph pool name (Default value: replicapool)
<4> RBD image format (Default value: 2) +
If this is set to 1, functions such as volume cloning cannot be used because the format is deprecated.
<5> RBD image features (Default value: layering) +
The following are not supported currently: striping, exclusive-lock, object-map, fast-diff, deep-flatten, and journaling.
<6> Ceph admin's secret created by an operator (Fixed value)
<7> File system type in the storage (Default value: ext4)
<8> Option to use the rbd-nbd module when mounting a volume (Unused by default)
<9> Option to support volume size extension (Default value: true)
<10> Policy of handling persistent volumes used (Default value: Delete)
* Retain: Retain the volume and its data.
* Delete: Delete the volume.

. To create the resource with the data you entered, click *[Create]*.

=== File Storage Class

Create a new file storage class by using the YAML editor.

. Click *[Create Storage Classes]* in the <<../console_menu_sub/storage#img-storage-class-main,Storage Classes>> main screen.
. Enter configuration data about a file storage class to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephfs-sc <1>
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph <2>
  fsName: myfs <3>
  pool: myfs-data0 <4>
    
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner <5>
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph <2>
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner <5>
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph <2>
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node <5>
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph <2>
    # mounter: kernel <6>
    
reclaimPolicy: Delete <7>
allowVolumeExpansion: true <8>    
mountOptions:
  #- debug <9>
----
+
<1> Storage class name
<2> Name of a namespace where a Rook Ceph cluster is installed (Default value: rook-ceph) +
If the default value is not used, secret's namespace must be changed.
<3> CephFS's file system name (Default value: myfs)
<4> Ceph pool name (Default value: myfs-data0)
<5> Ceph admin's secret created by an operator (Fixed value)
<6> Module to use when mounting a volume (Unused by default) +
If not set, a driver decides a default volume mounter.
* fuse: ceph-fuse
* kernel: ceph kernelclient
<7> Policy of handling persistent volumes used (Default value: Delete)
* Retain: Retain the volume and its data.
* Delete: Delete the volume.
<8> Option to support volume size extension (Default value: true)
<9> Option to run debugging during mount (Unused by default)

. To create the resource with the data you entered, click *[Create]*.