= 태스크 생성
:toc:
:toc-title:

본 장에서는 태스크 리소스의 생성 방법에 대해서 설명한다.

== YAML 에디터

새로운 태스크를 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/ci-cd#img-task-main,태스크 메인 화면>>에서 *[태스크 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[Yaml 에디터]**를 클릭한다.
. YAML 에디터 화면이 열리면 생성할 태스크의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-task <1>
  namespace: default
spec:
  resources:
    inputs: <2>
      - name: git-source
     type: git
  outputs: <3>
    - name: output-image
      type: image
  params: <4>
    - name: example-string
      type: string
      description: a sample string
      default: default-string-value
  steps: <5>
    - name: sample-job
      image: 'sample-image-name:latest'
      env:
        - name: SAMPLE_ENV
          value: hello/world/
      command:
        - /bin/sh
      args:
        - '-c'
        - echo helloworld
----
+
<1> 태스크의 이름
<2> 태스크에서 참조하는 파이프라인 리소스의 상세 명세
<3> 태스크 실행 완료 후 생성될 결과물의 상세 명세
<4> 실행할 컨테이너 이미지에 정의된 커맨드 인자(args)에서 참조하는 파라미터의 상세 명세
<5> 실행할 컨테이너 이미지의 상세 명세
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

== 폼 에디터

새로운 태스크를 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/ci-cd#img-task-main,태스크 메인 화면>>에서 *[태스크 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[폼 에디터]**를 클릭한다.
. *태스크 생성* 화면이 열리면 생성할 태스크의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다. (* : 필수 입력 항목)
+
[width="100%",options="header", cols="1,3a"]
|====================
|항목|설명
|이름 *|태스크의 이름을 입력한다.
|네임스페이스 *|태스크가 생성될 네임스페이스의 이름을 선택한다.
|인풋 리소스|태스크에서 참조하는 파이프라인 리소스를 추가한다. +
**[+ 추가]**를 클릭해서 *인풋 리소스* 팝업이 열리면 추가할 리소스의 정보를 설정한 후 *[추가]* 버튼을 클릭한다.

* 이름 * : 리소스의 이름
* 타입 * : 리소스의 종류 
* 리소스 저장 경로 : 리소스가 저장된 위치
|아웃풋 리소스|태스크 실행 완료 후 생성될 결과물을 추가한다. +
**[+ 추가]**를 클릭해서 *아웃풋 리소스* 팝업이 열리면 추가할 리소스의 정보를 설정한 후 *[추가]* 버튼을 클릭한다.

* 이름 * : 리소스의 이름
* 타입 * : 리소스의 종류 
* 리소스 저장 경로 : 리소스가 저장될 위치
|태스크 파라미터 구성|실행할 컨테이너 이미지에 정의된 커맨드 인자(args)에서 참조하는 파라미터를 추가한다. +
**[+ 추가]**를 클릭해서 *태스크 파라미터 구성* 팝업이 열리면 추가할 파라미터의 정보를 설정한 후 *[추가]* 버튼을 클릭한다.

* 이름 * : 파라미터의 이름
* 설명 : 파라미터에 대한 간략한 설명
* 타입 * : 파라미터의 종류 
* 기본 값 : 파라미터에 할당할 기본값
|볼륨|태스크 수행을 위해 필요한 파일을 저장하거나 필요한 파일을 제공하기 위한 볼륨을 추가한다. +
**[+ 추가]**를 클릭해서 *볼륨* 팝업이 열리면 추가할 볼륨의 정보를 설정한 후 *[추가]* 버튼을 클릭한다.

* 이름 * : 볼륨의 이름
* 타입 * : 볼륨의 종류 
|스텝 *|태스크의 스텝 관련 정보를 설정한다. +
**[+ 추가]**를 클릭해서 *스텝* 팝업이 열리면 스텝 타입에 따른 정보를 설정한 후 *[추가]* 버튼을 클릭한다.

다음은 스텝의 타입별 설정 항목에 대한 설명이다.

* 프리셋 (APPROVE) +
인증 오브젝트 생성과 관련된 정보(볼륨 마운트)를 설정한다. +
이때 볼륨 마운트 선택 시 컨피그 맵 타입의 볼륨만 선택이 가능하며 시크릿 및 Empty 디렉터리 타입은 선택이 불가능하다.
* 프리셋 (NOTIFY) +
인증 알림 메일 전송과 관련된 정보(메일 서버, 발신자, 제목, 내용, 볼륨 마운트)를 설정한다. +
이때 볼륨 마운트 선택 시 컨피그 맵 타입의 볼륨만 선택이 가능하며 시크릿 및 Empty 디렉터리 타입은 선택이 불가능하다.
* 직접 입력 +
스텝의 기본 정보(스텝 이름, 스텝 컨테이너 이름, 스텝 컨테이너에서 실행되는 커맨드, 스텝 컨테이너에서 참조할 수 있는 환경 변수, 볼륨 마운트)를 설정한다.
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.