= Creating Task Runs
:toc:
:toc-title:

The following describes how to create task run resources.

== YAML Editor

Create a new task run by using the YAML editor.

. Click *[Create Task Runs]* in the <<../console_menu_sub/ci-cd#img-task-run-main,Task Runs>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a task run to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-taskrun
  namespace: default
spec:
  serviceAccountName: example-san <1>
  taskRef: <2>
    name: example-task
  resources:
    inputs: <3>
      - name: git-source
        resourceRef:
          name: example-pipeline-resource-git
    outputs: <4>
      - name: output-image
        resourceRef:
          name: example-pipeline-resource-image
  params: <5>
    - name: example-string
      value: input-string
----
+
<1> Name of a service account that has privilege to create a resource in a namespace
<2> Information about a task to run in the task run
<3> Information about a pipeline resource referred by a container image that runs in a task
<4> Information about results generated after running a task
<5> Information about parameters referred by a container image that runs in a task

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new task run by using the Form editor.

. Click *[Create Task Runs]* in the <<../console_menu_sub/ci-cd#img-task-run-main,Task Runs>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Task Runs* screen opened, enter configuration data about a task run to create. +
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description
|Name*|Task run name.
|Namespace*|Name of a namespace where the task run is created.
|Select task*|Task to run in the task run.
|Task Parameter Value|Value to allocate to a parameter required to run a task.
|Input Resources|Pipeline resource referred when running a task.
|Output Resources|Results generated after running a task.
|Time Point of Timeout Error|Delay period before deciding running a task as failed. (Unit: minutes)
|Service Account Settings|Service account that has privilege to run a task.
|====================

. To create the resource with the data you entered, click *[Create]*.