= 태스크 런 생성
:toc:
:toc-title:

본 장에서는 태스크 런 리소스의 생성 방법에 대해서 설명한다.

== YAML 에디터

새로운 태스크 런을 YAML 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/ci-cd#img-task-run-main,태스크 런 메인 화면>>에서 *[테스크 런 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[Yaml 에디터]**를 클릭한다.
. YAML 에디터 화면이 열리면 생성할 태스크 런의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-taskrun
  namespace: default
spec:
  serviceAccountName: example-san <1>
  taskRef: <2>
    name: example-task
  resources:
    inputs: <3>
      - name: git-source
        resourceRef:
          name: example-pipeline-resource-git
    outputs: <4>
      - name: output-image
        resourceRef:
          name: example-pipeline-resource-image
  params: <5>
    - name: example-string
      value: input-string
----
+
<1> 네임스페이스 내부에 리소스를 생성하기 위해 권한을 가진 서비스 어카운트의 이름
<2> 태스크 런에서 실행할 태스크의 상세 명세
<3> 태스크에서 실행될 컨테이너 이미지가 참조하는 파이프라인 리소스의 상세 명세
<4> 태스크 실행 완료 후 생성될 결과물의 상세 명세
<5> 태스크에서 실행될 컨테이너 이미지가 참조하는 파라미터의 상세 명세
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.

== 폼 에디터

새로운 태스크 런을 폼 에디터를 사용해서 생성할 수 있다.

. <<../console_menu_sub/ci-cd#img-task-run-main,태스크 런 메인 화면>>에서 *[태스크 런 생성]* 버튼을 클릭한다.
. 드롭다운 메뉴가 열리면 **[폼 에디터]**를 클릭한다.
. *태스크 런 생성* 화면이 열리면 생성할 태스크 런의 구성 정보를 설정한다. +
각 설정 항목에 대한 설명은 다음과 같다. (* : 필수 입력 항목)
+
[width="100%",options="header", cols="1,3"]
|====================
|항목|설명
|이름 *|태스크 런의 이름을 입력한다.
|네임스페이스 *|태스크 런이 생성될 네임스페이스의 이름을 선택한다.
|태스크 선택 *|태스크 런에서 실행할 태스크를 선택한다.
|태스크 파라미터 값|태스크 실행 시 필요한 파라미터에 할당할 값을 입력한다.
|인풋 리소스|태스크 실행 시 참조하는 파이프라인 리소스를 선택한다.
|아웃풋 리소스|태스크 실행 완료 후 생성될 결과물을 선택한다.
|타임아웃 실패 시점 설정|태스크 실행을 실패로 판단할 지연 시간을 설정한다. (단위: 분)
|서비스 어카운트 지정|태스크 실행에 특정 권한을 지정할 서비스 어카운트를 선택한다.
|====================
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.