= Creating Tasks
:toc:
:toc-title:

The following describes how to create task resources.

== YAML Editor

Create a new task by using the YAML editor.

. Click *[Create Tasks]* in the <<../console_menu_sub/ci-cd#img-task-main,Task>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a task to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-task <1>
  namespace: default
spec:
  resources:
    inputs: <2>
      - name: git-source
     type: git
  outputs: <3>
    - name: output-image
      type: image
  params: <4>
    - name: example-string
      type: string
      description: a sample string
      default: default-string-value
  steps: <5>
    - name: sample-job
      image: 'sample-image-name:latest'
      env:
        - name: SAMPLE_ENV
          value: hello/world/
      command:
        - /bin/sh
      args:
        - '-c'
        - echo helloworld
----
+
<1> Task name
<2> Information about a pipeline resource referred by the task
<3> Information about results generated after running the task
<4> Information about parameters referred by command arguments defined in a container image to run
<5> Information about a container image to run

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new task by using the Form editor.

. Click *[Create Tasks]* in the <<../console_menu_sub/ci-cd#img-task-main,Task>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Tasks* screen opened, enter configuration data about a deployment to create. +
The following describes each configuration item. (*: required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description
|Name*|Task name.
|Namespace*|Name of a namespace where the task is created.
|Input Resources|Pipeline resource referred by the task. +
Clicking **[+ Add More]** opens the *Input Resources* dialog box. Enter information about a resource to add and then click *[Add]*.

* Name*: Resource name.
* Type*: Resource type. 
* Resource Path: Resource location.
|Output Resources|Results generated after running the task. +
Clicking **[+ Add More]** opens the *Output Resources* dialog box. Enter information about a resource to add and then click *[Add]*.

* Name*: Resource name.
* Type*: Resource type. 
* Resource Path: Resource location.
|Task Parameter|Parameters referred by command arguments defined in a container image to run. +
Clicking **[+ Add More]** opens the *Task Parameter* dialog box. Enter information about a parameter to add and then click *[Add]*.

* Name*: Parameter name.
* Description: Brief description about the parameter.
* Type*: Parameter type. 
* Default Value: Default value of the parameter
|Volume|Volume that stores or supports files required to run the task. +
Clicking **[+ Add More]** opens the *Volume* dialog box. Enter information about a volume to add and then click *[Add]*.

* Name*: Volume name.
* Type*: Volume type. 
|Step *|Task's step. +
Clicking **[+ Add More]** opens the *Step* dialog box. Enter information depending on the step type and then click *[Add]*.

The following describes configuration items for each step type.

* Preset (APPROVE) +
Set information related to authentication object creation (volume mount). +
Only config map volume can be selected. Secret and empty directory volumes cannot be selected.
* Preset (NOTIFY) +
Set information related to authentication notification mail (mail server, mail from, title, contents, and volume mount). +
Only config map volume can be selected. Secret and empty directory volumes cannot be selected.
* Input Directly +
Set information about the step (step name, step container name, commands that run in the step container, environment variables that can be referred by the step container, and volume mount).
|====================

. To create the resource with the data you entered, click *[Create]*.