= Creating Templates
:toc:
:toc-title:

The following describes how to create template resources.

== YAML Editor

Create a new template by using the YAML editor.

. Click *[Create Templates]* in the <<../console_menu_sub/service-catalog#img-template-main,Templates>> main screen.
. Enter configuration data about a template to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tmax.io/v1
kind: Template
metadata:
  name: nginx-template <1>
  namespace: default <2>
imageUrl: example.com/example.gif <3>
provider: tmax <4>
recommend: true <5>
urlDescription: http://url.example.com <6>
tags: <7>
- nginx
objects: <8>
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - name: ${NAME}
          image: ${IMAGE}
          ports:
          - name: http
            containerPort: 80
          resources:
            requests:
              cpu: 1
        tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          tolerationSeconds: 10
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          tolerationSeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: http
      port: 81
      protocol: TCP
      targetPort: 80
    selector:
      app: ${NAME}
    type: LoadBalancer
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  data:
    host: ZHVtbXk=
parameters: <9>
- name: NAME
  description: Application name
  valueType: string <10>
  value: nginx <11>
- name: IMAGE
  description: Application Docker Image
  valueType: string
  value: nginx
plans: <12>  
- name: example-plan1
  description: example
  metadata:
    bullets:
    - feat 1
    - feat 2
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          NAME: nginx1
          IMAGE: nginx:1
- name: example-plan2
  description: example
  metadata:
    bullets:
    - feat 1
    - feat 2
    costs:
      amount: 200
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          NAME: nginx2
          IMAGE: nginx:1  
  
----
+
<1> Template name
<2> Name of a namespace where the template is created
<3> Template image URL
<4> Template provider
<5> Whether to recommend the template
<6> Template description page URL
<7> Tags expressing the template
<8> Actual objects to create based on the template (The ``${PARAMETER}`` format is used for variables.)
<9> Details about variables specified in the template
<10> Variable's data type
* string
* number
<11> Variable's default value
<12> Plans to use to integrate a service broker

. To create the resource with the data you entered, click *[Create]*.