= Creating Template Instances
:toc:
:toc-title:

The following describes how to create template instance resources.

== YAML Editor

Create a new template instance by using the YAML editor.

. Click *[Create Template Instances]* in the <<../console_menu_sub/service-catalog#img-template-instance-main,Template Instances>> main screen.
. Select **[Yaml Editor]** from the drop down menu.
. Enter configuration data about a template instance to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: nginx-template-instance <1>
  namespace: hypercloud-system <2>
spec:
  template:
    metadata: <3>
      name: nginx-template
    parameters: <4>
    - name: NAME
      value: nginx
    - name: IMAGE
      value: nginx:1
----
+
<1> Name of a template instance
<2> Name of a namespace where the template instance is created
<3> Template information to which the template instance refers
<4> Pairs of name and value of variables entered when creating the template instance

. To create the resource with the data you entered, click *[Create]*.

== Form Editor

Create a new template instance by using the Form editor.

. Click *[Create Template Instances]* in the <<../console_menu_sub/service-catalog#img-template-instance-main,Template Instances>> main screen.
. Select **[Form Editor]** from the drop down menu.
. In the *Create Template Instances* screen opened, enter configuration data about a template instance to create. +
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description
|Name|Template instance name.
|Template|Template name.
|Parameters|Parameters declared in a template.
|====================

. To create the resource with the data you entered, click *[Create]*.