= 테라폼 클레임 생성
:toc:
:toc-title:

본 장에서는 테라폼 클레임 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 테라폼 클레임을 폼 에디터를 사용해서 생성할 수 있다.

. "멀티 클러스터" 콘솔 메뉴에서 *[테라폼 클레임]* 메뉴를 선택한다.
. *테라폼 클레임* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 테라폼 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[테라폼 클레임 생성]* 버튼을 클릭한다.
. *테라폼 클레임 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 테라폼 클레임의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* branch
* destroy
* secret
* type *
* url *
* variable
* version *
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 테라폼 클레임을 YAML 에디터를 사용해서 생성할 수 있다.

. "멀티 클러스터" 콘솔 메뉴에서 *[테라폼 클레임]* 메뉴를 선택한다.
. *테라폼 클레임* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 테라폼 클레임을 생성할 특정 네임스페이스를 선택한다.
. *[테라폼 클레임 생성]* 버튼을 클릭한다.
. *테라폼 클레임 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 테라폼 클레임의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: claim.tmax.io/v1alpha1
kind: TFApplyClaim
metadata:
  name: example <1>
  namespace: default <2>
spec:
  branch: master <3>
  destroy: false <4>
  secret: git-credential <5>
  type: public <6>
  url: http://gitlab.tmaxcloud.com/root/public.git <7>
  variable: AWS_ACCESS_KEY_ID=aws-access-key <8>
  version: 0.14.9 <9>
----
+
<1> 테라폼 클레임의 이름
<2> 테라폼 클레임이 생성될 네임스페이스의 이름
<3> Git 브랜치 이름
<4> 테라폼 제거시 사용되는 값으로 false로만 생성 가능 (QA : 주의 표시가 들어가야할 것 같습니다)
<5> Git에 접근 가능한 액세스 토큰으로 생성한 시크릿 정보 (Git 저장소의 공개 유형이 "private"일 경우 반드시 설정)
<6> Git 저장소의 공개 유형

* private
* public
<7> 사용할 HCL 코드가 있는 Git 주소
<8> tf 파일에 선언한 변수 값에 매핑할 값
<9> 사용할 테라폼 버전
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
