= 학습 모델 생성
:toc:
:toc-title:

본 장에서는 학습 모델 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 학습 모델을 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[AI DevOps]* -> *[학습 모델]* 메뉴를 선택한다.
. *학습 모델* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 학습 모델을 생성할 특정 네임스페이스를 선택한다.
. *[학습 모델 생성]* 버튼을 클릭한다.
. *학습 모델 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 학습 모델의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 설정 항목) 
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* inferenceService *
* Model *
+
----
framework *
memory *
storageUri *
----
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다

== YAML 에디터

새로운 학습 모델을 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[AI DevOps]* -> *[학습 모델]* 메뉴를 선택한다.
. *학습 모델* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 학습 모델을 생성할 특정 네임스페이스를 선택한다.
. *[학습 모델 생성]* 버튼을 클릭한다.
. *학습 모델 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 학습 모델의 구성 정보를 설정한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: "serving.kserve.io/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "fashion" <1>
  namespace: demo <2>
spec:
  inferenceService: triton-mms <3>
  model: <4>
    framework: tensorflow <5>
    memory: 1.0Gi <6>
    storageUri: "s3://triton/models/fashion" <7>
----
+
<1> 학습 모델의 이름
<2> 학습 모델이 생성될 네임스페이스의 이름
<3> 학습 모델을 배포할 상위 추론 서비스의 이름
<4> 예측(predictor) 모델의 사양
<5> 학습에서 사용하는 프레임워크의 종류
<6> 모델이 사용할 최대 메모리
<7> 학습 모델 리포지터리의 스토리지 URI 주소
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.
