= Creating Training Jobs
:toc:
:toc-title:

The following describes how to create training Job resources.

== YAML Editor

=== TensorFlow Jobs

Create a new TensorFlow Job by using the YAML editor.

. Click *[Create Training Jobs]* in the <<../console_menu_sub/ai-dev#img-training-job-main,Training Jobs>> main screen.
. Select **[Yaml Editor(TF Job)]** from the drop down menu.
. Enter configuration data about a TensorFlow Job to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: kubeflow.org/v1
kind: TFJob
metadata: <1>
  name: demo-tfjob <2>
  namespace: demo <3>
spec: <4>
  tfReplicaSpecs: <5>
    Worker: <6>
      replicas: 1 <7>
      template: <8>
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          name: fairing-deployer
        spec:
          containers:
          - command:
            - python
            - /app/fmnist-save-model-renew.py
            - "--learning_rate=0.01393"
            - "--dropout_rate=0.84807"
            env:
            - name: FAIRING_RUNTIME
              value: "1"
            image: rhojw/sample-job:3C8CE2EE
            name: tensorflow
            resources:
              limits:
                cpu: 1
                memory: 1.86Gi
            securityContext:
              runAsUser: 0
            volumeMounts:
            - mountPath: /result
              name: fairing-volume-demo-pvc
            workingDir: /app/
          restartPolicy: Never
          volumes:
          - name: fairing-volume-demo-pvc
            persistentVolumeClaim:
              claimName: demo-pvc
----
+
<1> TensorFlow Job metadata
<2> Name of a namespace where the TensorFlow Job is created
<3> TensorFlow Job name
<4> TensorFlow Job specification
<5> Specification of a replica created by the TensorFlow Job
<6> Worker specification
<7> Number of replicas
<8> Worker pod template

. To create the resource with the data you entered, click *[Create]*.

=== PyTorch Jobs

Create a new PyTorch Job by using the YAML editor.

. Click *[Create Training Jobs]* in the <<../console_menu_sub/ai-dev#img-training-job-main,Training Jobs>> main screen.
. Select **[Yaml Editor(PyTorch Job)]** from the drop down menu.
. Enter configuration data about a PyTorch Job to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata: <1>
  name: pytorch-tcp-dist-mnist <2>
  namespace: default <3>
spec: <4>
  pytorchReplicaSpecs: <5>
    Master: <6>
      replicas: 1 <7>
      restartPolicy: OnFailure <8>
      template: <9>
        spec:
          containers:
            - name: pytorch
              image: 'gcr.io/kubeflow-ci/pytorch-dist-mnist_test:1.0'
              ports:
                - name: pytorchjob-port
                  containerPort: 23456
              resources:
                limits:
                  nvidia.com/gpu: 1
    Worker: <10>
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: 'gcr.io/kubeflow-ci/pytorch-dist-mnist_test:1.0'
              ports:
                - name: pytorchjob-port
                  containerPort: 23456
              resources:
                limits:
                  nvidia.com/gpu: 1
----
+
<1> PyTorch Job metadata
<2> PyTorch Job name
<3> Name of a namespace where the PyTorch Job is created
<4> PyTorch Job specification
<5> Specification of a replica created by the PyTorch Job
<6> Master specification
<7> Number of replicas
<8> Master pod template
<9> Restarting policy when a failure occurs
<10> Specification of a worker for actual learning

. To create the resource with the data you entered, click *[Create]*.