= Creating User Groups
:toc:
:toc-title:

The following describes how to create user groups and assign roles to them.

== Creating User Groups

Create a new user group.

. Click *[New]* in the <<../console_menu_sub/permission#img-user-group-main,Groups>> main screen.
. In the *Create group* screen opened, enter configuration data about a user group to create.
+
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description
|Name *|User group name.
|====================
. To save the configuration data, click *[Save]*.

== Assigning Roles to User Groups

Assign a role to a user group.

. Double-click the name of a user group to which a role is assigned from the user group list in the <<../console_menu_sub/permission#img-user-group-main,Groups>> main screen.
. In the opened screen for the user group details, click *[Role Mappings]* tab and add a role to assign to the user group.
+
The following describes each area.

* *Available Roles* +
Displays roles that can be assigned to a user group. Selecting a role to assign and clicking *[Add selected]* moves the role to the *'Assigned Roles'* areas.
+
The following describes each role.
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description
|hyperauth tmax realm all role|All roles for tmax realm.
|offline_access|Role to issue and use an offline token so that a user can work offline.
|tmax realm user, group all role|All roles for users and groups of tmax realm.
|tmax realm user, group list|List role for users and groups of tmax realm.
|uma_authorization|Roles provided by HyperAuth by default for user and application integration.
|====================
* *Assigned Roles* +
Displays roles assigned to a user group. +
To remove an assigned role, select the role and click *[Remove selected]*. The role is moved to the *'Available Roles'* area.
* *Effective Roles* +
Displays roles dependent on assigned roles.
* *Client Roles* +
Assigns roles dependent on clients.