= 사용자 그룹 생성
:toc:
:toc-title:

본 장에서는 사용자 그룹의 생성 및 권한 할당 방법에 대해서 설명한다.

== 사용자 그룹 생성

새로운 사용자 그룹을 생성할 수 있다.

. <<../console_menu_sub/permission#img-user-group-main,Groups 메인 화면>>에서 *[New]* 버튼을 클릭한다.
. *Create group* 화면이 열리면 생성할 사용자 그룹의 구성 정보를 설정한다.
+
각 설정 항목에 대한 설명은 다음과 같다. (* : 필수 설정 항목)
+
[width="100%",options="header", cols="1,3"]
|====================
|항목|설명
|Name *|사용자 그룹의 이름을 입력한다.
|====================
. 설정이 완료되면 *[Save]* 버튼을 클릭해서 설정 내용을 저장한다.

== 사용자 그룹 권한 할당

사용자 그룹에 권한을 할당할 수 있다.

. <<../console_menu_sub/permission#img-user-group-main,Groups 메인 화면>>의 사용자 그룹 목록 영역에서 권한을 할당할 사용자 그룹의 이름을 더블클릭한다.
. 해당 사용자 그룹의 상세 정보 화면이 열리면 *[Role Mappings]* 탭을 선택한 후 사용자 그룹에 할당할 권한을 추가한다.
+
각 영역에 대한 설명은 다음과 같다.

* *Available Roles* +
사용자 그룹에 할당 가능한 권한의 목록이 표시된다. 이때 할당할 권한을 선택한 후 *[Add selected]* 버튼을 클릭하면 해당 권한이 *'Assigned Roles'* 영역으로 이동한다.
+
각 권한에 대한 설명은 다음과 같다.
+
[width="100%",options="header", cols="1,3"]
|====================
|항목|설명
|hyperauth tmax realm all role|tmax realm에 대한 모든 권한
|offline_access|오프라인 상태에서도 작업할 수 있도록 오프라인 토큰을 발급하여 사용할 수 있는 권한
|tmax realm user, group all role|tmax realm의 user, group에 대한 모든 권한
|tmax realm user, group list|tmax realm의 user, group에 대한 list 권한
|uma_authorization|사용자와 애플리케이션 연동을 위해 HyperAuth에서 기본으로 제공되는 권한
|====================
* *Assigned Roles* +
사용자 그룹에 할당된 권한의 목록이 표시된다. +
만약 할당된 권한을 제거하려면 제거할 권한을 선택한 후 *[Remove selected]* 버튼을 클릭한다. 이때 제거된 권한은 *'Available Roles'* 영역으로 이동한다.
* *Effective Roles* +
할당된 권한에 종속되어 있는 모든 권한의 목록이 표시된다.
* *Client Roles* +
클라이언트에 종속되어 있는 권한을 할당한다.