= Creating Users
:toc:
:toc-title:

The following describes how to create users and assign roles to them.

== Creating Users

Create a new user.

. Click *[Add user]* in the <<../console_menu_sub/permission#img-user-main,Users>> main screen.
. In the *Add user* screen opened, enter configuration data about a user to create.
+
The following describes each configuration item. (*: Required)
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description
|Username*|User ID to use when logging in to HyperCloud console.
|Email|Email address of the user. This is used to find a password and receive information such as OTP authentication data.
|First Name|First name of the user.
|Last Name|Last name of the user.
|User Enabled|Option to enable the user.

* ON: Enable the user (can log in to HyperCloud console)
* OFF: Disable the user (cannot log in to HyperCloud console)
|Email Verified|Whether the email address is verified.

* ON: The email address has been verified.
* OFF: The email address has not been verified.
|Required User Actions|Action that the user needs to take to activate the account after the first login.

* Update Password: Changing the password
* Update Profile: Changing the user information
* Verify Email: Verifying the email address
|Locale|Default language to use in the console.
|====================
. To save the configuration data, click *[Save]*.
. In the opened screen for user details, click the *[Credentials]* tab and set the user's password in *'Set Password'*.
+
The following describes each configuration item.
+
[width="100%",options="header", cols="1,3a"]
|====================
|Item|Description
|Password|User password with the following conditions.

* Must include one or more uppercase letters, lowercase letters, digits, and special characters.
* Must be 9 or more characters in length.
|Password Confirmation|Password entered in *'Password'*.
|Temporary|Option to use the set password temporarily.

* ON: Change the password after the first login.
* OFF: Continue to use the set password.
|====================
. To save the configuration data, click *[Set Password]*.

== Assigning Roles to Users

Assign a role to a user.

. Click the ID of a user to whom a role is assigned from the user list in the <<../console_menu_sub/permission#img-user-main,Users>> main screen.
. In the opened screen for the use details, click the *[Role Mappings]* tab and add a role to assign to the user.
+
The following describes each area.

* *Available Roles* +
Displays roles that can be assigned to a user. Selecting a role to assign and clicking *[Add selected]* moves the role to the *'Assigned Roles'* area.
+
The following describes each role.
+
[width="100%",options="header", cols="1,3"]
|====================
|Item|Description
|hyperauth tmax realm all role|All roles for tmax realm.
|offline_access|Role to issue and use an offline token so that a user can work offline.
|tmax realm user, group all role|All roles for users and groups of tmax realm.
|tmax realm user, group list|List role for users and groups of tmax realm.
|uma_authorization|Roles provided by HyperAuth by default for user and application integration.
|====================
* *Assigned Roles* +
Displays roles assigned to a user. +
To remove an assigned role, select the role and click *[Remove selected]*. The role is moved to the *'Available Roles'* area.
* *Effective Roles* +
Displays roles dependent on assigned roles.
* *Client Roles* +
Assigns roles dependent on clients.

== Adding Users to a Group

Add a user to a group.

. Click the ID of a user to join a group from the user list in the <<../console_menu_sub/permission#img-user-main,Users>> main screen.
. In the opened screen for the use details, click the *[Groups]* tab and select a user group.
+
The following describes each area.

* *Group Membership* +
Displays user groups the user joined. +
To leave the group, select the group and click *[Leave]*.
* *Available Groups* +
Displays user groups the user can join. Selecting a user group to join and clicking *[Join]* moves the user group to the *'Group Membership'* area.