= 가상 서비스 생성
:toc:
:toc-title:

본 장에서는 가상 서비스 리소스의 생성 방법에 대해서 설명한다.

== 폼 에디터

새로운 가상 서비스를 폼 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[가상 서비스]* 메뉴를 선택한다.
. *가상 서비스* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 가상 서비스를 생성할 특정 네임스페이스를 선택한다.
. *[가상 서비스 생성]* 버튼을 클릭한다.
. *가상 서비스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "Form View"로 선택한다.
. 폼 에디터가 열리면 생성할 가상 서비스의 구성 정보를 설정한다. +
이때 설정 가능한 항목들은 다음과 같다. (* : 필수 입력 항목)
+
NOTE: 각 항목에 대한 자세한 설명은 제품 내의 설명을 참고한다.

* Name *
* Labels
* Export To
+
----
Value *
----
* Gateways
+
----
Value *
----
* Hosts
+
----
Value *
----
* Http +
하위 세부 항목은 xref:../form-set-item.adoc#Http["폼 에디터 설정 항목 참조"의 "Http"]를 참고한다.
* Tcp +
하위 세부 항목은 xref:../form-set-item.adoc#Tcp["폼 에디터 설정 항목 참조"의 "Tcp"]를 참고한다.
* Tls +
하위 세부 항목은 xref:../form-set-item.adoc#Tls["폼 에디터 설정 항목 참조"의 "Tls"]를 참고한다.
. 설정이 완료되면 *[생성]* 버튼을 클릭해서 설정 내용을 저장한다.

== YAML 에디터

새로운 가상 서비스를 YAML 에디터를 사용해서 생성할 수 있다.

. "개발자" 콘솔 메뉴에서 *[서비스 메시]* -> *[가상 서비스]* 메뉴를 선택한다.
. *가상 서비스* 메인 화면이 열리면 네임스페이스 선택 영역에서 새로운 가상 서비스를 생성할 특정 네임스페이스를 선택한다.
. *[가상 서비스 생성]* 버튼을 클릭한다.
. *가상 서비스 생성* 화면이 열리면 **"다음을 통해 설정"**을 "YAML View"로 선택한다.
. YAML 에디터가 열리면 생성할 가상 서비스의 구성 정보를 작성한다.
+
.기본 작성 예
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo <1>
  namespace: bookinfo
spec:
  gateways: <2>
    - bookinfo-gateway 
  hosts: <3>
    - '*' 
  http:
    - match: <4>
        - uri:
            exact: /productpage 
        - uri:
            prefix: /static
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
      route:
        - destination:
            host: productpage <5>
            port:
              number: 9080
----
+
<1> 가상 서비스의 이름
<2> 라우팅 규칙을 적용할 게이트웨이의 이름
<3> 라우팅 규칙이 적용될 가상 서비스의 호스트 +
이때 와일드 카드 접두사(*)로 DNS 이름을 표기하거나 FQDN(Fully Qualified Domain Name) 형식으로 입력
<4> 라우팅 규칙을 적용하기 위한 요청의 조건
<5> 조건에 일치하는 트래픽의 실제 목적지
. 작성이 완료되면 *[생성]* 버튼을 클릭해서 작성 내용을 저장한다.