= Creating Virtual Machines
:toc:
:toc-title:

The following describes how to create virtual machine resources.

== YAML Editor

Create a new virtual machine by using the YAML editor.

. Click *[Create Virtual Machines]* in the <<../console_menu_sub/work-load#img-vm-main,Virtual Machines>> main screen.
. Enter configuration data about a virtual machine to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata: 
  name: windows-vm <1>
  namespace: default <2>
spec:
  running: true <3>
  template:
    spec:
      hostname: guestos-name <4>
      affinity:
        nodeAffinity: <5>
          requiredDuringSchedulingIgnoredDuringExecution:  
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname <6>
                    operator: In <7>
                    values: <8>
                      - k8s-3-3
      domain:
        machine:
          type: q35 <9>
        devices:
          disks: <10>
            - disk:
                bus: virtio <11>
              name: rootdisk <12>
              bootOrder: 1 <13>
            - cdrom: <14>
                bus: sata
                readonly: true <15>
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: additionaldisk
          interfaces: <16>
            - name: default <17>
              model: virtio <18>
              bridge: {} <19>
              macAddress: 'de:ad:00:00:be:aa' <20>
        gpus: <21>
          - deviceName: nvidia.com/GP102GL_Tesla_P40 <22>
            name: gpu1 <23>
        cpu: 
          cores: 2 <24>
        memory:
          guest: 2Gi <25>
        resources:
          overcommitGuestOverhead: false <26>
          requests:
            cpu: 1500m <27>
            memory: 2Gi <28>
          limits:
            cpu: 2500m <29>
            memory: 3Gi <30>
      terminationGracePeriodSeconds: 0 <31>
      networks: <32>
        - name: default <33>
          pod: {} <34>
      volumes: <35>
        - containerDisk: <36>
            image: '172.21.7.20:5000/ubuntu:18.04' <37>
          name: rootdisk <38>
        - name: cloudinitdisk <39>
          cloudInitConfigDrive: <40>
            userData: | <41>
              #ps1_sysnative
              NET USER tmax "Qwer12345" /ADD 
              NET LOCALGROUP "Administrators" "tmax" /add
        - name: additionaldisk <42>
          persistentVolumeClaim: <43>
            claimName: empty-pvc <44>
----
+
<1> Virtual machine name
<2> Name of a namespace where the virtual machine is created
<3> Whether to run the virtual machine
* true: Create and run the virtual machine.
* false: Only create the virtual machine.
<4> Hostname of a guest OS
<5> Configuration about node affinity
<6> Key for a node label when selecting a node
<7> Decision operator for key-value
<8> Actual key value for a node label
<9> Qemu machine type (Default value: q35)
<10> Disk to connect to an instance
<11> Type of a disk device to emulate
* virtio
* sata
* scsi
<12> Name of the disk device (identical to that of a volume to use)
<13> Booting order of the disk device
<14> CD-ROM to connect
<15> Read/write permission (Default value: true)
<16> Network interface information
<17> Network device name
<18> Interface model (Default value: virtio)
* e1000
* e1000e
* ne2k_pci
* pcnet
* rtl8139
* virtio
<19> Network configuration method
* bridge
* masquerade
* slirp
* sriov
<20> MAC address
<21> Information about a GPU device to connect
<22> Name of the GPU device
<23> Name of the GPU device to be exposed by device plugin
<24> Number of CPU cores to be allocated by the virtual machine process
<25> Memory to be allocated by the virtual machine process
<26> Whether to allow overhead for running the virtual machine (Default value: false)
<27> Minimum CPU for scheduling
<28> Minimum memory for scheduling
<29> CPU limit value of the virtual machine process
<30> Memory limit value of the virtual machine process
<31> Grace period to forcibly terminate the virtual machine after it stopped
<32> Information about a network to connect to a virtual interface of the virtual machine
<33> Name exposed to be used in a network interface
<34> Using a pod network
<35> Information about a volume to mount to the virtual machine
<36> One-time disk with the same lifecycle with VMI by referring to Docker image
<37> Image name registered in the Docker registry
<38> Volume name to be exposed to a device
<39> Volume name to be exposed to a device
<40> Datasource to be used in cloud-init or cloudbaseinit
<41> Configuration about user data
<42> Name of a volume exposed to a device
<43> Information about a persistent volume claim
<44> Name of a persistent volume claim

. To create the resource with the data you entered, click *[Create]*.