= Creating Workflows
:toc:
:toc-title:

The following describes how to create workflow resources.

== YAML Editor

Create a new workflow by using the YAML editor.

. Click *[Create Workflows]* in the <<../console_menu_sub/ai-dev#img-workflow-main,Workflows>> main screen.
. Enter configuration data about a workflow to create in the YAML editor opened.
+
.Sample
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: <1>
  name: demo-workflow <2>
  namespace: demo <3>
spec: <4>
  arguments: <5>
    parameters: <6>
    - name: learning_rate <7>
      value: "0.001397" <8>
    - name: dropout_rate
      value: "0.18"
    - name: epoch
      value: "11"
    - name: act
      value: sigmoid
    - name: layer
      value: "2"
    - name: checkpoint_dir
      value: /reuslt/training_checkpoints
    - name: saved_model_dir
      value: /result/saved_model/
    - name: pvc_name
      value: demo-pvc
    - name: tensorboard_log
      value: /result/log
    - name: name
      value: demo-inferenceservice
    - name: model_version
      value: "0001"
    - name: namespace
      value: demo
  entrypoint: fmnist <9>
  onExit: demo-inferenceservice <10>
  serviceAccountName: default-editor <11>
  templates: <12>
  - arguments: {}
    container: <13>
      args:
      - --learning_rate
      - '{{inputs.parameters.learning_rate}}'
      - --dropout_rate
      - '{{inputs.parameters.dropout_rate}}'
      - --epoch
      - '{{inputs.parameters.epoch}}'
      - --act
      - '{{inputs.parameters.act}}'
      - --layer
      - '{{inputs.parameters.layer}}'
      - --checkpoint_dir
      - '{{inputs.parameters.checkpoint_dir}}'
      - --saved_model_dir
      - '{{inputs.parameters.saved_model_dir}}'
      - --model_version
      - '{{inputs.parameters.model_version}}'
      - --tensorboard_log
      - '{{inputs.parameters.tensorboard_log}}'
      command:
      - python
      - /app/fmnist-save-model-renew.py
      image: rhojw/sample-job:3C8CE2EE
      name: ""
      resources: {}
      volumeMounts:
      - mountPath: /result
        name: pvolume-4a58304317c5a3f7e710d2eb21f621e4ee3cae3e64f19e1d55a8a09
    inputs: <14>
      parameters: <15>
      - name: act
      - name: checkpoint_dir
      - name: dropout_rate
      - name: epoch
      - name: layer
      - name: learning_rate
      - name: model_version
      - name: pvc_name
      - name: saved_model_dir
      - name: tensorboard_log
    metadata: <16>
      annotations:
        sidecar.istio.io/inject: "false"
    name: fmnist <17>
    outputs: {} <18>
    volumes: <19>
    - name: pvolume-4a58304317c5a3f7e710d2eb21f621e4ee3cae3e64f19e1d55a8a09
      persistentVolumeClaim:
        claimName: '{{inputs.parameters.pvc_name}}'
  - arguments: {}
    container:
      args:
      - --namespace
      - '{{inputs.parameters.namespace}}'
      - --storage_uri
      - pvc://{{inputs.parameters.pvc_name}}/saved_model
      - --name
      - '{{inputs.parameters.name}}'
      command:
      - python
      - /app/KFServing-fairing.py
      image: docker.io/rhojw/kfserving:745DCD9A
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: name
      - name: namespace
      - name: pvc_name
    metadata: 
      annotations:
        sidecar.istio.io/inject: "false"
    name: demo-inferenceservice
    outputs: {}
----
+
<1> Workflow metadata
<2> Workflow name
<3> Name of a namespace where the workflow is created
<4> Workflow specification
<5> Argument used in the workflow
<6> Parameters used in the workflow
<7> Parameter name
<8> Parameter value
<9> Start task name
<10> Last task name
<11> Name of a service account allocated to workflow management pod
<12> Task template in the workflow
<13> Task's container specification
<14> Input data used in a task
<15> Parameters used as input
<16> Task metadata
<17> Task name
<18> Task output
<19> Information about a volume to mount to a task pod

. To create the resource with the data you entered, click *[Create]*.