= Kube 인증서 관리
:toc:
:toc-title:

== kube-system 인증서 유효기간 확인

kube-system 인증서의 유효기간은 기본적으로 1년이다. kube-system 인증서의 유효기간 확인을 통해 인증서의 갱신 여부를 판단한다.
----
$ kubeadm certs check-expiration
----

== kube-system 인증서 갱신

kube-system 인증서는 1년마다 갱신을 해야한다. 이때 모든 마스터 노드에서 순차적으로 진행한다.

. *인증서 갱신*
+
----
$ kubeadm certs renew all
----

. *kube-system 파드 재기동*
+
갱신한 인증서를 적용하기 위해 kube-system 파드를 재기동한다. +
이때 마스터 노드 별로 진행하는 것을 권장하며 scheduler, apiserver, controller, etcd 순으로 진행한다.
+
.실행 방법
----
$ kubectl delete pod [파드 이름] -n kube-system
----
+
.예시
----
$ kubectl delete pod kube-apiserver-master1 -n kube-system
----

. *config 교체*
+
kube-system 파드 재기동 완료 후 kubelet 사용을 위해 새로 갱신한 config로 교체한다.
+
----
$ cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
----

. *인증서 갱신 확인*
+
갱신된 인증서는 아래 명령어를 통해 확인할 수 있다.
+
----
$ kubeadm certs check-expiration
----

== 인스톨러를 통한 인증서 갱신

. *인증서 기한 설정*
+
`kubespray-infra/inventory/tmaxcloud/group_vars/k8s_cluster/k8s-cluster.yml` 파일을 열어 K8S의 인증서 기한을 설정한다.
+
.실행 방법
----
## k8s certs days
update_cert: true
cert_days: [기한(일)]
----
+
.예시
----
## k8s certs days
update_cert: true
cert_days: 3650
----
+
. *kube-system 인증서 갱신*
+
----
ansible-playbook -i kubespray-infra/inventory/tmaxcloud/inventory.ini --become --become-user=root cluster.yml -v -t update-kubeadm-cert
----
+

. *kubelet 인증서 갱신*
+
----
ansible-playbook -i kubespray-infra/inventory/tmaxcloud/inventory.ini --become --become-user=root cluster.yml -v -t update-kubelet-cert
----

== 공인 인증서 적용

=== AWS route53을 통한 유효한 인증서 발급

본 절에서는 DNS01을 이용한 인증서 발급 방식 중 AWS의 Route53을 통한 TLS 인증서 발급 방법에 대해서 설명한다.

[NOTE]
.참고 문서
====
* link:https://cert-manager.io/docs/configuration/acme/dns01/[DNS01을 통한 인증서 개요]
* link:https://cert-manager.io/docs/configuration/acme/dns01/route53/[Route53을 통한 ClusterIssuer 생성]
====



. *AWS Console에서 IAM Role 설정과 Issuer 생성* +
Cert-Manager에서 사용할 수 있도록 AWS Console에서 route53에 대한 권한을 등록한다. +
아래 참고 문서에서 "*1. Setup Issuer*" 내용을 참고하여 IAM role 등록 및 Issuer를 생성한다.
+
----
https://cert-manager.io/docs/configuration/acme/dns01/
----
+
이때 ClusterIssuer 생성과 letsencrypt를 통한 공인된 TLS 인증서 발급을 위해 아래 yaml 파일을 참고하여 수정하는 것을 권장한다.
+
[source,yaml]
----
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cloud_csp@tmax.co.kr <1>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - dns01:
          route53:
            region: ap-northeast-2
            accessKeyID: KIR2WO5YWT
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key
            hostedZoneID: J13B3AB # optional
----
+
<1> TmaxCloud에서 사용하는 AWS 계정

. *Certificate을 사용하여 TLS secret 생성* +
Cert Manager에서 제공하는 Certificate 객체를 만들어 TLS 인증서를 발급한다.
+
certificate.yaml 파일을 아래와 같이 생성한다.
+
[source,yaml]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-acme-crt
  namespace: default <1>
spec:
  secretName: tls-acme-secret <2> 
  dnsNames: <3>
    - tmaxcloud.org  
    - "*.tmaxcloud.org" 
  issuerRef:
    name: letsencrypt-dns <4>
    kind: ClusterIssuer
----
+
<1> TLS 인증서가 secret 형태로 생성되길 원하는 네임스페이스
<2> secret 이름
<3> route53에서 관리하고 있는 도메인
<4> ClusterIssuer 이름 (1번 과정에서 생성한 ClusterIssuer 이름과 동일) 
. *ingress-controller에 해당 인증서를 기본 인증서로 사용* +
* api-gateway(traefik)일 경우 +
tlsstore.yaml을 생성한다. (traefik 설치되어 있다고 가정)
+
[source,yaml]
----
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default <1>
spec:
  defaultCertificate:
    secretName: tls-acme-secret
----
+
<1> TLS 인증서가 secret 형태로 생성되길 원하는 네임스페이스

* nginx-ingress-controller일 경우 +
nginx-ingress-controller 파드의 arg를 추가한다.
+
[source,yaml]
----
containers:
- args:
    - --default-ssl-certificate=default/tls-acme-secret
----
