= 폼 에디터 설정 항목 참조
:toc:
:toc-title:

== A

[#Affinity]
=== Affinity
****
▼ Node Affinity +
│  ▼ Preferred During Scheduling Ignored During Execution +
│  │  ▼ Preference * +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  ▼ Match Fields +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  weight * +
│  ▼ Required During Scheduling Ignored During Execution +
│  │  ▼ Node Selector Terms * +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  ▼ Match Fields +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
▼ Pod Affinity +
│  ▼ Preferred During Scheduling Ignored During Execution +
│  │  ▼ Pod Affinity Term * +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key * +
│  │  │  │  │  operator * +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  │  matchLabels +
│  │  │  ▼ Namespaces +
│  │  │  │  Value * +
│  │  │  topologyKey * +
│  │  weight * +
│  ▼ Required During Scheduling Ignored During Execution +
│  │  ▼ Label Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  ▼ Namespaces +
│  │  │  Value * +
│  │  topologyKey * +
▼ Pod Anti Affinity +
│  ▼ Preferred During Scheduling Ignored During Execution +
│  │  ▼ Pod Affinity Term * +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key * +
│  │  │  │  │  operator * +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  │  matchLabels +
│  │  │  ▼ Namespaces +
│  │  │  │  Value * +
│  │  │  topologyKey * +
│  │  weight * +
│  ▼ Required During Scheduling Ignored During Execution +
│  │  ▼ Label Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  ▼ Namespaces +
│  │  │  Value * +
│  │  topologyKey *
****

[#AffinityRedis]
=== Affinity(Redis)
****
▼ Node Affinity +
│  ▼ Preferred During Scheduling Ignored During Execution +
│  │  ▼ Preference * +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  ▼ Match Fields +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  weight * +
│  ▼ Required During Scheduling Ignored During Execution +
│  │  ▼ Node Selector Terms * +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  ▼ Match Fields +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
▼ Pod Affinity +
│  ▼ Preferred During Scheduling Ignored During Execution +
│  │  ▼ Pod Affinity Term * +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key * +
│  │  │  │  │  operator * +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  │  matchLabels +
│  │  │  ▼ Namespace Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key * +
│  │  │  │  │  operator * +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  │  matchLabels +
│  │  │  ▼ Namespaces +
│  │  │  │  Value * +
│  │  │  topologyKey * +
│  │  weight * +
│  ▼ Required During Scheduling Ignored During Execution +
│  │  ▼ Label Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  ▼ Namespace Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  ▼ Namespaces +
│  │  │  Value * +
│  │  topologyKey * +
▼ Pod Anti Affinity +
│  ▼ Preferred During Scheduling Ignored During Execution +
│  │  ▼ Pod Affinity Term * +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key * +
│  │  │  │  │  operator * +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  │  matchLabels +
│  │  │  ▼ Namespace Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key * +
│  │  │  │  │  operator * +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  │  matchLabels +
│  │  │  ▼ Namespaces +
│  │  │  │  Value * +
│  │  │  topologyKey * +
│  │  weight * +
│  ▼ Required During Scheduling Ignored During Execution +
│  │  ▼ Label Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  ▼ Namespace Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  ▼ Namespaces +
│  │  │  Value * +
│  │  topologyKey *
****

[#AllowedTopologies]
=== Allowed Topologies
****
▼ Match Label Expressions +
│  key * +
│  ▼ Values * +
│  │  Value
****

[#Authentication]
=== Authentication
****
▼ Access Token +
│  key * +
│  secretName * +
accessTokenIsJwt +
audience +
▼ Certificate And Key +
│  certificate * +
│  key * +
│  secretName * +
clientId +
▼ Client Secret +
│  key * +
│  secretName * +
disableTlsHostnameVerification +
maxTokenExpirySeconds +
▼ Password Secret +
│  password * +
│  secretName * +
▼ Refresh Token +
│  key * +
│  secretName * +
scope +
▼ Tls Trusted Certificates +
│  certificate * +
│  secretName * +
tokenEndpointUri +
type * +
username
****

== B

[#Backend]
=== Backend
****
▼ Resource +
│  apiGroup +
│  kind * +
│  name * +
serviceName +
▼ Service Port +
│  integer +
│  string
****

[#Behavior]
=== Behavior
****
▼ Scale Down +
│  ▼ Policies +
│  │  periodSeconds * +
│  │  type * +
│  │  value * +
│  selectPolicy +
│  stabilizationWindowSeconds +
▼ Scale Up +
│  ▼ Policies +
│  │  periodSeconds * +
│  │  type * +
│  │  value * +
│  selectPolicy +
│  stabilizationWindowSeconds
****

[#Build]
=== Build
****
▼ Output * +
│  ▼ Additional Kaniko Options +
│  │  Value * +
│  image * +
│  pushSecret +
│  type * +
▼ Plugins * +
│  ▼ Artifacts * +
│  │  artifact +
│  │  fileName +
│  │  group +
│  │  insecure +
│  │  repository +
│  │  sha512sum +
│  │  type * +
│  │  url +
│  │  version +
│  name *
****

== C

[#Cephfs]
=== Cephfs
****
▼ Monitors * +
│  Value +
path +
readOnly +
secretFile +
▼ Secret Ref +
│  name +
│  namespace +
user
****

[#Cinder]
=== Cinder
****
fsType +
readOnly +
▼ Secret Ref +
│  name +
│  namespace +
volumeID *
****

[#Clusters]
=== Clusters
****
alias * +
▶ <<Authentication>> +
bootstrapServers * +
▼ Tls * +
│  ▼ Trusted Certificates +
│  │  certificate * +
│  │  secretName *
****

[#ConfigPatches]
=== Config Patches
****
applyTo +
▼ Match +
│  ▼ Cluster +
│  │  name +
│  │  portNumber +
│  │  service +
│  │  subset +
│  context +
│  ▼ Listener +
│  │  ▼ Filter Chain +
│  │  │  applicationProtocols +
│  │  │  ▼ Filter +
│  │  │  │  name +
│  │  │  │  ▼ Sub Filter +
│  │  │  │  │  name +
│  │  │  name +
│  │  │  sni +
│  │  │  transportProtocol +
│  │  name +
│  │  portName +
│  │  portNumber +
│  ▼ Proxy +
│  │  ▼ Metadata +
│  │  │  KEY +
│  │  │  VALUE +
│  │  proxyVersion +
│  ▼ Route Configuration +
│  │  gateway +
│  │  name +
│  │  portName +
│  │  portNumber +
│  │  ▼ Vhost +
│  │  │  name +
│  │  │  ▼ Route +
│  │  │  │  action +
│  │  │  │  name +
▼ Patch +
│  operation
****

[#Containers]
=== Containers
****
▼ Args +
│  Value * +
▼ Command +
│  Value * +
▶ <<Env>> +
▶ <<Env From>> +
image * +
imagePullPolicy +
▶ <<Lifecycle>> +
▶ <<Liveness Probe>> +
name * +
▼ Ports +
│  containerPort * +
│  hostIP +
│  hostPort +
│  name +
│  protocol +
▶ <<Readiness Probe>> +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE +
▼ Security Context +
│  allowPrivilegeEscalation +
│  ▼ Capabilities +
│  │  ▼ Add +
│  │  │  Value * +
│  │  ▼ Drop +
│  │  │  Value * +
│  privileged +
│  procMount +
│  readOnlyRootFilesystem +
│  runAsGroup +
│  runAsNonRoot +
│  runAsUser +
│  ▼ Se Linux Options +
│  │  level +
│  │  role +
│  │  type +
│  │  user +
│  ▼ Seccomp Profile +
│  │  localhostProfile +
│  │  type * +
│  ▼ Windows Options +
│  │  gmsaCredentialSpec +
│  │  gmsaCredentialSpecName +
│  │  runAsUserName +
▶ <<Startup Probe>> +
stdin +
stdinOnce +
terminationMessagePath +
terminationMessagePolicy +
tty +
▼ Volume Devices +
│  devicePath * +
│  name * +
▼ Volume Mounts +
│  mountPath * +
│  mountPropagation +
│  name * +
│  readOnly +
│  subPath +
│  subPathExpr +
workingDir
****

[#CruiseControl]
=== Cruise Control
****
▼ Broker Capacity +
│  cpuUtilization +
│  disk +
│  inboundNetwork +
│  outboundNetwork +
image +
▶ <<Jvm Options>> +
▼ Liveness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▶ <<Logging>> +
▶ <<Metrics Config>> +
▼ Readiness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▼ Template +
│  ▼ Api Service +
│  │  ▼ Ip Families +
│  │  │  Value * +
│  │  ipFamilyPolicy +
│  ▼ Cruise Control Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ Pod +
│  │  ▶ <<Affinity>> +
│  │  enableServiceLinks +
│  │  ▼ Host Aliases +
│  │  │  ▼ Hostnames +
│  │  │  │  Value * +
│  │  │  ip +
│  │  ▼ Image Pull Secrets +
│  │  │  name +
│  │  priorityClassName +
│  │  schedulerName +
│  │  ▼ Security Context +
│  │  │  fsGroup +
│  │  │  fsGroupChangePolicy +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Supplemental Groups +
│  │  │  │  Value * +
│  │  │  ▼ Sysctls +
│  │  │  │  name +
│  │  │  │  value +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  │  terminationGracePeriodSeconds +
│  │  tmpDirSizeLimit +
│  │  ▼ Tolerations +
│  │  │  effect +
│  │  │  key +
│  │  │  operator +
│  │  │  tolerationSeconds +
│  │  │  value +
│  │  ▼ Topology Spread Constraints +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key +
│  │  │  │  │  operator +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  maxSkew +
│  │  │  topologyKey +
│  │  │  whenUnsatisfiable +
│  ▼ Pod Disruption Budget +
│  │  maxUnavailable +
│  ▼ Tls Sidecar Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
▶ <<Tls Sidecar>> +
****

[#Csi]
=== Csi
****
▼ Controller Publish Secret Ref +
│  name +
│  namespace +
driver * +
fsType +
▼ Node Publish Secret Ref +
│  name +
│  namespace +
▼ Node Stage Secret Ref +
│  name +
│  namespace +
readOnly +
▼ Volume Attributes +
│  KEY +
│  VALUE +
volumeHandle *
****

[#CustomResourceConversion]
=== Custom Resource Conversion
****
strategy * +
▼ Webhook +
│  ▼ Client Config +
│  │  caBundle +
│  │  ▼ Service +
│  │  │  name * +
│  │  │  namespace * +
│  │  │  path +
│  │  │  port +
│  │  url +
│  ▼ Conversion Review Versions * +
│  │  Value
****

[#CustomResourceDefinitionNames]
=== Custom Resource Definition Names
****
▼ Categories +
│  Value +
kind * +
listKind +
plural * +
▼ Short Names +
│  Value +
singular
****

== D

[#DnsConfig]
=== Dns Config
****
▼ Nameservers +
│  Value * +
▼ Options +
│  name +
│  value +
▼ Searches +
│  Value *
****

== E

[#Egress]
=== Egress
****
▼ Ports +
│  port +
│  protocol +
▼ To +
│  ▼ Ip Block +
│  │  cidr * +
│  │  ▼ Except +
│  │  │  Value +
│  ▼ Namespace Selector +
│  │  ▼ Match Expressions +
│  │  │  key * +
│  │  │  operator * +
│  │  │  ▼ Values +
│  │  │  │  Value +
│  │  matchLabels +
│  ▼ Pod Selector +
│  │  ▼ Match Expressions +
│  │  │  key * +
│  │  │  operator * +
│  │  │  ▼ Values +
│  │  │  │  Value +
│  │  matchLabels
****

[#EntityOperator]
=== Entity Operator
****
▼ Template +
│  ▼ Pod +
│  │  ▶ <<Affinity>> +
│  │  enableServiceLinks +
│  │  ▶ <<Host Aliases>> +
│  │  ▼ Image Pull Secrets +
│  │  │  name +
│  │  priorityClassName +
│  │  schedulerName +
│  │  ▶ <<Security Context>> +
│  │  terminationGracePeriodSeconds +
│  │  tmpDirSizeLimit +
│  │  ▼ Tolerations +
│  │  │  effect +
│  │  │  key +
│  │  │  operator +
│  │  │  tolerationSeconds +
│  │  │  value +
│  │  ▶ <<Topology Spread Constraints>> +
│  ▼ Tls Sidecar Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ Topic Operator Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ User Operator Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
▶ <<Tls Sidecar>> +
▼ Topic Operator +
│  image +
│  ▶ <<Jvm Options>> +
│  ▼ Liveness Probe +
│  │  failureThreshold +
│  │  initialDelaySeconds +
│  │  periodSeconds +
│  │  successThreshold +
│  │  timeoutSeconds +
│  ▶ <<Logging>> +
│  ▼ Readiness Probe +
│  │  failureThreshold +
│  │  initialDelaySeconds +
│  │  periodSeconds +
│  │  successThreshold +
│  │  timeoutSeconds +
│  reconciliationIntervalSeconds +
│  ▼ Startup Probe +
│  │  failureThreshold +
│  │  initialDelaySeconds +
│  │  periodSeconds +
│  │  successThreshold +
│  │  timeoutSeconds +
│  topicMetadataMaxAttempts +
│  watchedNamespace +
│  zookeeperSessionTimeoutSeconds +
▼ User Operator +
│  image +
│  ▶ <<Jvm Options>> +
│  ▼ Liveness Probe +
│  │  failureThreshold +
│  │  initialDelaySeconds +
│  │  periodSeconds +
│  │  successThreshold +
│  │  timeoutSeconds +
│  ▶ <<Logging>> +
│  ▼ Readiness Probe +
│  │  failureThreshold +
│  │  initialDelaySeconds +
│  │  periodSeconds +
│  │  successThreshold +
│  │  timeoutSeconds +
│  reconciliationIntervalSeconds +
│  secretPrefix +
│  watchedNamespace +
│  zookeeperSessionTimeoutSeconds +
****

[#Env]
=== Env
****
name * +
value +
▼ Value From +
│  ▼ Config Map Key Ref +
│  │  key * +
│  │  name +
│  │  optional +
│  ▼ Field Ref +
│  │  apiVersion +
│  │  fieldPath * +
│  ▼ Resource Field Ref +
│  │  containerName +
│  │  divisor +
│  │  resource * +
│  ▼ Secret Key Ref +
│  │  key * +
│  │  name +
│  │  optional
****

[#EnvFrom]
=== Env From
****
▼ Config Map Ref +
│  name +
│  optional +
prefix +
▼ Secret Ref +
│  name +
│  optional
****

[#EphemeralContainers]
=== Ephemeral Containers
****
▼ Args +
│  Value * +
▼ Command +
│  Value * +
▶ <<Env>> +
▶ <<Env From>> +
image +
imagePullPolicy +
▶ <<Lifecycle>> +
▶ <<Liveness Probe>> +
name * +
▼ Ports +
│  containerPort * +
│  hostIP +
│  hostPort +
│  name +
│  protocol +
▶ <<Readiness Probe>> +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE +
▼ Security Context +
│  allowPrivilegeEscalation +
│  ▼ Capabilities +
│  │  ▼ Add +
│  │  │  Value * +
│  │  ▼ Drop +
│  │  │  Value * +
│  privileged +
│  procMount +
│  readOnlyRootFilesystem +
│  runAsGroup +
│  runAsNonRoot +
│  runAsUser +
│  ▼ Se Linux Options +
│  │  level +
│  │  role +
│  │  type +
│  │  user +
│  ▼ Seccomp Profile +
│  │  localhostProfile +
│  │  type * +
│  ▼ Windows Options +
│  │  gmsaCredentialSpec +
│  │  gmsaCredentialSpecName +
│  │  runAsUserName +
▶ <<Startup Probe>> +
stdin +
stdinOnce +
targetContainerName +
terminationMessagePath +
terminationMessagePolicy +
tty +
▼ Volume Devices +
│  devicePath * +
│  name * +
▼ Volume Mounts +
│  mountPath * +
│  mountPropagation +
│  name * +
│  readOnly +
│  subPath +
│  subPathExpr +
workingDir
****

[#ExternalConfiguration]
=== External Configuration
****
▼ Env +
│  name * +
│  ▼ Value From * +
│  │  ▼ Config Map Key Ref +
│  │  │  key +
│  │  │  name +
│  │  │  optional +
│  │  ▼ Secret Key Ref +
│  │  │  key +
│  │  │  name +
│  │  │  optional +
▼ Volumes +
│  ▼ Config Map +
│  │  defaultMode +
│  │  ▼ Items +
│  │  │  key +
│  │  │  mode +
│  │  │  path +
│  │  name +
│  │  optional +
│  name * +
│  ▼ Secret +
│  │  defaultMode +
│  │  ▼ Items +
│  │  │  key +
│  │  │  mode +
│  │  │  path +
│  │  optional +
│  │  secretName
****

== F

[#Fc]
=== Fc
****
fsType +
lun +
readOnly +
▼ Target WW Ns +
│  Value +
▼ Wwids +
│  Value
****

[#Filters]
=== Filters
****
filterName +
filterType +
▼ Insert Position +
│  index +
│  relativeTo +
▼ Listener Match +
│  ▼ Address +
│  │  Value * +
│  listenerProtocol +
│  listenerType +
│  portNamePrefix +
│  portNumber +
****

[#FlexVolume]
=== Flex Volume
****
driver * +
fsType +
▼ Options +
│  KEY +
│  VALUE +
readOnly +
▼ Secret Ref +
│  name +
│  namespace
****

== G

[#Git]
=== Git
****
apiUrl +
repository * +
▼ Token * +
│  value +
│  ▼ Value From +
│  │  ▼ Secret Key Ref * +
│  │  │  key * +
│  │  │  name +
│  │  │  optional +
type *
****

== H

[#HostAliases]
=== Host Aliases
****
▼ Hostnames +
│  Value * +
ip
****

[#Http]
=== Http
****
▼ Cors Policy +
│  allowCredentials +
│  ▼ Allow Headers +
│  │  Value * +
│  ▼ Allow Methods +
│  │  Value * +
│  ▼ Allow Origin +
│  │  Value * +
│  ▼ Allow Origins +
│  │  exact +
│  │  prefix +
│  │  regex +
│  ▼ Expose Headers +
│  │  Value * +
│  maxAge +
▼ Fault +
│  ▼ Abort +
│  │  grpcStatus +
│  │  http2Error +
│  │  httpStatus +
│  │  ▼ Percentage +
│  │  │  value +
│  ▼ Delay +
│  │  exponentialDelay +
│  │  fixedDelay +
│  │  percent +
│  │  ▼ Percentage +
│  │  │  value +
▼ Headers +
│  ▼ Request +
│  │  ▼ Add +
│  │  │  KEY +
│  │  │  VALUE +
│  │  ▼ Remove +
│  │  │  Value * +
│  │  ▼ Set +
│  │  │  KEY +
│  │  │  VALUE +
│  ▼ Response +
│  │  ▼ Add +
│  │  │  KEY +
│  │  │  VALUE +
│  │  ▼ Remove +
│  │  │  Value * +
│  │  ▼ Set +
│  │  │  KEY +
│  │  │  VALUE +
▼ Match +
│  ▼ Authority +
│  │  exact +
│  │  prefix +
│  │  regex +
│  ▼ Gateways +
│  │  Value * +
│  ▼ Headers +
│  │  KEY +
│  │  VALUE +
│  ignoreUriCase +
│  ▼ Method +
│  │  exact +
│  │  prefix +
│  │  regex +
│  name +
│  port +
│  ▼ Query Params +
│  │  KEY +
│  │  VALUE +
│  ▼ Scheme +
│  │  exact +
│  │  prefix +
│  │  regex +
│  sourceLabels +
│  ▼ Uri +
│  │  exact +
│  │  prefix +
│  │  regex +
▼ Mirror +
│  host +
│  ▼ Port +
│  │  number +
│  subset +
mirrorPercent +
▼ Mirror Percentage +
│  value +
mirror_percent +
name +
▼ Redirect +
│  authority +
│  redirectCode +
│  uri +
▼ Retries +
│  attempts +
│  perTryTimeout +
│  retryOn +
▼ Rewrite +
│  authority +
│  uri +
▼ Route +
│  ▼ Destination +
│  │  host +
│  │  ▼ Port +
│  │  │  number +
│  │  subset +
│  ▼ Headers +
│  │  ▼ Request +
│  │  │  ▼ Add +
│  │  │  │  KEY +
│  │  │  │  VALUE +
│  │  │  ▼ Remove +
│  │  │  │  Value * +
│  │  │  ▼ Set +
│  │  │  │  KEY +
│  │  │  │  VALUE +
│  │  ▼ Response +
│  │  │  ▼ Add +
│  │  │  │  KEY +
│  │  │  │  VALUE +
│  │  │  ▼ Remove +
│  │  │  │  Value * +
│  │  │  ▼ Set +
│  │  │  │  KEY +
│  │  │  │  VALUE +
│  weight +
timeout
****

[#HttpKafka]
=== Http(Kafka)
****
▼ Cors +
│  ▼ Allowed Methods * +
│  │  Value * +
│  ▼ Allowed Origins * +
│  │  Value * +
port
****

== I

[#Ingress]
=== Ingress
****
▼ From +
│  ▼ Ip Block +
│  │  cidr * +
│  │  ▼ Except +
│  │  │  Value +
│  ▼ Namespace Selector +
│  │  ▼ Match Expressions +
│  │  │  key * +
│  │  │  operator * +
│  │  │  ▼ Values +
│  │  │  │  Value +
│  │  matchLabels +
│  ▼ Pod Selector +
│  │  ▼ Match Expressions +
│  │  │  key * +
│  │  │  operator * +
│  │  │  ▼ Values +
│  │  │  │  Value +
│  │  matchLabels +
▼ Ports +
│  port +
│  protocol
****

[#Iscsi]
=== Iscsi
****
chapAuthDiscovery +
chapAuthSession +
fsType +
initiatorName +
iqn * +
iscsiInterface +
lun * +
▼ Portals +
│  Value +
readOnly +
▼ Secret Ref +
│  name +
│  namespace +
targetPortal *
****

== J

[#JmxOptionss]
=== Jmx Options
****
▼ Authentication +
│  type *
****

[#JmxTrans]
=== Jmx Trans
****
image +
▼ Kafka Queries * +
│  ▼ Attributes * +
│  │  Value * +
│  ▼ Outputs * +
│  │  Value * +
│  targetMBean * +
logLevel +
▼ Output Definitions * +
│  flushDelayInSeconds +
│  host +
│  name * +
│  outputType * +
│  port +
│  ▼ Type Names +
│  │  Value * +
▼ Template +
│  ▼ Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ Pod +
│  │  ▶ <<Affinity>> +
│  │  enableServiceLinks +
│  │  ▶ <<Host Aliases>> +
│  │  ▼ Image Pull Secrets +
│  │  │  name +
│  │  priorityClassName +
│  │  schedulerName +
│  │  ▶ <<Security Context>> +
│  │  terminationGracePeriodSeconds +
│  │  tmpDirSizeLimit +
│  │  ▼ Tolerations +
│  │  │  effect +
│  │  │  key +
│  │  │  operator +
│  │  │  tolerationSeconds +
│  │  │  value +
│  │  ▶ <<Topology Spread Constraints>>
****


[#Jobs]
=== Jobs
****
▶ <<Post Submit / Pre Submit,Post Submit>> +
▶ <<Post Submit / Pre Submit,Pre Submit>> +
****

[#JobTemplate]
=== Job Template
****
▶ <<Metadata>> +
▼ Spec * +
│  activeDeadlineSeconds +
│  backoffLimit +
│  completions +
│  manualSelector +
│  parallelism +
│  ▶ <<Selector>> +
│  ▼ Template * +
│  │  ▶ <<Metadata>> +
│  │  ▼ Spec * +
│  │  │  activeDeadlineSeconds +
│  │  │  ▶ <<Affinity>> +
│  │  │  automountServiceAccountToken +
│  │  │  ▶ <<Containers>> * +
│  │  │  ▶ <<Dns Config>> +
│  │  │  dnsPolicy +
│  │  │  enableServiceLinks +
│  │  │  ▶ <<Ephemeral Containers>> +
│  │  │  ▶ <<Host Aliases>> +
│  │  │  hostIPC +
│  │  │  hostNetwork +
│  │  │  hostPID +
│  │  │  hostname +
│  │  │  ▼ Image Pull Secrets +
│  │  │  │  name +
│  │  │  ▶ <<Containers,Init Containers>> +
│  │  │  nodeName +
│  │  │  nodeSelector +
│  │  │  ▼ Overhead +
│  │  │  │  KEY +
│  │  │  │  VALUE +
│  │  │  preemptionPolicy +
│  │  │  priority +
│  │  │  priorityClassName +
│  │  │  ▼ Readiness Gates +
│  │  │  │  conditionType * +
│  │  │  restartPolicy +
│  │  │  runtimeClassName +
│  │  │  schedulerName +
│  │  │  ▶ <<Security Context>> +
│  │  │  serviceAccountName +
│  │  │  setHostnameAsFQDN +
│  │  │  shareProcessNamespace +
│  │  │  subdomain +
│  │  │  terminationGracePeriodSeconds +
│  │  │  ▼ Tolerations +
│  │  │  │  effect +
│  │  │  │  key +
│  │  │  │  operator +
│  │  │  │  tolerationSeconds +
│  │  │  │  value +
│  │  │  ▶ <<Topology Spread Constraints>> +
│  │  │  ▶ <<Volumes>> +
│  ttlSecondsAfterFinished
****

[#JvmOptions]
=== Jvm Options
****
-Xms +
-Xmx +
gcLoggingEnabled +
▼ Java System Properties +
│  name +
│  value +
****

[#JwtRules]
=== Jwt Rules
****
▼ Audiences +
│  Value * +
forwardOriginalToken +
▼ From Headers +
│  name +
│  prefix +
▼ From Params +
│  Value * +
issuer +
jwks +
jwksUri +
jwks_uri +
outputPayloadToHeader
****

== K

[#Kafka]
=== Kafka
****
▼ Authorization +
│  allowOnError +
│  authorizerClass +
│  clientId +
│  delegateToKafkaAcls +
│  disableTlsHostnameVerification +
│  expireAfterMs +
│  grantsRefreshPeriodSeconds +
│  grantsRefreshPoolSize +
│  initialCacheCapacity +
│  maximumCacheSize +
│  ▼ Super Users +
│  │  Value * +
│  supportsAdminApi +
│  ▼ Tls Trusted Certificates +
│  │  certificate * +
│  │  secretName * +
│  tokenEndpointUri +
│  type * +
│  url +
brokerRackInitImage +
image +
▶ <<Jmx Options>> +
▶ <<Jvm Options>> +
▼ Listeners * +
│  ▼ Authentication +
│  │  accessTokenIsJwt +
│  │  checkAccessTokenType +
│  │  checkAudience +
│  │  checkIssuer +
│  │  clientAudience +
│  │  clientId +
│  │  clientScope +
│  │  ▼ Client Secret +
│  │  │  key * +
│  │  │  secretName * +
│  │  customClaimCheck +
│  │  disableTlsHostnameVerification +
│  │  enableECDSA +
│  │  enableOauthBearer +
│  │  enablePlain +
│  │  fallbackUserNameClaim +
│  │  fallbackUserNamePrefix +
│  │  introspectionEndpointUri +
│  │  jwksEndpointUri +
│  │  jwksExpirySeconds +
│  │  jwksMinRefreshPauseSeconds +
│  │  jwksRefreshSeconds +
│  │  maxSecondsWithoutReauthentication +
│  │  ▼ Tls Trusted Certificates +
│  │  │  certificate * +
│  │  │  secretName * +
│  │  tokenEndpointUri +
│  │  type * +
│  │  userInfoEndpointUri +
│  │  userNameClaim +
│  │  validIssuerUri +
│  │  validTokenType +
│  ▼ Configuration +
│  │  ▼ Bootstrap +
│  │  │  ▼ Alternative Names +
│  │  │  │  Value * +
│  │  │  host +
│  │  │  loadBalancerIP +
│  │  │  nodePort +
│  │  ▼ Broker Cert Chain And Key +
│  │  │  certificate * +
│  │  │  key * +
│  │  │  secretName * +
│  │  ▼ Brokers +
│  │  │  advertisedHost +
│  │  │  advertisedPort +
│  │  │  broker * +
│  │  │  host +
│  │  │  loadBalancerIP +
│  │  │  nodePort +
│  │  class +
│  │  externalTrafficPolicy +
│  │  ▼ Finalizers +
│  │  │  Value * +
│  │  ▼ Ip Families +
│  │  │  Value * +
│  │  ipFamilyPolicy +
│  │  ▼ Load Balancer Source Ranges +
│  │  │  Value * +
│  │  maxConnectionCreationRate +
│  │  maxConnections +
│  │  preferredNodePortAddressType +
│  │  useServiceDnsDomain +
│  name * +
│  ▼ Network Policy Peers +
│  │  ▼ Ip Block +
│  │  │  cidr +
│  │  │  ▼ Except +
│  │  │  │  Value * +
│  │  ▼ Namespace Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key +
│  │  │  │  operator +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  ▼ Pod Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key +
│  │  │  │  operator +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  port * +
│  tls * +
│  type * +
▼ Liveness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▶ <<Logging>> +
▶ <<Metrics Config>> +
▼ Rack +
│  topologyKey * +
▼ Readiness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
replicas * +
▼ Storage * +
│  class +
│  deleteClaim +
│  id +
│  ▼ Overrides +
│  │  broker +
│  │  class +
│  size +
│  sizeLimit +
│  type * +
│  ▼ Volumes +
│  │  class +
│  │  deleteClaim +
│  │  id +
│  │  ▼ Overrides +
│  │  │  broker +
│  │  │  class +
│  │  size +
│  │  sizeLimit +
│  │  type * +
▼ Template * +
│  ▼ Bootstrap Service +
│  │  ▼ Ip Families +
│  │  │  Value * +
│  │  ipFamilyPolicy +
│  ▼ Brokers Service +
│  │  ▼ Ip Families +
│  │  │  Value * +
│  │  ipFamilyPolicy +
│  ▼ Init Container +
│  │  ▼ Env +
│  │  │  value +
│  │  │  name +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ Kafka Container +
│  │  ▼ Env +
│  │  │  value +
│  │  │  name +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ Pod +
│  │  ▶ <<Affinity>> +
│  │  enableServiceLinks +
│  │  ▶ <<<Host Aliases>> +
│  │  ▼ Image Pull Secrets +
│  │  │  name +
│  │  priorityClassName +
│  │  schedulerName +
│  │  ▶ <<Security Context>> +
│  │  terminationGracePeriodSeconds +
│  │  tmpDirSizeLimit +
│  │  ▼ Tolerations +
│  │  │  effect +
│  │  │  key +
│  │  │  operator +
│  │  │  tolerationSeconds +
│  │  │  value +
│  │  ▼ Topology Spread Constraints +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key +
│  │  │  │  │  operator +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  maxSkew +
│  │  │  topologyKey +
│  │  │  whenUnsatisfiable +
│  ▼ Pod Disruption Budget +
│  │  maxUnavailable +
│  ▼ Statefulset +
│  │  podManagementPolicy +
version
****

[#KafkaExporter]
=== Kafka Exporter
****
enableSaramaLogging +
groupRegex +
image +
▼ Liveness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
logging +
▼ Readiness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▼ Template +
│  ▼ Container +
│  │  ▼ Env +
│  │  │  value +
│  │  │  name +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
│  ▼ Pod +
│  │  ▶ <<Affinity>> +
│  │  enableServiceLinks +
│  │  ▶ <<Host Aliases>> +
│  │  ▼ Image Pull Secrets +
│  │  │  name +
│  │  priorityClassName +
│  │  schedulerName +
│  │  ▶ <<Security Context>> +
│  │  terminationGracePeriodSeconds +
│  │  tmpDirSizeLimit +
│  │  ▼ Tolerations +
│  │  │  effect +
│  │  │  key +
│  │  │  operator +
│  │  │  tolerationSeconds +
│  │  │  value +
│  │  ▼ Topology Spread Constraints +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key +
│  │  │  │  │  operator +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  maxSkew +
│  │  │  topologyKey +
│  │  │  whenUnsatisfiable +
topicRegex
****

[#KubernetesConfig]
=== Kubernetes Config
****
image * +
imagePullPolicy * +
▼ Image Pull Secrets +
│  name +
▼ Redis Secret +
│  key +
│  name +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE +
****

== L

[#Lifecycle]
=== Lifecycle
****
▼ Post Start +
│  ▼ Exec +
│  │  ▼ Command +
│  │  │  Value *  +
│  ▼ Http Get +
│  │  host +
│  │  ▼ Http Headers +
│  │  │  name * +
│  │  │  value * +
│  │  path +
│  │  port * +
│  │  scheme +
│  ▼ Tcp Socket +
│  │  host +
│  │  port * +
▼ Pre Stop +
│  ▼ Exec +
│  │  ▼ Command +
│  │  │  Value *  +
│  ▼ Http Get +
│  │  host +
│  │  ▼ Http Headers +
│  │  │  name * +
│  │  │  value * +
│  │  path +
│  │  port * +
│  │  scheme +
│  ▼ Tcp Socket +
│  │  host +
│  │  port *
****

[#Limits]
=== Limits
****
▼ Default +
│  KEY +
│  VALUE +
▼ Default Request +
│  KEY +
│  VALUE +
▼ Max +
│  KEY +
│  VALUE +
▼ Max Limit Request Ratio +
│  KEY +
│  VALUE +
▼ Min +
│  KEY +
│  VALUE +
type
****

[#LivenessProbe]
=== Liveness Probe
****
▼ Exec +
│  ▼ Command +
│  │  Value * +
failureThreshold +
▼ Http Get +
│  host +
│  ▼ Http Headers +
│  │  name * +
│  │  value * +
│  path +
│  port * +
│  scheme +
initialDelaySeconds +
periodSeconds +
successThreshold +
▼ Tcp Socket +
│  host +
│  port * +
timeoutSeconds
****

[#Logging]
=== Logging
****
type * +
▼ Value From +
│  ▼ Config Map Key Ref +
│  │  key +
│  │  name +
│  │  optional +
****

== M

[#Metadata]
=== Metadata
****
annotations +
▼ Finalizers +
│  Value * +
generateName +
labels * +
▼ Managed Fields +
│  apiVersion +
│  fieldsType +
│  manager +
│  operation +
│  time +
name +
namespace +
▼ Owner References +
│  apiVersion * +
│  blockOwnerDeletion +
│  controller +
│  kind * +
│  name * +
│  uid *
****

[#Metrics]
=== Metrics
****
▼ External +
│  ▼ Metric * +
│  │  name * +
│  │  ▼ Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value +
│  │  │  matchLabels +
│  ▼ Target * +
│  │  averageUtilization +
│  │  averageValue +
│  │  type * +
│  │  value +
▼ Object +
│  ▼ Described Object * +
│  │  apiVersion +
│  │  kind * +
│  │  name * +
│  ▼ Metric * +
│  │  name * +
│  │  ▼ Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  ▼ Target * +
▼ Pods +
│  ▼ Metric * +
│  │  name * +
│  │  ▼ Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value +
│  │  │  matchLabels +
│  ▼ Target * +
│  │  averageUtilization +
│  │  averageValue +
│  │  type * +
│  │  value +
▼ Resource +
│  name * +
│  ▼ Target * +
│  │  averageUtilization +
│  │  averageValue +
│  │  type * +
│  │  value +
type *
****

[#MetricsConfig]
=== Metrics Config
****
type * +
▼ Value From * +
│  ▼ Config Map Key Ref +
│  │  key +
│  │  name +
│  │  optional +
****

[#Mirrors]
=== Mirrors
****
▼ Checkpoint Connector +
│  pause +
│  tasksMax +
groupsBlacklistPattern +
groupsExcludePattern +
groupsPattern +
▼ Heartbeat Connector +
│  pause +
│  tasksMax +
sourceCluster * +
▼ Source Connector +
│  pause +
│  tasksMax +
targetCluster * +
topicsBlacklistPattern +
topicsExcludePattern +
topicsPattern
****

== N

[#NodeAffinity]
=== Node Affinity
****
▼ Required +
│  ▼ Node Selector Terms * +
│  │  ▼ Match Expressions +
│  │  │  key * +
│  │  │  operator * +
│  │  │  ▼ Values +
│  │  │  │  Value +
│  │  ▼ Match Fields +
│  │  │  key * +
│  │  │  operator * +
│  │  │  ▼ Values +
│  │  │  │  Value
****

== P

[#ParametersFrom]
=== Parameters From
****
▼ Secret Key Ref +
│  key * +
│  name *
****

[#PodTemplate]
=== Pod Template
****
▶ <<Affinity>> +
automountServiceAccountToken +
▶ <<Dns Config>> +
dnsPolicy +
enableServiceLinks +
hostNetwork +
▼ Image Pull Secrets +
│  name +
nodeSelector +
priorityClassName +
runtimeClassName +
schedulerName +
▼ Security Context +
│  fsGroup +
│  fsGroupChangePolicy +
│  runAsGroup +
│  runAsNonRoot +
│  runAsUser +
│  ▼ Se Linux Options +
│  │  level +
│  │  role +
│  │  type +
│  │  user +
│  ▼ Supplemental Groups +
│  │  Value * +
│  ▼ Sysctls +
│  │  name * +
│  │  value * +
│  ▼ Windows Options +
│  │  gmsaCredentialSpec +
│  │  gmsaCredentialSpecName +
│  │  runAsUserName +
▼ Tolerations +
│  effect +
│  key +
│  operator +
│  tolerationSeconds +
│  value +
▼ Volumes +
│  ▼ Aws Elastic Block Store +
│  │  fsType +
│  │  partition +
│  │  readOnly +
│  │  volumeID * +
│  ▼ Azure Disk +
│  │  cachingMode +
│  │  diskName * +
│  │  diskURI * +
│  │  fsType +
│  │  kind +
│  │  readOnly +
│  ▼ Azure File +
│  │  readOnly +
│  │  secretName * +
│  │  shareName * +
│  ▼ Cephfs +
│  │  ▼ Monitors * +
│  │  │  Value * +
│  │  path +
│  │  readOnly +
│  │  secretFile +
│  │  ▼ Secret Ref +
│  │  │  name +
│  │  user +
│  ▼ Cinder +
│  │  fsType +
│  │  readOnly +
│  │  ▼ Secret Ref +
│  │  │  name +
│  │  volumeID * +
│  ▼ Config Map +
│  │  defaultMode +
│  │  ▼ Items +
│  │  │  key * +
│  │  │  mode +
│  │  │  path * +
│  │  name +
│  │  optional +
│  ▼ Csi +
│  │  driver * +
│  │  fsType +
│  │  ▼ Node Publish Secret Ref +
│  │  │  name +
│  │  readOnly +
│  │  ▼ Volume Attributes +
│  │  │  KEY +
│  │  │  VALUE +
│  ▼ Downward API +
│  │  defaultMode +
│  │  ▼ Items +
│  │  │  ▼ Field Ref +
│  │  │  │  apiVersion +
│  │  │  │  fieldPath * +
│  │  │  mode +
│  │  │  path * +
│  │  │  ▼ Resource Field Ref +
│  │  │  │  containerName +
│  │  │  │  divisor +
│  │  │  │  resource * +
│  ▼ Empty Dir +
│  │  medium +
│  │  sizeLimit +
│  ▼ Fc +
│  │  fsType +
│  │  lun +
│  │  readOnly +
│  │  ▼ Target WW Ns +
│  │  │  Value * +
│  │  ▼ Wwids +
│  │  │  Value * +
│  ▼ Flex Volume +
│  │  driver * +
│  │  fsType +
│  │  ▼ Options +
│  │  │  KEY +
│  │  │  VALUE +
│  │  readOnly +
│  │  ▼ Secret Ref +
│  │  │  name +
│  ▼ Flocker +
│  │  datasetName +
│  │  datasetUUID +
│  ▼ Gce Persistent Disk +
│  │  fsType +
│  │  partition +
│  │  pdName * +
│  │  readOnly +
│  ▼ Git Repo +
│  │  directory +
│  │  repository * +
│  │  revision +
│  ▼ Glusterfs +
│  │  endpoints * +
│  │  path * +
│  │  readOnly +
│  ▼ Host Path +
│  │  path * +
│  │  type +
│  ▼ Iscsi +
│  │  chapAuthDiscovery +
│  │  chapAuthSession +
│  │  fsType +
│  │  initiatorName +
│  │  iqn * +
│  │  iscsiInterface +
│  │  lun * +
│  │  ▼ Portals +
│  │  │  Value * +
│  │  readOnly +
│  │  ▼ Secret Ref +
│  │  │  name +
│  │  targetPortal * +
│  name * +
│  ▼ Nfs +
│  │  path * +
│  │  readOnly +
│  │  server * +
│  ▼ Persistent Volume Claim +
│  │  claimName * +
│  │  readOnly +
│  ▼ Photon Persistent Disk +
│  │  fsType +
│  │  pdID * +
│  ▼ Portworx Volume +
│  │  fsType +
│  │  readOnly +
│  │  volumeID * +
│  ▼ Projected +
│  │  defaultMode +
│  │  ▼ Sources * +
│  │  │  ▼ Config Map +
│  │  │  │  ▼ Items +
│  │  │  │  │  key * +
│  │  │  │  │  mode +
│  │  │  │  │  path * +
│  │  │  │  name +
│  │  │  │  optional +
│  │  │  ▼ Downward API +
│  │  │  │  ▼ Items +
│  │  │  │  │  ▼ Field Ref +
│  │  │  │  │  │  apiVersion +
│  │  │  │  │  │  fieldPath * +
│  │  │  │  │  mode +
│  │  │  │  │  path * +
│  │  │  │  │  ▼ Resource Field Ref +
│  │  │  │  │  │  containerName +
│  │  │  │  │  │  divisor +
│  │  │  │  │  │  resource * +
│  │  │  ▼ Secret +
│  │  │  │  ▼ Items +
│  │  │  │  │  key * +
│  │  │  │  │  mode +
│  │  │  │  │  path * +
│  │  │  │  name +
│  │  │  │  optional +
│  │  │  ▼ Service Account Token +
│  │  │  │  audience +
│  │  │  │  expirationSeconds +
│  │  │  │  path * +
│  ▼ Quobyte +
│  │  group +
│  │  readOnly +
│  │  registry * +
│  │  tenant +
│  │  user +
│  │  volume * +
│  ▼ Rbd +
│  │  fsType +
│  │  image * +
│  │  keyring +
│  │  ▼ Monitors * +
│  │  │  Value * +
│  │  pool +
│  │  readOnly +
│  │  ▼ Secret Ref +
│  │  │  name +
│  │  user +
│  ▼ Scale IO +
│  │  fsType +
│  │  gateway * +
│  │  protectionDomain +
│  │  readOnly +
│  │  ▼ Secret Ref * +
│  │  │  name +
│  │  sslEnabled +
│  │  storageMode +
│  │  storagePool +
│  │  system * +
│  │  volumeName +
│  ▼ Secret +
│  │  defaultMode +
│  │  ▼ Items +
│  │  │  key * +
│  │  │  mode +
│  │  │  path * +
│  │  optional +
│  │  secretName +
│  ▼ Storageos +
│  │  fsType +
│  │  readOnly +
│  │  ▼ Secret Ref +
│  │  │  name +
│  │  volumeName +
│  │  volumeNamespace +
│  ▼ Vsphere Volume +
│  │  fsType +
│  │  storagePolicyID +
│  │  storagePolicyName +
│  │  volumePath *
****

[#PostSubmit/PreSubmit]
=== Post Submit / Pre Submit
****
▼ After +
│  Value * +
▼ Approval +
│  ▼ Approvers +
│  │  Value * +
│  ▼ Approvers Config Map +
│  │  name +
│  requestMessage * +
▼ Args +
│  Value * +
▼ Command +
│  Value * +
▼ Email +
│  content * +
│  isHtml +
│  ▼ Receivers +
│  │  Value * +
│  title * +
▶ <<Env>> +
▶ <<Env From>> +
image +
imagePullPolicy +
▶ <<Lifecycle>> +
▶ <<Liveness Probe>> +
name * +
▼ Notification +
│  ▼ On Failure +
│  │  ▼ Email +
│  │  │  content * +
│  │  │  isHtml +
│  │  │  ▼ Receivers +
│  │  │  │  Value * +
│  │  │  title * +
│  │  ▼ Slack +
│  │  │  message * +
│  │  │  url * +
│  ▼ On Success +
│  │  ▼ Email +
│  │  │  content * +
│  │  │  isHtml +
│  │  │  ▼ Receivers +
│  │  │  │  Value * +
│  │  │  title * +
│  │  ▼ Slack +
│  │  │  message * +
│  │  │  url * +
▼ Ports +
│  containerPort * +
│  hostIP +
│  hostPort +
│  name +
│  protocol +
▶ <<Readiness Probe>> +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE +
script +
▼ Security Context +
│  allowPrivilegeEscalation +
│  ▼ Capabilities +
│  │  ▼ Add +
│  │  │  Value * +
│  │  ▼ Drop +
│  │  │  Value * +
│  privileged +
│  procMount +
│  readOnlyRootFilesystem +
│  runAsGroup +
│  runAsNonRoot +
│  runAsUser +
│  ▼ Se Linux Options +
│  │  level +
│  │  role +
│  │  type +
│  │  user +
│  ▼ Windows Options +
│  │  gmsaCredentialSpec +
│  │  gmsaCredentialSpecName +
│  │  runAsUserName +
skipCheckout +
▼ Slack +
│  message * +
│  url * +
▶ <<Startup Probe>> +
stdin +
stdinOnce +
▼ Tekton Task +
│  ▼ Params +
│  │  ▼ Array Val +
│  │  │  Value * +
│  │  name * +
│  │  stringVal +
│  ▼ Resources +
│  │  ▼ Inputs +
│  │  │  name +
│  │  │  ▼ Paths +
│  │  │  │  Value * +
│  │  │  ▼ Resource Ref +
│  │  │  │  apiVersion +
│  │  │  │  name +
│  │  │  ▼ Resource Spec +
│  │  │  │  description +
│  │  │  │  ▼ Params * +
│  │  │  │  │  name * +
│  │  │  │  │  value * +
│  │  │  │  ▼ Secrets +
│  │  │  │  │  fieldName * +
│  │  │  │  │  secretKey * +
│  │  │  │  │  secretName * +
│  │  │  │  type * +
│  │  ▼ Outputs +
│  │  │  name +
│  │  │  ▼ Paths +
│  │  │  │  Value * +
│  │  │  ▼ Resource Ref +
│  │  │  │  apiVersion +
│  │  │  │  name +
│  │  │  ▼ Resource Spec +
│  │  │  │  description +
│  │  │  │  ▼ Params * +
│  │  │  │  │  name * +
│  │  │  │  │  value * +
│  │  │  │  ▼ Secrets +
│  │  │  │  │  fieldName * +
│  │  │  │  │  secretKey * +
│  │  │  │  │  secretName * +
│  │  │  │  type * +
│  ▼ Task Ref * +
│  │  catalog +
│  │  ▼ Local +
│  │  │  apiVersion +
│  │  │  bundle +
│  │  │  kind +
│  │  │  name +
│  ▼ Workspaces +
│  │  name * +
│  │  subPath +
│  │  workspace * +
terminationMessagePath +
terminationMessagePolicy +
tty +
▼ Volume Devices +
│  devicePath * +
│  name * +
▼ Volume Mounts +
│  mountPath * +
│  mountPropagation +
│  name * +
│  readOnly +
│  subPath +
│  subPathExpr +
▼ When +
│  ▼ Branch +
│  │  Value * +
│  ▼ Skip Branch +
│  │  Value * +
│  ▼ Skip Tag +
│  │  Value * +
│  ▼ Tag +
│  │  Value * +
workingDir
****

== R

[#Rbd]
=== Rbd
****
fsType +
image * +
keyring +
▼ Monitors * +
│  Value +
pool +
readOnly +
▼ Secret Ref +
│  name +
│  namespace +
user
****

[#ReadinessProbe]
=== Readiness Probe
****
▼ Exec +
│  ▼ Command +
│  │  Value * +
failureThreshold +
▼ Http Get +
│  host +
│  ▼ Http Headers +
│  │  name * +
│  │  value * +
│  path +
│  port * +
│  scheme +
initialDelaySeconds +
periodSeconds +
successThreshold +
▼ Tcp Socket +
│  host +
│  port * +
timeoutSeconds
****

[RedisExporter]
=== Redis Exporter
****
enabled +
▼ Env +
│  name * +
│  value +
│  ▼ Value From +
│  │  ▼ Config Map Key Ref +
│  │  │  key * +
│  │  │  name +
│  │  │  optional +
│  │  ▼ Field Ref +
│  │  │  apiVersion +
│  │  │  fieldPath * +
│  │  ▼ Resource Field Ref +
│  │  │  containerName +
│  │  │  divisor +
│  │  │  resource * +
│  │  ▼ Secret Key Ref +
│  │  │  key * +
│  │  │  name +
│  │  │  optional +
image * +
imagePullPolicy +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE
****

[#RedisFollower/RedisLeader]
=== Redis Follower / Redis Leader
****
▶ <<AffinityRedis,Affinity>> +
▼ Liveness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▼ Pdb +
│  enabled +
│  maxUnavailable +
│  minAvailable +
▼ Readiness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▼ Redis Config +
│  additionalRedisConfig +
replicas
****

[#Resources]
=== Resources
****
▼ Requests +
│  storage
****

[#Rules]
=== Rules
****
▼ From +
│  ▼ Source +
│  │  ▼ Ip Blocks +
│  │  │  Value * +
│  │  ▼ Namespaces +
│  │  │  Value * +
│  │  ▼ Not Ip Blocks +
│  │  │  Value * +
│  │  ▼ Not Namespaces +
│  │  │  Value * +
│  │  ▼ Not Principals +
│  │  │  Value * +
│  │  ▼ Not Request Principals +
│  │  │  Value * +
│  │  ▼ Principals +
│  │  │  Value * +
│  │  ▼ Request Principals +
│  │  │  Value * +
▼ To +
│  ▼ Operation +
│  │  ▼ Hosts +
│  │  │  Value * +
│  │  ▼ Methods +
│  │  │  Value * +
│  │  ▼ Not Hosts +
│  │  │  Value * +
│  │  ▼ Not Methods +
│  │  │  Value * +
│  │  ▼ Not Paths +
│  │  │  Value * +
│  │  ▼ Not Ports +
│  │  │  Value * +
│  │  ▼ Paths +
│  │  │  Value * +
│  │  ▼ Ports +
│  │  │  Value * +
▼ When +
│  key +
│  ▼ Not Values +
│  │  Value * +
│  ▼ Values +
│  │  Value *
****

== S

[#ScaleIO]
=== Scale IO
****
fsType +
gateway * +
protectionDomain +
readOnly +
▼ Secret Ref * +
│  name +
│  namespace +
sslEnabled +
storageMode +
storagePool +
system * +
volumeName
****

[#SecurityContext]
=== Security Context
****
fsGroup +
fsGroupChangePolicy +
runAsGroup +
runAsNonRoot +
runAsUser +
▼ Se Linux Options +
│  level +
│  role +
│  type +
│  user +
▼ Seccomp Profile +
│  localhostProfile +
│  type * +
▼ Supplemental Groups +
│  Value * +
▼ Sysctls +
│  name * +
│  value * +
▼ Windows Options +
│  gmsaCredentialSpec +
│  gmsaCredentialSpecName +
│  runAsUserName
****

[#SecurityContextInferenceService]
=== Security Context(Inference Service)
****
allowPrivilegeEscalation +
▼ Capabilities +
│  ▼ Add +
│  │  Value * +
│  ▼ Drop +
│  │  Value * +
privileged +
procMount +
readOnlyRootFilesystem +
runAsGroup +
runAsNonRoot +
runAsUser +
▼ Se Linux Options +
│  level +
│  role +
│  type +
│  user +
▼ Seccomp Profile +
│  localhostProfile +
│  type * +
▼ Windows Options +
│  gmsaCredentialSpec +
│  gmsaCredentialSpecName +
│  runAsUserName +
****

[#SecurityContextRedis]
=== Security Context(Redis)
****
fsGroup +
fsGroupChangePolicy +
runAsGroup +
runAsNonRoot +
runAsUser +
▼ Se Linux Options +
│  level +
│  role +
│  type +
│  user +
▼ Seccomp Profile +
│  localhostProfile +
│  type * +
▼ Supplemental Groups +
│  Value * +
▼ Sysctls +
│  name * +
│  value * +
▼ Windows Options +
│  gmsaCredentialSpec +
│  gmsaCredentialSpecName +
│  hostProcess +
│  runAsUserName +
****

[#Selector]
=== Selector
****
▼ Match Expressions +
│  key * +
│  operator * +
│  ▼ Values +
│  │  Value +
matchLabels
****

NOTE: 디플로이먼트, 레플리카 셋, 데몬 셋, 스테이트풀 셋을 생성할 경우 matchLabels 항목은 필수 설정 항목이다.  

[#Servers]
=== Servers
****
binds +
defaultEndpoint +
▼ Hosts +
│  Value * +
▼ Port +
│  name +
│  number +
│  protocol +
▼ Tls +
│  caCertificates +
│  ▼ Cipher Suites +
│  │  Value * +
│  credentialName +
│  httpsRedirect +
│  maxProtocolVersion +
│  minProtocolVersion +
│  mode +
│  privateKey +
│  serverCertificate +
│  ▼ Subject Alt Names +
│  │  Value * +
│  ▼ Verify Certificate Hash +
│  │  Value * +
│  ▼ Verify Certificate Spki +
│  │  Value * +
****

[#SessionAffinityConfig]
=== Session Affinity Config
****
▼ Client IP +
│  timeoutSeconds
****

[#Sidecars]
=== Sidecars
****
▶ <<Env>> +
image * +
imagePullPolicy +
name * +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE
****

[#Spec]
=== Spec
****
▼ Access Modes +
│  Value * +
▼ Data Source +
│  apiGroup +
│  kind * +
│  name * +
▼ Resources +
│  ▼ Limits +
│  │  KEY +
│  │  VALUE +
│  ▼ Requests +
│  │  KEY +
│  │  VALUE +
▼ Selector +
│  ▼ Match Expressions +
│  │  key * +
│  │  operator * +
│  │  ▼ Values +
│  │  │  Value * +
│  matchLabels +
storageClassName +
volumeMode +
volumeName
****

[#StartupProbe]
=== Startup Probe
****
▼ Exec +
│  ▼ Command +
│  │  Value * +
failureThreshold +
▼ Http Get +
│  host +
│  ▼ Http Headers +
│  │  name * +
│  │  value * +
│  path +
│  port * +
│  scheme +
initialDelaySeconds +
periodSeconds +
successThreshold +
▼ Tcp Socket +
│  host +
│  port * +
timeoutSeconds
****

[#Storage]
=== Storage
****
▼ Volume Claim Template +
│  apiVersion +
│  kind +
│  ▼ Spec +
│  │  ▼ Access Modes +
│  │  │  Value * +
│  │  ▼ Data Source +
│  │  │  apiGroup +
│  │  │  kind * +
│  │  │  name * +
│  │  ▼ Data Source Ref +
│  │  │  apiGroup +
│  │  │  kind * +
│  │  │  name * +
│  │  ▼ Resources +
│  │  │  ▼ Limits +
│  │  │  │  KEY +
│  │  │  │  Value +
│  │  │  ▼ Requests +
│  │  │  │  KEY +
│  │  │  │  Value +
│  │  ▼ Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key * +
│  │  │  │  operator * +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  │  matchLabels +
│  │  storageClassName +
│  │  volumeMode +
│  │  volumeName +
│  ▼ Status +
│  │  ▼ Access Modes +
│  │  │  Value * +
│  │  ▼ Allocated Resources +
│  │  │  KEY +
│  │  │  VALUE +
│  │  ▼ Capacity +
│  │  │  KEY +
│  │  │  VALUE +
│  │  ▼ Conditions +
│  │  │  lastProbeTime +
│  │  │  lastTransitionTime +
│  │  │  message +
│  │  │  reason +
│  │  │  status * +
│  │  │  type * +
│  │  phase +
│  │  resizeStatus
****

[#Storageos]
=== Storageos
****
fsType +
readOnly +
▼ Secret Ref +
│  apiVersion +
│  fieldPath +
│  kind +
│  name +
│  namespace +
│  resourceVersion +
│  uid +
volumeName +
volumeNamespace
****

[#Strategy]
=== Strategy
****
▼ Rolling Update +
│  maxSurge +
│  maxUnavailable +
type
****

[#Subsets]
=== Subsets
****
labels +
name +
▶ <<Traffic Policy>>
****

== T

[#Tcp]
=== Tcp
****
▼ Match +
│  ▼ Destination Subnets +
│  │  Value * +
│  ▼ Gateways +
│  │  Value * +
│  port +
│  sourceLabels +
│  sourceSubnet +
▼ Route +
│  ▼ Destination +
│  │  host +
│  │  ▼ Port +
│  │  │  number +
│  │  subset +
│  weight
****

[#Template]
=== Template
****
▶ <<Metadata>> * +
▼ Spec * +
│  activeDeadlineSeconds +
│  ▶ <<Affinity>> +
│  automountServiceAccountToken +
│  ▶ <<Containers>> * +
│  ▶ <<Dns Config>> +
│  dnsPolicy +
│  enableServiceLinks +
│  ▶ <<Ephemeral Containers>> +
│  ▶ <<Host Aliases>> +
│  hostIPC +
│  hostNetwork +
│  hostPID +
│  hostname +
│  ▼ Image Pull Secrets +
│  │  name +
│  ▶ <<Containers,Init Containers>> +
│  nodeName +
│  nodeSelector +
│  ▼ Overhead +
│  │  KEY +
│  │  VALUE +
│  preemptionPolicy +
│  priority +
│  priorityClassName +
│  ▼ Readiness Gates +
│  │  conditionType * +
│  restartPolicy +
│  runtimeClassName +
│  schedulerName +
│  ▶ <<Security Context>> +
│  serviceAccountName +
│  setHostnameAsFQDN +
│  shareProcessNamespace +
│  subdomain +
│  terminationGracePeriodSeconds +
│  ▼ Tolerations +
│  │  effect +
│  │  key +
│  │  operator +
│  │  tolerationSeconds +
│  │  value +
│  ▶ <<Topology Spread Constraints>> +
│  ▶ <<Volumes>>
****

[#Templatekafka]
=== Template(Kafka)
****
▼ Api Service +
│  ▼ Ip Families +
│  │  Value * +
│  ipFamilyPolicy +
▼ Build Config +
│  pullSecret +
▼ Build Container +
│  ▼ Env +
│  │  name +
│  │  value +
│  ▼ Security Context +
│  │  allowPrivilegeEscalation +
│  │  ▼ Capabilities +
│  │  │  ▼ Add +
│  │  │  │  Value * +
│  │  │  ▼ Drop +
│  │  │  │  Value * +
│  │  privileged +
│  │  procMount +
│  │  readOnlyRootFilesystem +
│  │  runAsGroup +
│  │  runAsNonRoot +
│  │  runAsUser +
│  │  ▼ Se Linux Options +
│  │  │  level +
│  │  │  role +
│  │  │  type +
│  │  │  user +
│  │  ▼ Seccomp Profile +
│  │  │  localhostProfile +
│  │  │  type +
│  │  ▼ Windows Options +
│  │  │  gmsaCredentialSpec +
│  │  │  gmsaCredentialSpecName +
│  │  │  hostProcess +
│  │  │  runAsUserName +
▼ Build Pod +
│  ▶ <<Affinity>> +
│  enableServiceLinks +
│  ▶ <<Host Aliases>> +
│  ▼ Image Pull Secrets +
│  │  name +
│  priorityClassName +
│  schedulerName +
│  ▼ Security Context +
│  │  fsGroup +
│  │  fsGroupChangePolicy +
│  │  runAsGroup +
│  │  runAsNonRoot +
│  │  runAsUser +
│  │  ▼ Se Linux Options +
│  │  │  level +
│  │  │  role +
│  │  │  type +
│  │  │  user +
│  │  ▼ Seccomp Profile +
│  │  │  localhostProfile +
│  │  │  type +
│  │  ▼ Supplemental Groups +
│  │  │  Value * +
│  │  ▼ Sysctls +
│  │  │  name +
│  │  │  value +
│  │  ▼ Windows Options +
│  │  │  gmsaCredentialSpec +
│  │  │  gmsaCredentialSpecName +
│  │  │  hostProcess +
│  │  │  runAsUserName +
│  terminationGracePeriodSeconds +
│  tmpDirSizeLimit +
│  ▼ Tolerations +
│  │  effect +
│  │  key +
│  │  operator +
│  │  tolerationSeconds +
│  │  value +
│  ▼ Topology Spread Constraints +
│  │  ▼ Label Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key +
│  │  │  │  operator +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  maxSkew +
│  │  topologyKey +
│  │  whenUnsatisfiable +
▼ Connect Container +
│  ▼ Env +
│  │  name +
│  │  value +
│  ▼ Security Context +
│  │  allowPrivilegeEscalation +
│  │  ▼ Capabilities +
│  │  │  ▼ Add +
│  │  │  │  Value * +
│  │  │  ▼ Drop +
│  │  │  │  Value * +
│  │  privileged +
│  │  procMount +
│  │  readOnlyRootFilesystem +
│  │  runAsGroup +
│  │  runAsNonRoot +
│  │  runAsUser +
│  │  ▼ Se Linux Options +
│  │  │  level +
│  │  │  role +
│  │  │  type +
│  │  │  user +
│  │  ▼ Seccomp Profile +
│  │  │  localhostProfile +
│  │  │  type +
│  │  ▼ Windows Options +
│  │  │  gmsaCredentialSpec +
│  │  │  gmsaCredentialSpecName +
│  │  │  hostProcess +
│  │  │  runAsUserName +
▼ Deployment +
│  deploymentStrategy +
▼ Init Container +
│  ▼ Env +
│  │  name +
│  │  value +
│  ▼ Security Context +
│  │  allowPrivilegeEscalation +
│  │  ▼ Capabilities +
│  │  │  ▼ Add +
│  │  │  │  Value * +
│  │  │  ▼ Drop +
│  │  │  │  Value * +
│  │  privileged +
│  │  procMount +
│  │  readOnlyRootFilesystem +
│  │  runAsGroup +
│  │  runAsNonRoot +
│  │  runAsUser +
│  │  ▼ Se Linux Options +
│  │  │  level +
│  │  │  role +
│  │  │  type +
│  │  │  user +
│  │  ▼ Seccomp Profile +
│  │  │  localhostProfile +
│  │  │  type +
│  │  ▼ Windows Options +
│  │  │  gmsaCredentialSpec +
│  │  │  gmsaCredentialSpecName +
│  │  │  hostProcess +
│  │  │  runAsUserName +
▼ Pod +
│  ▶ <<Affinity>> +
│  enableServiceLinks +
│  ▶ <<Host Aliases>> +
│  ▼ Image Pull Secrets +
│  │  name +
│  priorityClassName +
│  schedulerName +
│  ▼ Security Context +
│  │  fsGroup +
│  │  fsGroupChangePolicy +
│  │  runAsGroup +
│  │  runAsNonRoot +
│  │  runAsUser +
│  │  ▼ Se Linux Options +
│  │  │  level +
│  │  │  role +
│  │  │  type +
│  │  │  user +
│  │  ▼ Seccomp Profile +
│  │  │  localhostProfile +
│  │  │  type +
│  │  ▼ Supplemental Groups +
│  │  │  Value * +
│  │  ▼ Sysctls +
│  │  │  name +
│  │  │  value +
│  │  ▼ Windows Options +
│  │  │  gmsaCredentialSpec +
│  │  │  gmsaCredentialSpecName +
│  │  │  hostProcess +
│  │  │  runAsUserName +
│  terminationGracePeriodSeconds +
│  tmpDirSizeLimit +
│  ▼ Tolerations +
│  │  effect +
│  │  key +
│  │  operator +
│  │  tolerationSeconds +
│  │  value +
│  ▼ Topology Spread Constraints +
│  │  ▼ Label Selector +
│  │  │  ▼ Match Expressions +
│  │  │  │  key +
│  │  │  │  operator +
│  │  │  │  ▼ Values +
│  │  │  │  │  Value * +
│  │  maxSkew +
│  │  topologyKey +
│  │  whenUnsatisfiable +
▼ Pod Disruption Budget +
│  maxUnavailable
****

[#Tls]
=== Tls
****
▼ Match +
│  ▼ Destination Subnets +
│  │  Value * +
│  ▼ Gateways +
│  │  Value * +
│  port +
│  ▼ Sni Hosts +
│  │  Value * +
│  sourceLabels +
▼ Route +
│  ▼ Destination +
│  │  host +
│  │  ▼ Port +
│  │  │  number +
│  │  subset +
│  weight
****

[#TlsRedis]
=== Tls(Redis)
****
ca +
cert +
key +
▼ Secret * +
│  defaultMode +
│  ▼ Items +
│  │  key * +
│  │  mode +
│  │  path * +
│  optional +
│  secretName
****



[#TlsSidecar]
=== Tls Sidecar
****
image +
▼ Liveness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
logLevel +
▼ Readiness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds
****


[#TopologySpreadConstraints]
=== Topology Spread Constraints
****
▼ Label Selector +
│  ▼ Match Expressions +
│  │  key * +
│  │  operator * +
│  │  ▼ Values +
│  │  │  Value * +
│  matchLabels +
maxSkew * +
topologyKey * +
whenUnsatisfiable *
****

[#TrafficPolicy]
=== Traffic Policy
****
▼ Connection Pool +
│  ▼ Http +
│  │  h2UpgradePolicy +
│  │  http1MaxPendingRequests +
│  │  http2MaxRequests +
│  │  idleTimeout +
│  │  maxRequestsPerConnection +
│  │  maxRetries +
│  ▼ Tcp +
│  │  connectTimeout +
│  │  maxConnections +
│  │  ▼ Tcp Keepalive +
│  │  │  interval +
│  │  │  probes +
│  │  │  time +
▼ Load Balancer +
│  ▼ Consistent Hash +
│  │  ▼ Http Cookie +
│  │  │  name +
│  │  │  path +
│  │  │  ttl +
│  │  httpHeaderName +
│  │  minimumRingSize +
│  │  useSourceIp +
│  ▼ Locality Lb Setting +
│  │  ▼ Distribute +
│  │  │  from +
│  │  │  ▼ To +
│  │  │  │  KEY +
│  │  │  │  VALUE +
│  │  enabled +
│  │  ▼ Failover +
│  │  │  from +
│  │  │  to +
│  simple +
▼ Outlier Detection +
│  baseEjectionTime +
│  consecutive5xxErrors +
│  consecutiveErrors +
│  consecutiveGatewayErrors +
│  interval +
│  maxEjectionPercent +
│  minHealthPercent +
▼ Port Level Settings +
│  ▼ Connection Pool +
│  │  ▼ Http +
│  │  │  h2UpgradePolicy +
│  │  │  http1MaxPendingRequests +
│  │  │  http2MaxRequests +
│  │  │  idleTimeout +
│  │  │  maxRequestsPerConnection +
│  │  │  maxRetries +
│  │  ▼ Tcp +
│  │  │  connectTimeout +
│  │  │  maxConnections +
│  │  │  ▼ Tcp Keepalive +
│  │  │  │  interval +
│  │  │  │  probes +
│  │  │  │  time +
│  ▼ Load Balancer +
│  │  ▼ Consistent Hash +
│  │  │  ▼ Http Cookie +
│  │  │  │  name +
│  │  │  │  path +
│  │  │  │  ttl +
│  │  │  httpHeaderName +
│  │  │  minimumRingSize +
│  │  │  useSourceIp +
│  │  ▼ Locality Lb Setting +
│  │  │  ▼ Distribute +
│  │  │  │  from +
│  │  │  │  ▼ To +
│  │  │  │  │  KEY +
│  │  │  │  │  VALUE +
│  │  │  enabled +
│  │  │  ▼ Failover +
│  │  │  │  from +
│  │  │  │  to +
│  │  simple +
│  ▼ Outlier Detection +
│  │  baseEjectionTime +
│  │  consecutive5xxErrors +
│  │  consecutiveErrors +
│  │  consecutiveGatewayErrors +
│  │  interval +
│  │  maxEjectionPercent +
│  │  minHealthPercent +
│  ▼ Port +
│  │  number +
│  ▼ Tls +
│  │  caCertificates +
│  │  clientCertificate +
│  │  mode +
│  │  privateKey +
│  │  sni +
│  │  ▼ Subject Alt Names +
│  │  │  Value * +
▼ Tls +
│  caCertificates +
│  clientCertificate +
│  mode +
│  privateKey +
│  sni +
│  ▼ Subject Alt Names +
│  │  Value * +
****

== U

[#UpdateStrategy(DaemonSet)]
=== Update Strategy(DaemonSet)
****
▼ Rolling Update +
│  maxUnavailable +
type
****

[#UpdateStrategy(StatefulSet)]
=== Update Strategy(StatefulSet)
****
▼ Rolling Update +
│  partition +
type
****

== V

[#Volumes]
=== Volumes
****
▼ Aws Elastic Block Store +
│  fsType +
│  partition +
│  readOnly +
│  volumeID * +
▼ Azure Disk +
│  cachingMode +
│  diskName * +
│  diskURI * +
│  fsType +
│  kind +
│  readOnly +
▼ Azure File +
│  readOnly +
│  secretName * +
│  shareName * +
▼ Cephfs +
│  ▼ Monitors * +
│  │  Value * +
│  path +
│  readOnly +
│  secretFile +
│  ▼ Secret Ref +
│  │  name +
│  user +
▼ Cinder +
│  fsType +
│  readOnly +
│  ▼ Secret Ref +
│  │  name +
│  volumeID * +
▼ Config Map +
│  defaultMode +
│  ▼ Items +
│  │  key * +
│  │  mode +
│  │  path * +
│  name +
│  optional +
▼ Csi +
│  driver * +
│  fsType +
│  ▼ Node Publish Secret Ref +
│  │  name +
│  readOnly +
│  ▼ Volume Attributes +
│  │  KEY +
│  │  VALUE +
▼ Downward API +
│  defaultMode +
│  ▼ Items +
│  │  ▼ Field Ref +
│  │  │  apiVersion +
│  │  │  fieldPath * +
│  │  mode +
│  │  path * +
│  │  ▼ Resource Field Ref +
│  │  │  containerName +
│  │  │  divisor +
│  │  │  resource * +
▼ Empty Dir +
│  medium +
│  sizeLimit +
▼ Ephemeral +
│  readOnly +
│  ▼ Volume Claim Template +
│  │  ▶ <<Metadata>> +
│  │  ▶ <<Spec>> * +
▼ Fc +
│  fsType +
│  lun +
│  readOnly +
│  ▼ Target WW Ns +
│  │  Value * +
│  ▼ Wwids +
│  │  Value * +
▼ Flex Volume +
│  driver * +
│  fsType +
│  ▼ Options +
│  │  KEY +
│  │  VALUE +
│  readOnly +
│  ▼ Secret Ref +
│  │  name +
▼ Flocker +
│  datasetName +
│  datasetUUID +
▼ Gce Persistent Disk +
│  fsType +
│  partition +
│  pdName * +
│  readOnly +
▼ Git Repo +
│  directory +
│  repository * +
│  revision +
▼ Glusterfs +
│  endpoints * +
│  path * +
│  readOnly +
▼ Host Path +
│  path * +
│  type +
▼ Iscsi +
│  chapAuthDiscovery +
│  chapAuthSession +
│  fsType +
│  initiatorName +
│  iqn * +
│  iscsiInterface +
│  lun * +
│  ▼ Portals +
│  │  Value * +
│  readOnly +
│  ▼ Secret Ref +
│  │  name +
│  targetPortal * +
name * +
▼ Nfs +
│  path * +
│  readOnly +
│  server * +
▼ Persistent Volume Claim +
│  claimName * +
│  readOnly +
▼ Photon Persistent Disk +
│  fsType +
│  pdID * +
▼ Portworx Volume +
│  fsType +
│  readOnly +
│  volumeID * +
▼ Projected +
│  defaultMode +
│  ▼ Sources * +
│  │  ▼ Config Map +
│  │  │  ▼ Items +
│  │  │  │  key * +
│  │  │  │  mode +
│  │  │  │  path * +
│  │  │  name +
│  │  │  optional +
│  │  ▼ Downward API +
│  │  │  ▼ Items +
│  │  │  │  ▼ Field Ref +
│  │  │  │  │  apiVersion +
│  │  │  │  │  fieldPath * +
│  │  │  │  mode +
│  │  │  │  path * +
│  │  │  │  ▼ Resource Field Ref +
│  │  │  │  │  containerName +
│  │  │  │  │  divisor +
│  │  │  │  │  resource * +
│  │  ▼ Secret +
│  │  │  ▼ Items +
│  │  │  │  key * +
│  │  │  │  mode +
│  │  │  │  path * +
│  │  │  name +
│  │  │  optional +
│  │  ▼ Service Account Token +
│  │  │  audience +
│  │  │  expirationSeconds +
│  │  │  path * +
▼ Quobyte +
│  group +
│  readOnly +
│  registry * +
│  tenant +
│  user +
│  volume * +
▼ Rbd +
│  fsType +
│  image * +
│  keyring +
│  ▼ Monitors * +
│  │  Value * +
│  pool +
│  readOnly +
│  ▼ Secret Ref +
│  │  name +
│  user +
▼ Scale IO +
│  fsType +
│  gateway * +
│  protectionDomain +
│  readOnly +
│  ▼ Secret Ref * +
│  │  name +
│  sslEnabled +
│  storageMode +
│  storagePool +
│  system * +
│  volumeName +
▼ Secret +
│  defaultMode +
│  ▼ Items +
│  │  key * +
│  │  mode +
│  │  path * +
│  optional +
│  secretName +
▼ Storageos +
│  fsType +
│  readOnly +
│  ▼ Secret Ref +
│  │  name +
│  volumeName +
│  volumeNamespace +
▼ Vsphere Volume +
│  fsType +
│  storagePolicyID +
│  storagePolicyName +
│  volumePath *
****

[#VolumeClaimTemplates]
=== Volume Claim Templates
****
apiVersion +
kind +
▶ <<Metadata>> +
▶ <<Spec>>
****

== W

[#Workspaces]
=== Workspaces
****
▼ Config Map +
│  defaultMode +
│  ▼ Items +
│  │  key * +
│  │  mode +
│  │  path * +
│  name +
│  optional +
▼ Empty Dir +
│  medium +
│  sizeLimit +
name * +
▼ Persistent Volume Claim +
│  claimName * +
│  readOnly +
▼ Secret +
│  defaultMode +
│  ▼ Items +
│  │  key * +
│  │  mode +
│  │  path * +
│  optional +
│  secretName +
subPath +
▼ Volume Claim Template +
│  apiVersion +
│  kind +
│  ▶ <<Spec>> +
│  ▼ Status +
│  │  ▼ Access Modes +
│  │  │  Value * +
│  │  ▼ Capacity +
│  │  │  KEY +
│  │  │  VALUE +
│  │  ▼ Conditions +
│  │  │  lastProbeTime +
│  │  │  lastTransitionTime +
│  │  │  message +
│  │  │  reason +
│  │  │  status * +
│  │  │  type * +
│  │  phase
****

== Z

[#Zookeepers]
=== Zookeeper
****
image +
▶ <<Jmx Options>> +
▶ <<Jvm Options>> +
▼ Liveness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
▶ <<Logging>> +
▶ <<Metrics Config>> +
▼ Readiness Probe +
│  failureThreshold +
│  initialDelaySeconds +
│  periodSeconds +
│  successThreshold +
│  timeoutSeconds +
replicas * +
▼ Storage * +
│  class +
│  deleteClaim +
│  id +
│  ▼ Overrides +
│  │  broker +
│  │  class +
│  size +
│  sizeLimit +
│  type * +
▼ Template +
│  ▼ Client Service +
│  │  ▼ Ip Families +
│  │  │  Value * +
│  │  ipFamilyPolicy +
│  ▼ Nodes Service +
│  │  ▼ Ip Families +
│  │  │  Value * +
│  │  ipFamilyPolicy +
│  ▼ Pod +
│  │  ▶ <<Affinity>> +
│  │  enableServiceLinks +
│  │  ▶ <<Host Aliases>> +
│  │  ▼ Image Pull Secrets +
│  │  │  name +
│  │  priorityClassName +
│  │  schedulerName +
│  │  ▶ <<Security Context>> +
│  │  terminationGracePeriodSeconds +
│  │  tmpDirSizeLimit +
│  │  ▼ Tolerations +
│  │  │  effect +
│  │  │  key +
│  │  │  operator +
│  │  │  tolerationSeconds +
│  │  │  value +
│  │  ▼ Topology Spread Constraints +
│  │  │  ▼ Label Selector +
│  │  │  │  ▼ Match Expressions +
│  │  │  │  │  key +
│  │  │  │  │  operator +
│  │  │  │  │  ▼ Values +
│  │  │  │  │  │  Value * +
│  │  │  maxSkew +
│  │  │  topologyKey +
│  │  │  whenUnsatisfiable +
│  ▼ Pod Disruption Budget +
│  │  maxUnavailable +
│  ▼ Statefulset +
│  │  podManagementPolicy +
│  ▼ Zookeeper Container +
│  │  ▼ Env +
│  │  │  name +
│  │  │  value +
│  │  ▼ Security Context +
│  │  │  allowPrivilegeEscalation +
│  │  │  ▼ Capabilities +
│  │  │  │  ▼ Add +
│  │  │  │  │  Value * +
│  │  │  │  ▼ Drop +
│  │  │  │  │  Value * +
│  │  │  privileged +
│  │  │  procMount +
│  │  │  readOnlyRootFilesystem +
│  │  │  runAsGroup +
│  │  │  runAsNonRoot +
│  │  │  runAsUser +
│  │  │  ▼ Se Linux Options +
│  │  │  │  level +
│  │  │  │  role +
│  │  │  │  type +
│  │  │  │  user +
│  │  │  ▼ Seccomp Profile +
│  │  │  │  localhostProfile +
│  │  │  │  type +
│  │  │  ▼ Windows Options +
│  │  │  │  gmsaCredentialSpec +
│  │  │  │  gmsaCredentialSpecName +
│  │  │  │  hostProcess +
│  │  │  │  runAsUserName +
****
