= Easy and economical way to build open source-based cloud

With the shift from infrastructure cloud to next-generation platform cloud environment, container-based cloud architecture is becoming an essential element, and Kubernetes as its core engine is emerging as a standard. Enterprises want to incorporate multiple clouds into their IT strategies to take advantage of the cloud's full computing power. 

Tmax has joined the Cloud Native Computing Foundation (CNCF) to secure its own technology for this core engine, and is contributing to open source and reinforcing products with its abundant R&D power. Tmax has also obtained CK certification, which is the official CNCF certification for {product-title} {product-version} based on Kubernetes. It provides easy access to various open sources that run on {product-title} and {product-version}. This OSS enables a system that Tmax directly verifies and provides technical support. +

{product-title} {product-version} built on Tmax's open source technology facilitates quick and easy cloud construction and open source-based software configuration. You can experience stable operation of infrastructure through Tmax's quick technical support. 
