= CI/CD 설치

다음은 Tekton 파이프라인을 이용하여 CI/CD를 사용할 수 있도록 관련된 Task와 
이미지 취약점 분석 툴인 Clair 설치 과정에 대한 설명이다.

. *Clair 이미지 생성*
+
clair_latest.tar, postgres.tar, clair-git.tar 파일을 `docker load` 명령을 사용해 도커 이미지로 생성한다.
+
----
[root@master1 17.cicd]# docker load -i clair_latest.tar
[root@master1 17.cicd]# docker load -i postgres.tar
[root@master1 17.cicd]# docker load -i clair-git.tar

[root@master1 17.cicd]# docker images|grep clair
quay.io/coreos/clair    latest     79f851f41934   15 months ago        355MB
[root@master1 17.cicd]# docker images|grep postgres
postgres        latest       0f10374e5170        8 weeks ago        314MB
[root@master1 17.cicd]# docker images|grep clair
quay.io/coreos/clair-git  latest   e7b02af47e06      2 weeks ago       60.1MB
----

. *Clair 이미지 업로드*
+
생성된 도커 이미지를 프라이빗 이미지 레지스트리에 업로드한다.
+
우선 `docker tag` 명령을 사용해 각 이미지에 레지스트리의 주소를 추가한다.
+
----
[root@master1 17.cicd]# docker tag \
quay.io/coreos/clair:latest {IMAGE_REGISTRY}/quay.io/coreos/clair:latest
[root@master1 17.cicd]# docker tag \
postgres:latest {IMAGE_ REGISTRY}/postgres:latest
[root@master1 17.cicd]# docker tag \
quay.io/coreos/clair-git:latest {IMAGE_ REGISTRY}/quay.io/coreos/clair-git:latest
----
+
이후 `docker push` 명령을 사용해 각 이미지를 레지스트리에 업로드한다.
+
----
[root@master1 17.cicd]# docker push {IMAGE_REGISTRY}/quay.io/coreos/clair:latest
[root@master1 17.cicd]# docker push {IMAGE_REGISTRY}/postgres:latest
[root@master1 17.cicd]# docker push {IMAGE_REGISTRY}/quay.io/coreos/clair-git:latest
----

. *Clair 이미지 업로드 확인*
+
이미지가 정상적으로 업로드되었는지 확인한다.
+
----
curl -X GET http://{IMAGE_REGISTRY}/v2/{이미지 이름}/tags/list
----

. *Clair 리소스 생성*
+
clair.tar 파일을 이용하여 clair에 필요한 리소스를 생성한다. +
먼저 clair/docker-compose.yml, clair/contrib/k8s/clair-kubernetes.yaml 내부의 {IMAGE_REPOSITORY} 부분에 구성한 docker registry IP를 넣어준 후 secret을 생성하고 yaml을 apply하여 리소스를 생성한다.
+
----
[root@master1 17.cicd]# pwd
/root/hc-install/17.cicd 

[root@master1 17.cicd]# tar -xvf clair.tar
cd clair/contrib/k8s
[root@master1 k8s]# cd clair/contrib/k8s

[root@master1 17.cicd]# kubectl create secret generic clairsecret \
--from-file=./config.yaml
secret/clairsecret2 created
[root@master1 17.cicd]# kubectl create -f clair-kubernetes.yaml
service/clairsvc created
...
----
+
default Namespace에 clair 관련 파드가 생성됐는지 확인한다.
+
----
[root@master1 k8s]# k get pod|grep clair
clair-postgres-48nf6               1/1     Running   0          15h
clair-skg58                        1/1     Running   1          15h
----

. *Task 이미지 생성*
+
cicd-util_1.0.0.tar, klar_v2.4.0.tar, s2i.tar, buildah.tar 파일을 `docker load` 명령을 사용해 도커 이미지로 생성한다. +
+
----
root@master1 17.cicd]# pwd
/root/hc-install/17.cicd

[root@master1 17.cicd]# docker load -i cicd-util_1.0.0.tar
[root@master1 17.cicd]# docker load -i klar_v2.4.0.tar
[root@master1 17.cicd]# docker load -i s2i.tar
[root@master1 17.cicd]# docker load -i buildah.tar

[root@master1 17.cicd]# docker images|grep cicd
cicd-util        1.0.0           9147293f3cbf        2 weeks ago         136MB
[root@master1 17.cicd]# docker images|grep klar
klar         v2.4.0       6257c751054e        3 months ago        692MB
[root@master1 17.cicd]# docker images|grep s2i
quay.io/openshift-pipeline/s2i  nightly  c0020e5b0b40   2 weeks ago      416MB
[root@master1 17.cicd]# docker images|grep build
quay.io/buildah/stable     latest    e03a232aae6c     4 weeks ago     257MB
----

. *Task 이미지 업로드*
+
생성된 도커 이미지를 프라이빗 이미지 레지스트리에 업로드한다. 
+
우선 `docker tag` 명령을 사용해 각 이미지에 레지스트리의 주소를 추가한다.
+
----
[root@master1 17.cicd]# docker tag \
cicd-util:1.0.0 {IMAGE_REGISTRY}/cicd-util:1.0.0
[root@master1 17.cicd]# docker tag klar:v2.4.0 {IMAGE_REGISTRY}/klar:v2.4.0
[root@master1 17.cicd]# docker tag \
quay.io/openshift-pipeline/s2i:nightly {IMAGE_REGISTRY}/quay.io/openshift-pipeline/s2i:nightly
[root@master1 17.cicd]# docker tag \
quay.io/buildah/stable:latest {IMAGE_REGISTRY}/quay.io/buildah/stable:latest

----
+
이후 `docker push` 명령을 사용해 각 이미지를 레지스트리에 업로드한다.
+
----
[root@master1 17.cicd]# docker push {IMAGE_REGISTRY}/cicd-util:1.0.0
[root@master1 17.cicd]# docker push {IMAGE_REGISTRY}/klar:v2.4.0
[root@master1 17.cicd]# docker push \
{IMAGE_REGISTRY}/quay.io/openshift-pipeline/s2i:nightly
[root@master1 17.cicd]# docker push {IMAGE_REGISTRY}/quay.io/buildah/stable:latest
----

. *Task 이미지 업로드 확인*
+
이미지가 정상적으로 업로드되었는지 확인한다.
+
----
curl -X GET http://{IMAGE_REGISTRY}/v2/{이미지 이름}/tags/list
----

. *task-s2i 생성*
+
task-s2i.yaml 파일을 이용하여 source를 image화 하기 위한 s2i task를 생성한다. +
task-s2i.yaml 파일 내부에 s2i task 실행시 필요한 cicd-util:1.0.0 이미지 경로의 위치를 {IMAGE_REPOSITORY}에서 docker registry IP로 변경한 후 apply한다.
+
----
[root@master1 17.cicd]# kubectl apply -f task-s2i.yaml
----

. *task-scan 생성*
+
task-scan.yaml 파일을 이용하여 이미지 취약점 분석을 위한 scan task를 생성한다. 
task-scan.yaml 파일 내부에 scan task 실행시 필요한 klar:v2.4.0 이미지 경로의 
위치를 {IMAGE_REPOSITORY}에서 docker registry IP로 변경한다. 또한 CLAIR_ADDR의 http://{NODE_IP}:30060로 명시된 {NODE_IP} 부분을 Clair가 설치된 노드의 IP로 변경한다.
+
----
[root@master1 17.cicd]# kubectl apply -f task-scan.yaml
----

. *task-deploy 생성*
+
task-deploy.yaml 파일을 이용하여 deployment.yaml을 생성하고 deploy 하기 위한
deploy task를 생성한다. +
task-deploy.yaml 파일 내부에 deploy task 실행시 필요한 cicd-util:1.0.0 이미지 경로의 위치를 {IMAGE_REPOSITORY}에서 docker registry IP로 변경한 후 apply 한다.
+
----
[root@master1 17.cicd]# kubectl apply -f task-deploy.yaml
----