[id="contributing-to-docs-contributing"]
= Contribute to OpenShift documentation
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:description: Basic information about the OpenShift GitHub repository

toc::[]


== _distro_map.yml 작성 방법

link:/_distro_map.yml[_distro_map.yml]
[source, yaml]
----
hypercloud:                               # 빌드 시 _preview에 떨어지는 디렉토리명. 영문, 숫자, 하이픈, 언더바 사용 가능. (erb: distro_key)
  name: HyperCloud Console                # 제품명. (adoc: product-title / erb: distro)
  author: HyperCloud Documentation Project <hypercloud-docs@tmax.com>
  site: HyperCloud-Docs                   # 영문 대소문자, 숫자, 하이픈, 언더바 가능. 화면에 표시되지 않지만 입력 필수
  site_name: Documentation                # 브래드크럼 최상위 항목 (erb: site_name)
  site_url: https://www.tmaxcloud.com/    # gnb 로고 또는 브래드크럼 최상위 항목 클릭 시 이동 링크 (erb: site_url)
  branches:
    master:                               # 브랜치명
      name: '4'                           # 버전명 (adoc: product-version / erb: version)
      dir: '4'                            # 해당 버전의 디렉토리 명. 버전명과 동일하게 작성
    test-branch:
      name: '3'
      dir: '3'
hypercloud-en:
  name: HyperCloud Console
  author: HyperCloud Documentation Project <hypercloud-docs@tmax.com>
  site: HyperCloud-Docs
  site_name: Documentation
  site_url: https://www.tmaxcloud.com/
  branches:
    master:
      name: '4'
      dir: '4'
    test-branch:
      name: '3'
      dir: '3'

----

* 빌드 결과물 파일 구조 예시
+
---- 
_preview
├── hypercloud
|   ├── 4
|   |   └── 빌드 결과물 
|   └── 3
|       └── 빌드 결과물 
└── hypercloud-01
    ├── 4
    |   └── 빌드 결과물 
    └── 3
        └── 빌드 결과물 
----


== _topic_map.yml 작성 방법

Docs 화면의 목차(좌측 Navigation Bar)를 구성하는 부분

* 최대 3 depth 까지 작성 가능, 최상단 항목은 Group 만 가능 (하위 Topic을 포함해야함)
* Name : 제목 (목차, 브래드크럼, adoc 파일 상단에 노출되는 타이틀)
* Id : 대문자로 시작, 카멜 형식으로 작성
** 2depth 이상일 경우 : 상위항목의 Id와 자기 자신의 id를  ::으로 연결 ( `상위 항목의 id::현재 항목 id`)
** ex) Component (1depth),  Component::Operator (2depth) , Component::Compute::Docker (3depth)
* Dir : adoc파일의 경로. 소문자로만 구성, 두 단어 이상일 경우 언더바(_)로 연결.
* Topics : 하위 항목이 있는 경우 작성.
* File : adoc 파일명. 소문자로만 구성, 두 단어 이상일 경우 하이픈(-)으로 연결.


* link:/_topic_map.yml[_topic_map.yml]
+
[source, yaml]
----
# This configuration file dictates the organization of the topic groups and
# topics on the main page of the doc site for this branch. Each record
# consists of the following:
#
# ---                                  <= Record delimiter
# Name: Origin of the Species          <= Display name of topic group
# Id: OriginOfTheSpecies               <= Id of topic group
# Dir:  origin_of_the_species          <= Directory name of topic group
# Topics:
#   - Name: The Majestic Marmoset                       <= Topic name
#     Id: OriginOfTheSpecies::TheMajesticMarmoset       <= Topic id
#     File: the_majestic_marmoset                       <= Topic file under group dir +/- .adoc
#   - Name: The Curious Crocodile                       <= Topic 2 name
#     Id: OriginOfTheSpecies::TheCuriousCrocodile       <= Topic 2 id
#     File: the_curious_crocodile                       <= Topic 2 file
#   - Name: The Numerous Nematodes                      <= Sub-topic group name
#     Id: OriginOfTheSpecies::TheNumerousNematodes      <= Sub-topic group id
#     Dir: the_numerous_nematodes                       <= Sub-topic group dir
#     Topics:
#       - Name: The Wily Worm                                                <= Sub-topic name
#         Id: OriginOfTheSpecies::TheNumerousNematodes::TheWilyWorm          <= Sub-topic id
#         File: the_wily_worm                                                <= Sub-topic file under <group dir>/<subtopic dir>
#       - Name: The Acrobatic Ascarid                                        <= Sub-topic 2 name
#         Id: OriginOfTheSpecies::TheNumerousNematodes::TheAcrobaticAscarid  <= Sub-topic 2 id
#         File: the_acrobatic_ascarid                                        <= Sub-topic 2 file under <group dir>/<subtopic dir>
#
# The ordering of the records in this document determines the ordering of the
# topic groups and topics on the main page.
---
Name: Welcome
Id: Welcome
Dir: welcome
Topics:
  - Name: 제품소개
    Id: Welcome::Overview
    File: index
  - Name: 장/단점
    Id: Welcome::ProsCons
    File: pros-cons
  - Name: 법적공지
    Id: Welcome::LegalNotice
    File: legal-notice
  - Name: 릴리즈노트
    Id: Welcome::ReleaseNote
    File: release-note
---
Name: 구성 요소
Id: Component
Dir: component
Topics:
  - Name: HyperCloud 오퍼레이터
    Id: Component::Operator
    File: hypercloud-operator
  - Name: HyperCloud 콘솔
    Id: Component::Console
    File: hypercloud-console
  - Name: 쿠버네티스
    Id: Component::Kubernetes
    File: kubernetes
  - Name: 컴퓨트
    Id: Component::Compute
    Dir: compute
    Topics:
      - Name: 도커
        Id: Component::Compute::Docker
        File: docker
      - Name: CRI-O
        Id: Component::Compute::CRI-O
        File: cri-o
  - Name: 스토리지
    Id: Component::Storage
    Dir: storage
    Topics:
      - Name: Rook Ceph
        Id: Component::Storage::RookCeph
        File: rook-ceph
      - Name: NFS
        Id: Component::Storage::NFS
        File: nfs
  - Name: 네트워크
    Id: Component::Network
    Dir: network
    Topics:
      - Name: Calico
        Id: Component::Network::Calico
        File: calico
  - Name: 플러그인
    Id: Component::Plugin
    Dir: plugin
    Topics:
      - Name: Prometheus
        Id: Component::Plugin::Prometheus
        File: prometheus
      - Name: Grafana
        Id: Component::Plugin::Grafana
        File: grafana
      - Name: Tekton
        Id: Component::Plugin::Tekton
        File: tekton
      - Name: Kubevirt
        Id: Component::Plugin::Kubevirt
        File: kubevirt
---
Name: 인스톨 가이드
Id: InstallationGuide
Dir: installation_guide
Topics:
  - Name: 개요
    Id: InstallationGuide::Overview
    File: index
---
Name: 튜닝 가이드
Id: TuningGuide
Dir: tuning_guide
Topics:
  - Name: 개요
    Id: TuningGuide::Overview
    File: index
---
Name: 백업 및 복구
Id: BackupAndRestore
Dir: backup_and_restore
Topics:
  - Name: 개요
    Id: BackupAndRestore::Overview
    File: index
---
Name: 사용자가이드
Id: UserGuide
Dir: user_guide
Topics:
  - Name: 개요
    Id: UserGuide::Overview
    File: index
  - Name: 로그인
    Id: UserGuide::Welcome
    File: login
---
Name: API Reference
Id: APIReference
Dir: api_reference
Topics:
  - Name: Master API
    Id: APIReference::MasterAPI
    File: master-api
  - Name: Kubernetes API
    Id: APIReference::KubernetesAPI
    File: kubernetes-api
  - Name: Prometheus API
    Id: APIReference::PrometheusAPI
    File: prometheus-api

----


== 버전 추가 방법
* 브랜치 생성 및 _distro_map.yml에 정보 추가
** 버전 추가 시 새 브랜치 생성 (ex `new-branch`)
** _distro_map.yml에 새 버전의 브랜치 정보 추가

* link:/_distro_map.yml[_distro_map.yml]
+
[source, yml]
----
---
hypercloud: # 빌드 시 _preview에 떨어지는 디렉토리명. 영문, 숫자, 하이픈, 언더바 사용 가능. (distro_key)
  name: HyperCloud Console # 제품명. (distro)
  author: HyperCloud Documentation Project <hypercloud-docs@tmax.com>
  site: HyperCloud-Docs # 영문 대소문자, 숫자, 하이픈, 언더바 가능. 화면에 표시되지 않지만 입력 필수
  site_name: Documentation # 브래드크럼 최상위 항목 (site_name)
  site_url: https://www.tmaxcloud.com/ # gnb 로고 또는 브래드크럼 최상위 항목 클릭 시 이동 링크 (site_url)
  branches:
    master: # 브랜치명
      name: '4' # 버전명 (version)
      dir: '4' # 해당 버전의 디렉토리 명. 버전명과 동일하게 작성
    test-branch:
      name: '3'
      dir: '3'
    ####### 버전 추가 예시 #######
    new-branch:
      name: '5'
      dir: '5'
    ####### 버전 추가 예시 #######
----

* _templates/_topnav_other.html.erb 파일 수정
** id가 "**version-selector**"인 select태그 하위에 옵션 태그 한 줄 추가
** <option value=" `버전명` "> `화면에 보여질 버전명` </option>

** link:/_templates/_topnav_other.html.erb[_topnav_other.html.erb]
+
[source, html]
----
<select id="version-selector" onchange="versionSelector(this, '<%= distro_key %>', '<%= version %>');">
  <option value="5">HyperCloud 5</option> // 5 버전 추가 예시
  <option value="4">HyperCloud 4</option>
  <option value="3">HyperCloud 3</option>
</select>
----

** 새로운 버전의 브랜치로 이동한 상태에서 위의 코드 수정 후 새로 빌드해주어야함.

== 언어 추가 (i18n)
* 지원할 언어의 개수만큼 xref:../_distro_map.yml[_distro_map.yml] 파일에 distro를 생성합니다.
+
[source, yaml]
----
hypercloud:
  (...)
hypercloud-en:
  (...)
----

* 사용자가 gnb에서 추가한 언어를 선택 할 수 있도록 html 파일 내 언어 option을 추가합니다. 
** id가 "**language-selector**"인 select태그 하위에 옵션 태그 한 줄 추가
** <option value=" `distro` "> `화면에 표시할 언어명` </option>
** link:/_templates/_topnav_other.html.erb[_topnav_other.html.erb]
+
[source, html]
----
<select id="language-selector" onchange="languageSelector(this, '<%= distro_key %>');" >
  <option value="hypercloud">한국어</option>
  <option value="hypercloud-en">EN-US</option>
  <option value="hypercloud-fr">Français</option> // 언어 추가 예시
</select>
----

* 다국어를 지원할 문서(`.adoc`)에서 xref:conditional-text-between-products[ifdef, endif] 문법을 사용하여, 각 부분이 어떤 distro에서 보여질지 지정합니다.

** sample.adoc
+
----
\ifdef::hypercloud[]
i18n 샘플 입니다. 
\endif::[]

\ifdef::hypercloud-en[] 
This is i18n sample.
\endif::[]
----


* 전체 목차를 다국어로 지원하려면, xref:../_topic_map.yml[_topic_map.yml] 파일에서 topic title마다 Distros: 줄을 추가하여, 특정 topic이 어떤 distro에서 어떤 title로 보여질지 지정합니다. +
이때 Distros에 여러 개를 쉼표로 (공백없이) 이어붙여 입력할 수도 있고, all을 입력할 수도 있습니다.
+
[source, yaml]
----
---
Name: 환영합니다.
Id: Welcome
Distros: hypercloud
(...)
---
Name: Welcome
Id: Welcome
Distros: hypercloud-en
(...)

# Distros: all 입력가능
# Distros: hypercloud,hypercloud-en 입력가능
----

=== Conditional text between products
OpenShift documentation uses AsciiDoc's `ifdef/endif` macro to conditionalize
and reuse content across the different OpenShift products, down to the
single-line level.

The supported distribution attributes used with the OpenShift build mechanism
are:

* _openshift-origin_
* _openshift-online_
* _openshift-enterprise_
* _openshift-dedicated_
* _openshift-aro_
* _openshift-webscale_

These attributes can be used by themselves or in conjunction to conditionalize
text within a topic document.

Here is an example of this concept in use:

----
This first line is unconditionalized, and will appear for all versions.

\ifdef::openshift-enterprise,openshift-webscale,openshift-origin,openshift-dedicated[]
`Docker` and
\endif::[]
`Source-to-Image (S2I)` strategy builds set the following environment variables.
----

Note that the following limitations exist when conditionalizing text:

1. While the `ifdef/endif` blocks have no size limit, do not use them to
to conditionalize an entire file. If an entire file is specific to a
only some OpenShift distributions, specify them in the `&#95;topic&#95;map.yml`
file.

2. Avoid using `ifndef/endif`. As of writing, it's use is broken and buggy.

== Release branches
With the combination of conditionalizing content within files with
`ifdef/endif` and conditionalizing whole files in the `&#95;topic&#95;map.yml`
file, the `master` branch of
this repository always contains a complete set of documentation for all
OpenShift products. However, when and as new versions of an OpenShift product
are released, the `master` branch is merged down to new or existing release
branches. Here is the general naming scheme used in the branches:

* `master` - This is our *working* branch.
* `enterprise-N.N` - OpenShift Container Platform support releases. The docs
for OpenShift Online and OpenShift Dedicated are based on the appropriate
`enterprise-N.N` branch.

[NOTE]
====
All OpenShift content development for the 4.x stream occurs on the `master`, or
 *working* branch.
Therefore, when submitting your work the PR must be created against the `master`
branch. After it is reviewed, a writer will apply the content to the relevant
release branches. If you know which branches a change applies to, be sure to
specify it in your PR.

When adding or updating content for version 3.11, you should create a feature
branch against enterprise-3.11 to submit your changes.
====

== Adding files to the collection
After you create files, you must add them to the `&#95;topic&#95;map.yml` so
that the build system can render them. The documentation build system reads
the `&#95;distro&#95;map.yml` from the master branch to determine
which branches to build and then the `&#95;topic&#95;map.yml` file
for each of the branches
to construct the content from the source files and publish to the relevant
product site at https://docs.openshift.com. The build system _only_ reads this
file to determine which topic files to include. Therefore, all new topics that
are created must be included in the `&#95;topic&#95;map.yml` file in
order to be processed by the build system.

=== Topic map file format
The `&#95;topic&#95;map.yml` file uses the following format:

----
--- //<1>
Name: Origin of the Species <2>
Dir:  origin_of_the_species <3>
Distros: all <4>
Topics:
  - Name: The Majestic Marmoset <5>
    File: the_majestic_marmoset <6>
    Distros: all
  - Name: The Curious Crocodile
    File: the_curious_crocodile
    Distros: openshift-online,openshift-enterprise <4>
  - Name: The Numerous Nematodes
    Dir: the_numerous_nematodes <7>
    Topics:
      - Name: The Wily Worm <8>
        File: the_wily_worm
      - Name: The Acrobatic Ascarid  <= Sub-topic 2 name
        File: the_acrobatic_ascarid  <= Sub-topic 2 file under <group dir>/<subtopic dir>
----
<1> Record separator at the top of each topic group.
<2> Display name of topic group.
<3> Directory name of topic group.
<4> Which OpenShift versions this topic group is part of.
* The *Distros* setting is optional for topic groups and topic items. By
default, if the *Distros* setting is not used, it is processed as if it was set
to *Distros: all* for that particular topic or topic group. This means that
topic or topic group will appear in all product documentation versions.
* The *all* value for *Distros* is a synonym for
_openshift-origin,openshift-enterprise,openshift-online,openshift-dedicated,openshift-aro,openshift-webscale_.
* The *all* value overrides other values, so _openshift-online,all_ is processed
as *all*.
<5> Topic name.
<6> Topic file under the topic group dir without `.adoc`.
<7> This topic is actually a subtopic group. Instead of a `File` path it has a
`Dir` path and `Topics`, just like a top-level topic group.
<8> Topics belonging to a subtopic group are listed just like regular topics
with a `Name` and `File`.

== Next steps
* First, you should link:tools_and_setup.adoc[Install and set up the tools and software]
on your workstation so that you can contribute.
* Next, link:doc_guidelines.adoc[review the documentation guidelines] to
understand some basic guidelines to keep things consistent
across our content.
* If you are ready to create content, or want to edit existing content, the
link:create_or_edit_content.adoc[create or edit content] topic describes how
you can do this by creating a working branch.
