[id="contributing-to-docs-tools-and-setup"]
= 빌드 환경 세팅하기, 빌드하기
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:linkattrs:
:description: How to set up and install the tools to contribute

toc::[]

== AsciiBinder 설치하기
HyperCloud documentation은 AsciiDoc으로 이루어져 있고, http://asciidoctor.org/[AsciiDoctor] 기반의 문서 관리 시스템인 https://github.com/redhataccess/ascii_binder[AsciiBinder]으로 빌드한다.

CentOS 7.7.1908에서 아래와 같이 ascii_binder와 그 dependencies를 차례로 설치한다.
(다른 Linux System에서도 할 수 있겠지만, 아래의 가이드는 CentOS 7.7.1908 에서의 재현이 보장된다.)

1. `yum install rubygems`
2. `yum install ruby-devel`
3. `yum install gcc-c++`
4. `yum install redhat-rpm-config`
5. `yum install make`
6. `gem install asciidoctor-diagram --version=1.5.6`
7. `gem install ascii_binder`

위 7.단계에서 에러가 발생하면, 아래 과정을 추가로 진행한다.

1. `gem install "rubygems-update:<3.0.0" --no-document`
2. `update_rubygems`
3. `gem install ffi -v 1.12.2`
4. `gem install rb-inotify -v 0.9.10`
5. `gem install listen -v 3.0.8`
6. `gem install lumberjack -v 1.0.13`
7. `gem install ascii_binder`


== AsciiBinder 코드 수정하기
순정 상태의 AsciiBinder는 한국어를 제대로 지원하지 못한다.

docs를 빌드하면, 상단 breadcrumb 및 좌측 LNB tree의 각 node에 ID가 자동으로 부여된다. 이러한 ID는 각 노드의 이름에서 영문/숫자만 남기고 camel case로 이어붙이는 방식으로 생성된다. 이때 ID가 빈 스트링인 경우가 있거나 중복되는 경우가 있으면 빌드 결과에서의 정상적인 동작이 보장되지 않는다.

노드 이름에 한국어를 지원하기 위해, ID는 _topic_map.yml에서 직접 기입하도록 하고, 이 값을 사용할 수 있게 AsciiBinder의 코드를 수정하자.

1. `/usr/local/share/gems/gems/ascii_binder-0.1.15.3/lib/ascii_binder/topic_entity.rb` 파일을 열고, `module AsciiBinder > class TopicEntity` 의 `attr_reader` 에 `:id` 를 추가한다.
2. 단계 1.을 진행하는 부분 바로 아래의 `def initialize` 내용에 `@id = topic_entity['Id']` 줄을 추가한다.

----
require 'ascii_binder/helpers'
require 'trollop'

include AsciiBinder::Helpers

module AsciiBinder
  class TopicEntity
    ########################################################### 아래 attr_reader에 :id 를 추가한다. (1.)
    attr_reader :name, :id, :dir, :file, :topic_alias, :distro_keys, :subitems, :raw, :parent, :depth
    def initialize(topic_entity,actual_distro_keys,dir_path='',parent_group=nil,depth=0)
      @raw                = topic_entity
      @parent             = parent_group
      @dir_path           = dir_path
      @name               = topic_entity['Name']
      @id                 = topic_entity['Id'] ################################## 이 줄을 추가한다. (2.)
...
----



== 빌드하기

1. hypercloud-docs 프로젝트 폴더를 위 AsciiBinder가 설치된 환경에 업로드한다. (.git 파일도 포함되어 있어야 한다.)
2. `cd hypercloud-docs`
3. `chmod +x create_symlink.sh`
4. `./create_symlink.sh`
+
[NOTE]
====
`-bash: ./create_symlink.sh: /bin/bash^M: bad interpreter: No such file or directory` 에러가 발생할 수 있다.

이 경우, `vi create_symlink.sh` , esc 키, `:set fileformat=unix` , `:wq` 를 차례로 입력하여 해결할 수 있다.

또한 5.단계를 진행하려면 그때마다 3.과 4.를 진행하여야 한다.
====
5. `asciibinder build`
6. 새로 생성된 `hypercloud-docs/_preview` 폴더를 다운로드하고, 웹 서버에 띄워 테스트
7. hypercloud-docs 프로젝트 폴더를 삭제한다.
