[id="contributing-to-docs-tools-and-setup"]
= 빌드 환경 세팅하기, 빌드하기
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:linkattrs:
:description: How to set up and install the tools to contribute

toc::[]

== Install AsciiBinder and dependencies
All HyperCloud documentation is created in AsciiDoc, and is processed with https://github.com/redhataccess/ascii_binder[AsciiBinder],
which is an http://asciidoctor.org/[AsciiDoctor]-based docs management system.

=== Install the required software dependencies on a Linux system
The following instructions describe how to install all the required tools to do
live content editing on a Fedora Linux system.

1. Install the _RubyGems_ package with `yum install rubygems`
2. Install _Ruby_ development packages with `yum install ruby-devel`
3. Install _gcc_ with `yum install gcc-c++`
4. Install _redhat-rpm-config_ with `yum install redhat-rpm-config`
5. Install _make_ with `yum install make`
6. Install (1.5.6 version of) _asciidoctor-diagram_ with `gem install asciidoctor-diagram --version=1.5.6`
7. Install the _ascii_binder_ gem with `gem install ascii_binder`

NOTE: If you already have AsciiBinder installed, you might be due for an update.
These directions assume that you are using AsciiBinder 0.1.15 or newer. To check
and update if necessary, simply run `gem update ascii_binder`. Note that you might require root permissions.

=== Building the collection
With the initial setup complete, you are ready to build the collection.

1. From the `hypercloud-docs` directory, run an initial build:
+
----
$ cd hypercloud-docs
$ asciibinder build
----
2. Open the generated HTML file in your web browser. This will be located in the
`hypercloud-docs/_preview/<distro>/<branch>` directory, with the same path and
filename as the original `.adoc` file you edited, only it will be with the
`.html` extension.

== Clean up
The `.gitignore` file is set up to prevent anything under the `_preview` and
`_package` directories from being committed. However, you can reset the
environment manually by running:

----
$ asciibinder clean
----
