= Rook-Ceph 설치

다음은 Rook-Ceph을 설치하는 과정에 대한 설명이다.

. *바이너리 압축 해제*
+
hypercloud-rook-ceph-1.1.3 버전의 tar 파일을 압축 해제한다.
+
----
[root@master1 7.rook-ceph]# pwd
/root/hc-install/7.rook-ceph

[root@master1 7.rook-ceph]# ls
hypercloud-rook-ceph-1.1.3.tar

[root@master1 7.rook-ceph]# tar -xvf hypercloud-rook-ceph-1.1.3.tar
hypercloud-rook-ceph-1.1.3/
...
----

. *config 파일 설정*
+
Rook-Ceph 클러스터를 구성하기 위한 필수 config 정보들을 cluster.config에 입력한다.
+
----
[root@master1 hypercloud-rook-ceph-1.1.3]# pwd
/root/hc-install/7.rook-ceph/hypercloud-rook-ceph-1.1.3

[root@master1 hypercloud-rook-ceph-1.1.3]# vi cluster.config 
...
dockerRegistry=172.22.9.130:5000 <1>
osdDownOutInterval=80 <2>
----
<1> 이미지를 다운받기 위한 레지스트리 엔드포인트를 설정한다. +
만약 작성하지 않을 경우 기본값으로 public network에서 이미지를 다운받는다.
<2> Ceph 클러스터에서 다운된 osd를 out으로 처리하기까지의 시간을 설정한다. (단위 : 초) +
osd failure 시 해당 값만큼 Ceph 클러스터가 다운된 osd를 클러스터에서 제외시키지 않기 때문에 Ceph 클러스터 recovery 시간에 영향을 미친다. +
만약 작성하지 않을 경우 기본값으로 60초가 설정된다.

. *빌드 수행*
+
Rook-Ceph 클러스터 구성을 위해 사용될 yaml 파일들을 template 디렉터리로부터 빌드한다. +
빌드 명령어를 수행하면 deploy 디렉터리에 배포할 클러스터 yaml 파일들이 생성된다.
+
----
[root@master1 hypercloud-rook-ceph-1.1.3]# pwd
/root/hc-install/7.rook-ceph/hypercloud-rook-ceph-1.1.3

[root@master1 hypercloud-rook-ceph-1.1.3]# ./installer.sh build

[root@master1 hypercloud-rook-ceph-1.1.3]# ls deploy/
block_mysql.yaml    block_sc.yaml    ceph_config_override.yaml
....
----

. *설정*
+
구성할 Rook-Ceph 클러스터 스펙에 맞도록 deploy/cluster.yaml, deploy/file_system.yaml, deploy/block_pool.yaml 파일을 수정한다. +
cluster.yaml 설정의 경우 각 환경 정보를 기준으로 하여 구성할 Ceph 클러스터의 정보를 입력한다.
+
----
nodes:
- name: "master1"         # Add worker2 node to ceph-osd.
        directories:            # Add a directory of worker2 to ceph-osd.
        - path: "/root/testdir" # Caution: Directory must exist in worker2 node.
        devices:
        - name: "sdc" # Add disk of worker2 to ceph-osd. disk must exist in the nodes.
----

. *up 수행*
+
installer를 수행하여 실제 설치를 진행한다.
+
----
[root@master1 hypercloud-rook-ceph-1.1.3]# ./installer.sh up
==================== install rook =====================
Create ./deploy/common.yaml...
namespace/rook-ceph created
....
----

. *파드 확인*
+
Ceph 파드의 상태가 모두 ``Running``인 것을 확인한다.
+
----
[root@master1 ~]# k get pod -n rook-ceph
NAME                     READY    STATUS     RESTART    AGE
csi-cephfsplugin-c5l2d   3/3      Running    0          3m35s
csi-cephfsplugin-h6ns2   1/1      Running    0          3m35s
csi-cephfsplugin-m52m8   1/1      Running    0          3m35s
...
----

. *Ceph 상태 확인*
+
설치된 tools pod를 실행하여 *ceph -s* 명령으로 현재 상태를 확인한다.
+
----
[root@master1 hypercloud-rook-ceph-1.1.3]# k get pod -n rook-ceph|grep tools
rook-ceph-tools-5dd7b7589b-2wtb4         1/1     Running     0          8h

[root@master1 hypercloud-rook-ceph-1.1.3]# k exec -it -n rook-ceph rook-ceph-tools-5dd7b7589b-2wtb4 -- ceph -s <1>
  cluster:
    id:     5a46a606-9a15-4e0f-82fc-387a9a61ae37
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum a (age 75s)
    mgr: a(active, since 47s)
    mds: myfs:1 {0=myfs-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 39s), 3 in (since 39s)
 
  data:
    pools:   3 pools, 96 pgs
----
<1> k exec -it -n rook-ceph `{ceph tools pod 이름}` - - ceph -s